/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.saat.model.impl;

import at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink;
import at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLinkModel;
import at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLinkSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DictionaryDictionaryLink service. Represents a row in the &quot;saat_dictionary_dictionary_addiction_link&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DictionaryDictionaryLinkImpl}.
 * </p>
 *
 * @author reihsr
 * @see DictionaryDictionaryLinkImpl
 * @see at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink
 * @see at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLinkModel
 * @generated
 */
@JSON(strict = true)
public class DictionaryDictionaryLinkModelImpl extends BaseModelImpl<DictionaryDictionaryLink>
	implements DictionaryDictionaryLinkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dictionary dictionary link model instance should use the {@link at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink} interface instead.
	 */
	public static final String TABLE_NAME = "saat_dictionary_dictionary_addiction_link";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dictionary_dictionary_addiction_linkId", Types.BIGINT },
			{ "dictionaryId", Types.BIGINT },
			{ "addictionId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table saat_dictionary_dictionary_addiction_link (dictionary_dictionary_addiction_linkId LONG not null primary key,dictionaryId LONG,addictionId LONG)";
	public static final String TABLE_SQL_DROP = "drop table saat_dictionary_dictionary_addiction_link";
	public static final String ORDER_BY_JPQL = " ORDER BY dictionaryDictionaryLink.dictionary_dictionary_addiction_linkId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY saat_dictionary_dictionary_addiction_link.dictionary_dictionary_addiction_linkId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink"),
			true);
	public static long DICTIONARYID_COLUMN_BITMASK = 1L;
	public static long DICTIONARY_DICTIONARY_ADDICTION_LINKID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DictionaryDictionaryLink toModel(
		DictionaryDictionaryLinkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DictionaryDictionaryLink model = new DictionaryDictionaryLinkImpl();

		model.setDictionary_dictionary_addiction_linkId(soapModel.getDictionary_dictionary_addiction_linkId());
		model.setDictionaryId(soapModel.getDictionaryId());
		model.setAddictionId(soapModel.getAddictionId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DictionaryDictionaryLink> toModels(
		DictionaryDictionaryLinkSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DictionaryDictionaryLink> models = new ArrayList<DictionaryDictionaryLink>(soapModels.length);

		for (DictionaryDictionaryLinkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink"));

	public DictionaryDictionaryLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dictionary_dictionary_addiction_linkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDictionary_dictionary_addiction_linkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dictionary_dictionary_addiction_linkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DictionaryDictionaryLink.class;
	}

	@Override
	public String getModelClassName() {
		return DictionaryDictionaryLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dictionary_dictionary_addiction_linkId",
			getDictionary_dictionary_addiction_linkId());
		attributes.put("dictionaryId", getDictionaryId());
		attributes.put("addictionId", getAddictionId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dictionary_dictionary_addiction_linkId = (Long)attributes.get(
				"dictionary_dictionary_addiction_linkId");

		if (dictionary_dictionary_addiction_linkId != null) {
			setDictionary_dictionary_addiction_linkId(dictionary_dictionary_addiction_linkId);
		}

		Long dictionaryId = (Long)attributes.get("dictionaryId");

		if (dictionaryId != null) {
			setDictionaryId(dictionaryId);
		}

		Long addictionId = (Long)attributes.get("addictionId");

		if (addictionId != null) {
			setAddictionId(addictionId);
		}
	}

	@JSON
	@Override
	public long getDictionary_dictionary_addiction_linkId() {
		return _dictionary_dictionary_addiction_linkId;
	}

	@Override
	public void setDictionary_dictionary_addiction_linkId(
		long dictionary_dictionary_addiction_linkId) {
		_columnBitmask = -1L;

		_dictionary_dictionary_addiction_linkId = dictionary_dictionary_addiction_linkId;
	}

	@JSON
	@Override
	public long getDictionaryId() {
		return _dictionaryId;
	}

	@Override
	public void setDictionaryId(long dictionaryId) {
		_columnBitmask |= DICTIONARYID_COLUMN_BITMASK;

		if (!_setOriginalDictionaryId) {
			_setOriginalDictionaryId = true;

			_originalDictionaryId = _dictionaryId;
		}

		_dictionaryId = dictionaryId;
	}

	public long getOriginalDictionaryId() {
		return _originalDictionaryId;
	}

	@JSON
	@Override
	public long getAddictionId() {
		return _addictionId;
	}

	@Override
	public void setAddictionId(long addictionId) {
		_addictionId = addictionId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DictionaryDictionaryLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DictionaryDictionaryLink toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DictionaryDictionaryLink)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DictionaryDictionaryLinkImpl dictionaryDictionaryLinkImpl = new DictionaryDictionaryLinkImpl();

		dictionaryDictionaryLinkImpl.setDictionary_dictionary_addiction_linkId(getDictionary_dictionary_addiction_linkId());
		dictionaryDictionaryLinkImpl.setDictionaryId(getDictionaryId());
		dictionaryDictionaryLinkImpl.setAddictionId(getAddictionId());

		dictionaryDictionaryLinkImpl.resetOriginalValues();

		return dictionaryDictionaryLinkImpl;
	}

	@Override
	public int compareTo(DictionaryDictionaryLink dictionaryDictionaryLink) {
		int value = 0;

		if (getDictionary_dictionary_addiction_linkId() < dictionaryDictionaryLink.getDictionary_dictionary_addiction_linkId()) {
			value = -1;
		}
		else if (getDictionary_dictionary_addiction_linkId() > dictionaryDictionaryLink.getDictionary_dictionary_addiction_linkId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DictionaryDictionaryLink)) {
			return false;
		}

		DictionaryDictionaryLink dictionaryDictionaryLink = (DictionaryDictionaryLink)obj;

		long primaryKey = dictionaryDictionaryLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DictionaryDictionaryLinkModelImpl dictionaryDictionaryLinkModelImpl = this;

		dictionaryDictionaryLinkModelImpl._originalDictionaryId = dictionaryDictionaryLinkModelImpl._dictionaryId;

		dictionaryDictionaryLinkModelImpl._setOriginalDictionaryId = false;

		dictionaryDictionaryLinkModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DictionaryDictionaryLink> toCacheModel() {
		DictionaryDictionaryLinkCacheModel dictionaryDictionaryLinkCacheModel = new DictionaryDictionaryLinkCacheModel();

		dictionaryDictionaryLinkCacheModel.dictionary_dictionary_addiction_linkId = getDictionary_dictionary_addiction_linkId();

		dictionaryDictionaryLinkCacheModel.dictionaryId = getDictionaryId();

		dictionaryDictionaryLinkCacheModel.addictionId = getAddictionId();

		return dictionaryDictionaryLinkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{dictionary_dictionary_addiction_linkId=");
		sb.append(getDictionary_dictionary_addiction_linkId());
		sb.append(", dictionaryId=");
		sb.append(getDictionaryId());
		sb.append(", addictionId=");
		sb.append(getAddictionId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append(
			"at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dictionary_dictionary_addiction_linkId</column-name><column-value><![CDATA[");
		sb.append(getDictionary_dictionary_addiction_linkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dictionaryId</column-name><column-value><![CDATA[");
		sb.append(getDictionaryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>addictionId</column-name><column-value><![CDATA[");
		sb.append(getAddictionId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DictionaryDictionaryLink.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DictionaryDictionaryLink.class
		};
	private long _dictionary_dictionary_addiction_linkId;
	private long _dictionaryId;
	private long _originalDictionaryId;
	private boolean _setOriginalDictionaryId;
	private long _addictionId;
	private long _columnBitmask;
	private DictionaryDictionaryLink _escapedModel;
}