/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EventData service. Represents a row in the &quot;kdssmp.eventdata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.EventDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.EventDataImpl}.
 * </p>
 *
 * @author reihsr
 * @see EventData
 * @see at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.EventDataImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.EventDataModelImpl
 * @generated
 */
public interface EventDataModel extends BaseModel<EventData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event data model instance should use the {@link EventData} interface instead.
	 */

	/**
	 * Returns the primary key of this event data.
	 *
	 * @return the primary key of this event data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event data.
	 *
	 * @param primaryKey the primary key of this event data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the eventdata ID of this event data.
	 *
	 * @return the eventdata ID of this event data
	 */
	public long getEventdataId();

	/**
	 * Sets the eventdata ID of this event data.
	 *
	 * @param eventdataId the eventdata ID of this event data
	 */
	public void setEventdataId(long eventdataId);

	/**
	 * Returns the event ID of this event data.
	 *
	 * @return the event ID of this event data
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this event data.
	 *
	 * @param eventId the event ID of this event data
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the patient ID of this event data.
	 *
	 * @return the patient ID of this event data
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this event data.
	 *
	 * @param patientId the patient ID of this event data
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the ontology of this event data.
	 *
	 * @return the ontology of this event data
	 */
	@AutoEscape
	public String getOntology();

	/**
	 * Sets the ontology of this event data.
	 *
	 * @param ontology the ontology of this event data
	 */
	public void setOntology(String ontology);

	/**
	 * Returns the value of this event data.
	 *
	 * @return the value of this event data
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this event data.
	 *
	 * @param value the value of this event data
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EventData eventData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EventData> toCacheModel();

	@Override
	public EventData toEscapedModel();

	@Override
	public EventData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}