/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KdssmpPatient service. Represents a row in the &quot;kdssmp.patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.KdssmpPatientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.KdssmpPatientImpl}.
 * </p>
 *
 * @author reihsr
 * @see KdssmpPatient
 * @see at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.KdssmpPatientImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.KdssmpPatientModelImpl
 * @generated
 */
public interface KdssmpPatientModel extends BaseModel<KdssmpPatient> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kdssmp patient model instance should use the {@link KdssmpPatient} interface instead.
	 */

	/**
	 * Returns the primary key of this kdssmp patient.
	 *
	 * @return the primary key of this kdssmp patient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kdssmp patient.
	 *
	 * @param primaryKey the primary key of this kdssmp patient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patient ID of this kdssmp patient.
	 *
	 * @return the patient ID of this kdssmp patient
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this kdssmp patient.
	 *
	 * @param patientId the patient ID of this kdssmp patient
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the organization ID of this kdssmp patient.
	 *
	 * @return the organization ID of this kdssmp patient
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this kdssmp patient.
	 *
	 * @param organizationId the organization ID of this kdssmp patient
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the firstname of this kdssmp patient.
	 *
	 * @return the firstname of this kdssmp patient
	 */
	@AutoEscape
	public String getFirstname();

	/**
	 * Sets the firstname of this kdssmp patient.
	 *
	 * @param firstname the firstname of this kdssmp patient
	 */
	public void setFirstname(String firstname);

	/**
	 * Returns the lastname of this kdssmp patient.
	 *
	 * @return the lastname of this kdssmp patient
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this kdssmp patient.
	 *
	 * @param lastname the lastname of this kdssmp patient
	 */
	public void setLastname(String lastname);

	/**
	 * Returns the gender of this kdssmp patient.
	 *
	 * @return the gender of this kdssmp patient
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this kdssmp patient.
	 *
	 * @param gender the gender of this kdssmp patient
	 */
	public void setGender(String gender);

	/**
	 * Returns the dateofbirth of this kdssmp patient.
	 *
	 * @return the dateofbirth of this kdssmp patient
	 */
	public Date getDateofbirth();

	/**
	 * Sets the dateofbirth of this kdssmp patient.
	 *
	 * @param dateofbirth the dateofbirth of this kdssmp patient
	 */
	public void setDateofbirth(Date dateofbirth);

	/**
	 * Returns the dateofdeath of this kdssmp patient.
	 *
	 * @return the dateofdeath of this kdssmp patient
	 */
	public Date getDateofdeath();

	/**
	 * Sets the dateofdeath of this kdssmp patient.
	 *
	 * @param dateofdeath the dateofdeath of this kdssmp patient
	 */
	public void setDateofdeath(Date dateofdeath);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KdssmpPatient kdssmpPatient);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KdssmpPatient> toCacheModel();

	@Override
	public KdssmpPatient toEscapedModel();

	@Override
	public KdssmpPatient toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}