/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the KdssmpParameterOptions service. Represents a row in the &quot;kdssmp.parameteroptions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.KdssmpParameterOptionsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.KdssmpParameterOptionsImpl}.
 * </p>
 *
 * @author reihsr
 * @see KdssmpParameterOptions
 * @see at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.KdssmpParameterOptionsImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.KdssmpParameterOptionsModelImpl
 * @generated
 */
public interface KdssmpParameterOptionsModel extends BaseModel<KdssmpParameterOptions> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kdssmp parameter options model instance should use the {@link KdssmpParameterOptions} interface instead.
	 */

	/**
	 * Returns the primary key of this kdssmp parameter options.
	 *
	 * @return the primary key of this kdssmp parameter options
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kdssmp parameter options.
	 *
	 * @param primaryKey the primary key of this kdssmp parameter options
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the parameteroptions ID of this kdssmp parameter options.
	 *
	 * @return the parameteroptions ID of this kdssmp parameter options
	 */
	public long getParameteroptionsId();

	/**
	 * Sets the parameteroptions ID of this kdssmp parameter options.
	 *
	 * @param parameteroptionsId the parameteroptions ID of this kdssmp parameter options
	 */
	public void setParameteroptionsId(long parameteroptionsId);

	/**
	 * Returns the parameterconfiguration ID of this kdssmp parameter options.
	 *
	 * @return the parameterconfiguration ID of this kdssmp parameter options
	 */
	public long getParameterconfigurationId();

	/**
	 * Sets the parameterconfiguration ID of this kdssmp parameter options.
	 *
	 * @param parameterconfigurationId the parameterconfiguration ID of this kdssmp parameter options
	 */
	public void setParameterconfigurationId(long parameterconfigurationId);

	/**
	 * Returns the option of this kdssmp parameter options.
	 *
	 * @return the option of this kdssmp parameter options
	 */
	@AutoEscape
	public String getOption();

	/**
	 * Sets the option of this kdssmp parameter options.
	 *
	 * @param option the option of this kdssmp parameter options
	 */
	public void setOption(String option);

	/**
	 * Returns the value of this kdssmp parameter options.
	 *
	 * @return the value of this kdssmp parameter options
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this kdssmp parameter options.
	 *
	 * @param value the value of this kdssmp parameter options
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KdssmpParameterOptions kdssmpParameterOptions);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KdssmpParameterOptions> toCacheModel();

	@Override
	public KdssmpParameterOptions toEscapedModel();

	@Override
	public KdssmpParameterOptions toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}