/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the patientnamegenerator service. Represents a row in the &quot;kdssmp.patientnamegenerator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.patientnamegeneratorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.patientnamegeneratorImpl}.
 * </p>
 *
 * @author reihsr
 * @see patientnamegenerator
 * @see at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.patientnamegeneratorImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.kdssmp.service.model.impl.patientnamegeneratorModelImpl
 * @generated
 */
public interface patientnamegeneratorModel extends BaseModel<patientnamegenerator> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patientnamegenerator model instance should use the {@link patientnamegenerator} interface instead.
	 */

	/**
	 * Returns the primary key of this patientnamegenerator.
	 *
	 * @return the primary key of this patientnamegenerator
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patientnamegenerator.
	 *
	 * @param primaryKey the primary key of this patientnamegenerator
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patientnamegenerator ID of this patientnamegenerator.
	 *
	 * @return the patientnamegenerator ID of this patientnamegenerator
	 */
	public long getPatientnamegeneratorId();

	/**
	 * Sets the patientnamegenerator ID of this patientnamegenerator.
	 *
	 * @param patientnamegeneratorId the patientnamegenerator ID of this patientnamegenerator
	 */
	public void setPatientnamegeneratorId(long patientnamegeneratorId);

	/**
	 * Returns the name of this patientnamegenerator.
	 *
	 * @return the name of this patientnamegenerator
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this patientnamegenerator.
	 *
	 * @param name the name of this patientnamegenerator
	 */
	public void setName(String name);

	/**
	 * Returns the type of this patientnamegenerator.
	 *
	 * @return the type of this patientnamegenerator
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this patientnamegenerator.
	 *
	 * @param type the type of this patientnamegenerator
	 */
	public void setType(String type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(patientnamegenerator patientnamegenerator);

	@Override
	public int hashCode();

	@Override
	public CacheModel<patientnamegenerator> toCacheModel();

	@Override
	public patientnamegenerator toEscapedModel();

	@Override
	public patientnamegenerator toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}