/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.graz.patho.haybaeck.model.impl;

import at.meduni.graz.patho.haybaeck.model.Sample;
import at.meduni.graz.patho.haybaeck.service.SampleLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Sample service. Represents a row in the &quot;haybaeck.sample&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SampleImpl}.
 * </p>
 *
 * @author reihsr
 * @see SampleImpl
 * @see at.meduni.graz.patho.haybaeck.model.Sample
 * @generated
 */
public abstract class SampleBaseImpl extends SampleModelImpl implements Sample {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sample model instance should use the {@link Sample} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			SampleLocalServiceUtil.addSample(this);
		}
		else {
			SampleLocalServiceUtil.updateSample(this);
		}
	}
}