/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.bibbox.reactjsservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ToolInformation service. Represents a row in the &quot;reactjsservice_ToolInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.bibbox.reactjsservice.model.impl.ToolInformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.bibbox.reactjsservice.model.impl.ToolInformationImpl}.
 * </p>
 *
 * @author reihsr
 * @see ToolInformation
 * @see at.bibbox.reactjsservice.model.impl.ToolInformationImpl
 * @see at.bibbox.reactjsservice.model.impl.ToolInformationModelImpl
 * @generated
 */
public interface ToolInformationModel extends BaseModel<ToolInformation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tool information model instance should use the {@link ToolInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this tool information.
	 *
	 * @return the primary key of this tool information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tool information.
	 *
	 * @param primaryKey the primary key of this tool information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tool information ID of this tool information.
	 *
	 * @return the tool information ID of this tool information
	 */
	public long getToolInformationId();

	/**
	 * Sets the tool information ID of this tool information.
	 *
	 * @param toolInformationId the tool information ID of this tool information
	 */
	public void setToolInformationId(long toolInformationId);

	/**
	 * Returns the git u u i d of this tool information.
	 *
	 * @return the git u u i d of this tool information
	 */
	@AutoEscape
	public String getGitUUID();

	/**
	 * Sets the git u u i d of this tool information.
	 *
	 * @param gitUUID the git u u i d of this tool information
	 */
	public void setGitUUID(String gitUUID);

	/**
	 * Returns the logourl of this tool information.
	 *
	 * @return the logourl of this tool information
	 */
	@AutoEscape
	public String getLogourl();

	/**
	 * Sets the logourl of this tool information.
	 *
	 * @param logourl the logourl of this tool information
	 */
	public void setLogourl(String logourl);

	/**
	 * Returns the name of this tool information.
	 *
	 * @return the name of this tool information
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this tool information.
	 *
	 * @param name the name of this tool information
	 */
	public void setName(String name);

	/**
	 * Returns the category of this tool information.
	 *
	 * @return the category of this tool information
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this tool information.
	 *
	 * @param category the category of this tool information
	 */
	public void setCategory(String category);

	/**
	 * Returns the company of this tool information.
	 *
	 * @return the company of this tool information
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this tool information.
	 *
	 * @param company the company of this tool information
	 */
	public void setCompany(String company);

	/**
	 * Returns the demourl of this tool information.
	 *
	 * @return the demourl of this tool information
	 */
	@AutoEscape
	public String getDemourl();

	/**
	 * Sets the demourl of this tool information.
	 *
	 * @param demourl the demourl of this tool information
	 */
	public void setDemourl(String demourl);

	/**
	 * Returns the downloadurl of this tool information.
	 *
	 * @return the downloadurl of this tool information
	 */
	@AutoEscape
	public String getDownloadurl();

	/**
	 * Sets the downloadurl of this tool information.
	 *
	 * @param downloadurl the downloadurl of this tool information
	 */
	public void setDownloadurl(String downloadurl);

	/**
	 * Returns the tool ID of this tool information.
	 *
	 * @return the tool ID of this tool information
	 */
	@AutoEscape
	public String getToolId();

	/**
	 * Sets the tool ID of this tool information.
	 *
	 * @param toolId the tool ID of this tool information
	 */
	public void setToolId(String toolId);

	/**
	 * Returns the platform of this tool information.
	 *
	 * @return the platform of this tool information
	 */
	@AutoEscape
	public String getPlatform();

	/**
	 * Sets the platform of this tool information.
	 *
	 * @param platform the platform of this tool information
	 */
	public void setPlatform(String platform);

	/**
	 * Returns the license of this tool information.
	 *
	 * @return the license of this tool information
	 */
	@AutoEscape
	public String getLicense();

	/**
	 * Sets the license of this tool information.
	 *
	 * @param license the license of this tool information
	 */
	public void setLicense(String license);

	/**
	 * Returns the description of this tool information.
	 *
	 * @return the description of this tool information
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this tool information.
	 *
	 * @param description the description of this tool information
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ToolInformation toolInformation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ToolInformation> toCacheModel();

	@Override
	public ToolInformation toEscapedModel();

	@Override
	public ToolInformation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}