/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.saat.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DictionaryDictionaryLink service. Represents a row in the &quot;saat_dictionary_dictionary_addiction_link&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.saat.model.impl.DictionaryDictionaryLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.saat.model.impl.DictionaryDictionaryLinkImpl}.
 * </p>
 *
 * @author reihsr
 * @see DictionaryDictionaryLink
 * @see at.graz.meduni.liferay.portlet.saat.model.impl.DictionaryDictionaryLinkImpl
 * @see at.graz.meduni.liferay.portlet.saat.model.impl.DictionaryDictionaryLinkModelImpl
 * @generated
 */
public interface DictionaryDictionaryLinkModel extends BaseModel<DictionaryDictionaryLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dictionary dictionary link model instance should use the {@link DictionaryDictionaryLink} interface instead.
	 */

	/**
	 * Returns the primary key of this dictionary dictionary link.
	 *
	 * @return the primary key of this dictionary dictionary link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dictionary dictionary link.
	 *
	 * @param primaryKey the primary key of this dictionary dictionary link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dictionary_dictionary_addiction_link ID of this dictionary dictionary link.
	 *
	 * @return the dictionary_dictionary_addiction_link ID of this dictionary dictionary link
	 */
	public long getDictionary_dictionary_addiction_linkId();

	/**
	 * Sets the dictionary_dictionary_addiction_link ID of this dictionary dictionary link.
	 *
	 * @param dictionary_dictionary_addiction_linkId the dictionary_dictionary_addiction_link ID of this dictionary dictionary link
	 */
	public void setDictionary_dictionary_addiction_linkId(
		long dictionary_dictionary_addiction_linkId);

	/**
	 * Returns the dictionary ID of this dictionary dictionary link.
	 *
	 * @return the dictionary ID of this dictionary dictionary link
	 */
	public long getDictionaryId();

	/**
	 * Sets the dictionary ID of this dictionary dictionary link.
	 *
	 * @param dictionaryId the dictionary ID of this dictionary dictionary link
	 */
	public void setDictionaryId(long dictionaryId);

	/**
	 * Returns the addiction ID of this dictionary dictionary link.
	 *
	 * @return the addiction ID of this dictionary dictionary link
	 */
	public long getAddictionId();

	/**
	 * Sets the addiction ID of this dictionary dictionary link.
	 *
	 * @param addictionId the addiction ID of this dictionary dictionary link
	 */
	public void setAddictionId(long addictionId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink dictionaryDictionaryLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink> toCacheModel();

	@Override
	public at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink toEscapedModel();

	@Override
	public at.graz.meduni.liferay.portlet.saat.model.DictionaryDictionaryLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}