/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.saat.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ICD10 service. Represents a row in the &quot;saat_code_icd10&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.saat.model.impl.ICD10ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.saat.model.impl.ICD10Impl}.
 * </p>
 *
 * @author reihsr
 * @see ICD10
 * @see at.graz.meduni.liferay.portlet.saat.model.impl.ICD10Impl
 * @see at.graz.meduni.liferay.portlet.saat.model.impl.ICD10ModelImpl
 * @generated
 */
public interface ICD10Model extends BaseModel<ICD10> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a i c d10 model instance should use the {@link ICD10} interface instead.
	 */

	/**
	 * Returns the primary key of this i c d10.
	 *
	 * @return the primary key of this i c d10
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this i c d10.
	 *
	 * @param primaryKey the primary key of this i c d10
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the icd10 ID of this i c d10.
	 *
	 * @return the icd10 ID of this i c d10
	 */
	public long getIcd10Id();

	/**
	 * Sets the icd10 ID of this i c d10.
	 *
	 * @param icd10Id the icd10 ID of this i c d10
	 */
	public void setIcd10Id(long icd10Id);

	/**
	 * Returns the code of this i c d10.
	 *
	 * @return the code of this i c d10
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this i c d10.
	 *
	 * @param code the code of this i c d10
	 */
	public void setCode(String code);

	/**
	 * Returns the description of this i c d10.
	 *
	 * @return the description of this i c d10
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this i c d10.
	 *
	 * @param description the description of this i c d10
	 */
	public void setDescription(String description);

	/**
	 * Returns the i n k l u s i v a of this i c d10.
	 *
	 * @return the i n k l u s i v a of this i c d10
	 */
	@AutoEscape
	public String getINKLUSIVA();

	/**
	 * Sets the i n k l u s i v a of this i c d10.
	 *
	 * @param INKLUSIVA the i n k l u s i v a of this i c d10
	 */
	public void setINKLUSIVA(String INKLUSIVA);

	/**
	 * Returns the e x k l u s i v a of this i c d10.
	 *
	 * @return the e x k l u s i v a of this i c d10
	 */
	@AutoEscape
	public String getEXKLUSIVA();

	/**
	 * Sets the e x k l u s i v a of this i c d10.
	 *
	 * @param EXKLUSIVA the e x k l u s i v a of this i c d10
	 */
	public void setEXKLUSIVA(String EXKLUSIVA);

	/**
	 * Returns the t y p e of this i c d10.
	 *
	 * @return the t y p e of this i c d10
	 */
	@AutoEscape
	public String getTYPE();

	/**
	 * Sets the t y p e of this i c d10.
	 *
	 * @param TYPE the t y p e of this i c d10
	 */
	public void setTYPE(String TYPE);

	/**
	 * Returns the u s e d of this i c d10.
	 *
	 * @return the u s e d of this i c d10
	 */
	public double getUSED();

	/**
	 * Sets the u s e d of this i c d10.
	 *
	 * @param USED the u s e d of this i c d10
	 */
	public void setUSED(double USED);

	/**
	 * Returns the f r o m_ c o d e of this i c d10.
	 *
	 * @return the f r o m_ c o d e of this i c d10
	 */
	@AutoEscape
	public String getFROM_CODE();

	/**
	 * Sets the f r o m_ c o d e of this i c d10.
	 *
	 * @param FROM_CODE the f r o m_ c o d e of this i c d10
	 */
	public void setFROM_CODE(String FROM_CODE);

	/**
	 * Returns the t o_ c o d e of this i c d10.
	 *
	 * @return the t o_ c o d e of this i c d10
	 */
	@AutoEscape
	public String getTO_CODE();

	/**
	 * Sets the t o_ c o d e of this i c d10.
	 *
	 * @param TO_CODE the t o_ c o d e of this i c d10
	 */
	public void setTO_CODE(String TO_CODE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(at.graz.meduni.liferay.portlet.saat.model.ICD10 icd10);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.liferay.portlet.saat.model.ICD10> toCacheModel();

	@Override
	public at.graz.meduni.liferay.portlet.saat.model.ICD10 toEscapedModel();

	@Override
	public at.graz.meduni.liferay.portlet.saat.model.ICD10 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}