/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.model.impl;

import at.graz.meduni.liferay.model.ICDO3;
import at.graz.meduni.liferay.service.ICDO3LocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ICDO3 service. Represents a row in the &quot;code_icdo3&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ICDO3Impl}.
 * </p>
 *
 * @author reihsr
 * @see ICDO3Impl
 * @see at.graz.meduni.liferay.model.ICDO3
 * @generated
 */
public abstract class ICDO3BaseImpl extends ICDO3ModelImpl implements ICDO3 {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a i c d o3 model instance should use the {@link ICDO3} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ICDO3LocalServiceUtil.addICDO3(this);
		}
		else {
			ICDO3LocalServiceUtil.updateICDO3(this);
		}
	}
}