/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Gene service. Represents a row in the &quot;ontologies.gene&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneImpl}.
 * </p>
 *
 * @author reihsr
 * @see Gene
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneModelImpl
 * @generated
 */
public interface GeneModel extends BaseModel<Gene> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gene model instance should use the {@link Gene} interface instead.
	 */

	/**
	 * Returns the primary key of this gene.
	 *
	 * @return the primary key of this gene
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gene.
	 *
	 * @param primaryKey the primary key of this gene
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the gene ID of this gene.
	 *
	 * @return the gene ID of this gene
	 */
	public long getGeneId();

	/**
	 * Sets the gene ID of this gene.
	 *
	 * @param geneId the gene ID of this gene
	 */
	public void setGeneId(long geneId);

	/**
	 * Returns the orphanetdisorder ID of this gene.
	 *
	 * @return the orphanetdisorder ID of this gene
	 */
	public long getOrphanetdisorderId();

	/**
	 * Sets the orphanetdisorder ID of this gene.
	 *
	 * @param orphanetdisorderId the orphanetdisorder ID of this gene
	 */
	public void setOrphanetdisorderId(long orphanetdisorderId);

	/**
	 * Returns the symbol of this gene.
	 *
	 * @return the symbol of this gene
	 */
	@AutoEscape
	public String getSymbol();

	/**
	 * Sets the symbol of this gene.
	 *
	 * @param symbol the symbol of this gene
	 */
	public void setSymbol(String symbol);

	/**
	 * Returns the description of this gene.
	 *
	 * @return the description of this gene
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this gene.
	 *
	 * @param description the description of this gene
	 */
	public void setDescription(String description);

	/**
	 * Returns the geneorphanumber of this gene.
	 *
	 * @return the geneorphanumber of this gene
	 */
	public long getGeneorphanumber();

	/**
	 * Sets the geneorphanumber of this gene.
	 *
	 * @param geneorphanumber the geneorphanumber of this gene
	 */
	public void setGeneorphanumber(long geneorphanumber);

	/**
	 * Returns the genetype of this gene.
	 *
	 * @return the genetype of this gene
	 */
	public long getGenetype();

	/**
	 * Sets the genetype of this gene.
	 *
	 * @param genetype the genetype of this gene
	 */
	public void setGenetype(long genetype);

	/**
	 * Returns the genetypeorphanumber of this gene.
	 *
	 * @return the genetypeorphanumber of this gene
	 */
	public long getGenetypeorphanumber();

	/**
	 * Sets the genetypeorphanumber of this gene.
	 *
	 * @param genetypeorphanumber the genetypeorphanumber of this gene
	 */
	public void setGenetypeorphanumber(long genetypeorphanumber);

	/**
	 * Returns the genetypename of this gene.
	 *
	 * @return the genetypename of this gene
	 */
	@AutoEscape
	public String getGenetypename();

	/**
	 * Sets the genetypename of this gene.
	 *
	 * @param genetypename the genetypename of this gene
	 */
	public void setGenetypename(String genetypename);

	/**
	 * Returns the disordergeneassociationtype of this gene.
	 *
	 * @return the disordergeneassociationtype of this gene
	 */
	public long getDisordergeneassociationtype();

	/**
	 * Sets the disordergeneassociationtype of this gene.
	 *
	 * @param disordergeneassociationtype the disordergeneassociationtype of this gene
	 */
	public void setDisordergeneassociationtype(long disordergeneassociationtype);

	/**
	 * Returns the disordergeneassociationtypename of this gene.
	 *
	 * @return the disordergeneassociationtypename of this gene
	 */
	@AutoEscape
	public String getDisordergeneassociationtypename();

	/**
	 * Sets the disordergeneassociationtypename of this gene.
	 *
	 * @param disordergeneassociationtypename the disordergeneassociationtypename of this gene
	 */
	public void setDisordergeneassociationtypename(
		String disordergeneassociationtypename);

	/**
	 * Returns the disordergeneassociationstatus of this gene.
	 *
	 * @return the disordergeneassociationstatus of this gene
	 */
	public long getDisordergeneassociationstatus();

	/**
	 * Sets the disordergeneassociationstatus of this gene.
	 *
	 * @param disordergeneassociationstatus the disordergeneassociationstatus of this gene
	 */
	public void setDisordergeneassociationstatus(
		long disordergeneassociationstatus);

	/**
	 * Returns the disordergeneassociationstatusname of this gene.
	 *
	 * @return the disordergeneassociationstatusname of this gene
	 */
	@AutoEscape
	public String getDisordergeneassociationstatusname();

	/**
	 * Sets the disordergeneassociationstatusname of this gene.
	 *
	 * @param disordergeneassociationstatusname the disordergeneassociationstatusname of this gene
	 */
	public void setDisordergeneassociationstatusname(
		String disordergeneassociationstatusname);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Gene gene);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Gene> toCacheModel();

	@Override
	public Gene toEscapedModel();

	@Override
	public Gene toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}