/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the GeneSynonym service. Represents a row in the &quot;ontologies.genesynonym&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneSynonymModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneSynonymImpl}.
 * </p>
 *
 * @author reihsr
 * @see GeneSynonym
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneSynonymImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneSynonymModelImpl
 * @generated
 */
public interface GeneSynonymModel extends BaseModel<GeneSynonym> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gene synonym model instance should use the {@link GeneSynonym} interface instead.
	 */

	/**
	 * Returns the primary key of this gene synonym.
	 *
	 * @return the primary key of this gene synonym
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gene synonym.
	 *
	 * @param primaryKey the primary key of this gene synonym
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the genesynonym ID of this gene synonym.
	 *
	 * @return the genesynonym ID of this gene synonym
	 */
	public long getGenesynonymId();

	/**
	 * Sets the genesynonym ID of this gene synonym.
	 *
	 * @param genesynonymId the genesynonym ID of this gene synonym
	 */
	public void setGenesynonymId(long genesynonymId);

	/**
	 * Returns the gene ID of this gene synonym.
	 *
	 * @return the gene ID of this gene synonym
	 */
	public long getGeneId();

	/**
	 * Sets the gene ID of this gene synonym.
	 *
	 * @param geneId the gene ID of this gene synonym
	 */
	public void setGeneId(long geneId);

	/**
	 * Returns the synonym of this gene synonym.
	 *
	 * @return the synonym of this gene synonym
	 */
	@AutoEscape
	public String getSynonym();

	/**
	 * Sets the synonym of this gene synonym.
	 *
	 * @param synonym the synonym of this gene synonym
	 */
	public void setSynonym(String synonym);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GeneSynonym geneSynonym);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GeneSynonym> toCacheModel();

	@Override
	public GeneSynonym toEscapedModel();

	@Override
	public GeneSynonym toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}