/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the GeneLocus service. Represents a row in the &quot;ontologies.genelocus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneLocusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneLocusImpl}.
 * </p>
 *
 * @author reihsr
 * @see GeneLocus
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneLocusImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.GeneLocusModelImpl
 * @generated
 */
public interface GeneLocusModel extends BaseModel<GeneLocus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gene locus model instance should use the {@link GeneLocus} interface instead.
	 */

	/**
	 * Returns the primary key of this gene locus.
	 *
	 * @return the primary key of this gene locus
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gene locus.
	 *
	 * @param primaryKey the primary key of this gene locus
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the genelocus ID of this gene locus.
	 *
	 * @return the genelocus ID of this gene locus
	 */
	public long getGenelocusId();

	/**
	 * Sets the genelocus ID of this gene locus.
	 *
	 * @param genelocusId the genelocus ID of this gene locus
	 */
	public void setGenelocusId(long genelocusId);

	/**
	 * Returns the gene ID of this gene locus.
	 *
	 * @return the gene ID of this gene locus
	 */
	public long getGeneId();

	/**
	 * Sets the gene ID of this gene locus.
	 *
	 * @param geneId the gene ID of this gene locus
	 */
	public void setGeneId(long geneId);

	/**
	 * Returns the genelocus of this gene locus.
	 *
	 * @return the genelocus of this gene locus
	 */
	@AutoEscape
	public String getGenelocus();

	/**
	 * Sets the genelocus of this gene locus.
	 *
	 * @param genelocus the genelocus of this gene locus
	 */
	public void setGenelocus(String genelocus);

	/**
	 * Returns the genelocuskey of this gene locus.
	 *
	 * @return the genelocuskey of this gene locus
	 */
	@AutoEscape
	public String getGenelocuskey();

	/**
	 * Sets the genelocuskey of this gene locus.
	 *
	 * @param genelocuskey the genelocuskey of this gene locus
	 */
	public void setGenelocuskey(String genelocuskey);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GeneLocus geneLocus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GeneLocus> toCacheModel();

	@Override
	public GeneLocus toEscapedModel();

	@Override
	public GeneLocus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}