/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the OrganizationSearchIndex service. Represents a row in the &quot;rdconnect.searchindex_rdconnect&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.OrganizationSearchIndexModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.OrganizationSearchIndexImpl}.
 * </p>
 *
 * @author reihsr
 * @see OrganizationSearchIndex
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.OrganizationSearchIndexImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.OrganizationSearchIndexModelImpl
 * @generated
 */
public interface OrganizationSearchIndexModel extends BaseModel<OrganizationSearchIndex> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a organization search index model instance should use the {@link OrganizationSearchIndex} interface instead.
	 */

	/**
	 * Returns the primary key of this organization search index.
	 *
	 * @return the primary key of this organization search index
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this organization search index.
	 *
	 * @param primaryKey the primary key of this organization search index
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the searchid of this organization search index.
	 *
	 * @return the searchid of this organization search index
	 */
	public long getSearchid();

	/**
	 * Sets the searchid of this organization search index.
	 *
	 * @param searchid the searchid of this organization search index
	 */
	public void setSearchid(long searchid);

	/**
	 * Returns the organisationid of this organization search index.
	 *
	 * @return the organisationid of this organization search index
	 */
	public long getOrganisationid();

	/**
	 * Sets the organisationid of this organization search index.
	 *
	 * @param organisationid the organisationid of this organization search index
	 */
	public void setOrganisationid(long organisationid);

	/**
	 * Returns the locationid of this organization search index.
	 *
	 * @return the locationid of this organization search index
	 */
	public long getLocationid();

	/**
	 * Sets the locationid of this organization search index.
	 *
	 * @param locationid the locationid of this organization search index
	 */
	public void setLocationid(long locationid);

	/**
	 * Returns the location of this organization search index.
	 *
	 * @return the location of this organization search index
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this organization search index.
	 *
	 * @param location the location of this organization search index
	 */
	public void setLocation(String location);

	/**
	 * Returns the key of this organization search index.
	 *
	 * @return the key of this organization search index
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this organization search index.
	 *
	 * @param key the key of this organization search index
	 */
	public void setKey(String key);

	/**
	 * Returns the searchvalue of this organization search index.
	 *
	 * @return the searchvalue of this organization search index
	 */
	@AutoEscape
	public String getSearchvalue();

	/**
	 * Sets the searchvalue of this organization search index.
	 *
	 * @param searchvalue the searchvalue of this organization search index
	 */
	public void setSearchvalue(String searchvalue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OrganizationSearchIndex organizationSearchIndex);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OrganizationSearchIndex> toCacheModel();

	@Override
	public OrganizationSearchIndex toEscapedModel();

	@Override
	public OrganizationSearchIndex toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}