/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the OrphanetDisorder service. Represents a row in the &quot;ontologies.orphanetdisorder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.OrphanetDisorderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.model.impl.OrphanetDisorderImpl}.
 * </p>
 *
 * @author reihsr
 * @see OrphanetDisorder
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.OrphanetDisorderImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.model.impl.OrphanetDisorderModelImpl
 * @generated
 */
public interface OrphanetDisorderModel extends BaseModel<OrphanetDisorder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a orphanet disorder model instance should use the {@link OrphanetDisorder} interface instead.
	 */

	/**
	 * Returns the primary key of this orphanet disorder.
	 *
	 * @return the primary key of this orphanet disorder
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this orphanet disorder.
	 *
	 * @param primaryKey the primary key of this orphanet disorder
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the orphanetdisorder ID of this orphanet disorder.
	 *
	 * @return the orphanetdisorder ID of this orphanet disorder
	 */
	public long getOrphanetdisorderId();

	/**
	 * Sets the orphanetdisorder ID of this orphanet disorder.
	 *
	 * @param orphanetdisorderId the orphanetdisorder ID of this orphanet disorder
	 */
	public void setOrphanetdisorderId(long orphanetdisorderId);

	/**
	 * Returns the orphanumber of this orphanet disorder.
	 *
	 * @return the orphanumber of this orphanet disorder
	 */
	public long getOrphanumber();

	/**
	 * Sets the orphanumber of this orphanet disorder.
	 *
	 * @param orphanumber the orphanumber of this orphanet disorder
	 */
	public void setOrphanumber(long orphanumber);

	/**
	 * Returns the orpahnetlink of this orphanet disorder.
	 *
	 * @return the orpahnetlink of this orphanet disorder
	 */
	@AutoEscape
	public String getOrpahnetlink();

	/**
	 * Sets the orpahnetlink of this orphanet disorder.
	 *
	 * @param orpahnetlink the orpahnetlink of this orphanet disorder
	 */
	public void setOrpahnetlink(String orpahnetlink);

	/**
	 * Returns the diseasename of this orphanet disorder.
	 *
	 * @return the diseasename of this orphanet disorder
	 */
	@AutoEscape
	public String getDiseasename();

	/**
	 * Sets the diseasename of this orphanet disorder.
	 *
	 * @param diseasename the diseasename of this orphanet disorder
	 */
	public void setDiseasename(String diseasename);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OrphanetDisorder orphanetDisorder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OrphanetDisorder> toCacheModel();

	@Override
	public OrphanetDisorder toEscapedModel();

	@Override
	public OrphanetDisorder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}