/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.hmmc.liferay.portlet.puch.model.impl;

import at.graz.hmmc.liferay.portlet.puch.model.Fahrzeug;
import at.graz.hmmc.liferay.portlet.puch.model.FahrzeugModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Fahrzeug service. Represents a row in the &quot;puchmuseum.fahrzeug&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link at.graz.hmmc.liferay.portlet.puch.model.FahrzeugModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FahrzeugImpl}.
 * </p>
 *
 * @author reihsr
 * @see FahrzeugImpl
 * @see at.graz.hmmc.liferay.portlet.puch.model.Fahrzeug
 * @see at.graz.hmmc.liferay.portlet.puch.model.FahrzeugModel
 * @generated
 */
public class FahrzeugModelImpl extends BaseModelImpl<Fahrzeug>
	implements FahrzeugModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fahrzeug model instance should use the {@link at.graz.hmmc.liferay.portlet.puch.model.Fahrzeug} interface instead.
	 */
	public static final String TABLE_NAME = "puchmuseum.fahrzeug";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fahrzeugId", Types.BIGINT },
			{ "createrUserId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedUserId", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "typ", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table puchmuseum.fahrzeug (fahrzeugId LONG not null primary key,createrUserId LONG,createDate DATE null,modifiedUserId LONG,modifiedDate DATE null,typ VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table puchmuseum.fahrzeug";
	public static final String ORDER_BY_JPQL = " ORDER BY fahrzeug.typ ASC";
	public static final String ORDER_BY_SQL = " ORDER BY puchmuseum.fahrzeug.typ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.hmmc.liferay.portlet.puch.model.Fahrzeug"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.hmmc.liferay.portlet.puch.model.Fahrzeug"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.hmmc.liferay.portlet.puch.model.Fahrzeug"),
			true);
	public static long TYP_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.at.graz.hmmc.liferay.portlet.puch.model.Fahrzeug"));

	public FahrzeugModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fahrzeugId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFahrzeugId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fahrzeugId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Fahrzeug.class;
	}

	@Override
	public String getModelClassName() {
		return Fahrzeug.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fahrzeugId", getFahrzeugId());
		attributes.put("createrUserId", getCreaterUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedUserId", getModifiedUserId());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("typ", getTyp());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fahrzeugId = (Long)attributes.get("fahrzeugId");

		if (fahrzeugId != null) {
			setFahrzeugId(fahrzeugId);
		}

		Long createrUserId = (Long)attributes.get("createrUserId");

		if (createrUserId != null) {
			setCreaterUserId(createrUserId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long modifiedUserId = (Long)attributes.get("modifiedUserId");

		if (modifiedUserId != null) {
			setModifiedUserId(modifiedUserId);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String typ = (String)attributes.get("typ");

		if (typ != null) {
			setTyp(typ);
		}
	}

	@Override
	public long getFahrzeugId() {
		return _fahrzeugId;
	}

	@Override
	public void setFahrzeugId(long fahrzeugId) {
		_fahrzeugId = fahrzeugId;
	}

	@Override
	public long getCreaterUserId() {
		return _createrUserId;
	}

	@Override
	public void setCreaterUserId(long createrUserId) {
		_createrUserId = createrUserId;
	}

	@Override
	public String getCreaterUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getCreaterUserId(), "uuid",
			_createrUserUuid);
	}

	@Override
	public void setCreaterUserUuid(String createrUserUuid) {
		_createrUserUuid = createrUserUuid;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public long getModifiedUserId() {
		return _modifiedUserId;
	}

	@Override
	public void setModifiedUserId(long modifiedUserId) {
		_modifiedUserId = modifiedUserId;
	}

	@Override
	public String getModifiedUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getModifiedUserId(), "uuid",
			_modifiedUserUuid);
	}

	@Override
	public void setModifiedUserUuid(String modifiedUserUuid) {
		_modifiedUserUuid = modifiedUserUuid;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getTyp() {
		if (_typ == null) {
			return StringPool.BLANK;
		}
		else {
			return _typ;
		}
	}

	@Override
	public void setTyp(String typ) {
		_columnBitmask = -1L;

		if (_originalTyp == null) {
			_originalTyp = _typ;
		}

		_typ = typ;
	}

	public String getOriginalTyp() {
		return GetterUtil.getString(_originalTyp);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Fahrzeug.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Fahrzeug toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Fahrzeug)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FahrzeugImpl fahrzeugImpl = new FahrzeugImpl();

		fahrzeugImpl.setFahrzeugId(getFahrzeugId());
		fahrzeugImpl.setCreaterUserId(getCreaterUserId());
		fahrzeugImpl.setCreateDate(getCreateDate());
		fahrzeugImpl.setModifiedUserId(getModifiedUserId());
		fahrzeugImpl.setModifiedDate(getModifiedDate());
		fahrzeugImpl.setTyp(getTyp());

		fahrzeugImpl.resetOriginalValues();

		return fahrzeugImpl;
	}

	@Override
	public int compareTo(Fahrzeug fahrzeug) {
		int value = 0;

		value = getTyp().compareTo(fahrzeug.getTyp());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Fahrzeug)) {
			return false;
		}

		Fahrzeug fahrzeug = (Fahrzeug)obj;

		long primaryKey = fahrzeug.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FahrzeugModelImpl fahrzeugModelImpl = this;

		fahrzeugModelImpl._originalTyp = fahrzeugModelImpl._typ;

		fahrzeugModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Fahrzeug> toCacheModel() {
		FahrzeugCacheModel fahrzeugCacheModel = new FahrzeugCacheModel();

		fahrzeugCacheModel.fahrzeugId = getFahrzeugId();

		fahrzeugCacheModel.createrUserId = getCreaterUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			fahrzeugCacheModel.createDate = createDate.getTime();
		}
		else {
			fahrzeugCacheModel.createDate = Long.MIN_VALUE;
		}

		fahrzeugCacheModel.modifiedUserId = getModifiedUserId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fahrzeugCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			fahrzeugCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		fahrzeugCacheModel.typ = getTyp();

		String typ = fahrzeugCacheModel.typ;

		if ((typ != null) && (typ.length() == 0)) {
			fahrzeugCacheModel.typ = null;
		}

		return fahrzeugCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{fahrzeugId=");
		sb.append(getFahrzeugId());
		sb.append(", createrUserId=");
		sb.append(getCreaterUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedUserId=");
		sb.append(getModifiedUserId());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", typ=");
		sb.append(getTyp());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("at.graz.hmmc.liferay.portlet.puch.model.Fahrzeug");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fahrzeugId</column-name><column-value><![CDATA[");
		sb.append(getFahrzeugId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createrUserId</column-name><column-value><![CDATA[");
		sb.append(getCreaterUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedUserId</column-name><column-value><![CDATA[");
		sb.append(getModifiedUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typ</column-name><column-value><![CDATA[");
		sb.append(getTyp());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Fahrzeug.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Fahrzeug.class
		};
	private long _fahrzeugId;
	private long _createrUserId;
	private String _createrUserUuid;
	private Date _createDate;
	private long _modifiedUserId;
	private String _modifiedUserUuid;
	private Date _modifiedDate;
	private String _typ;
	private String _originalTyp;
	private long _columnBitmask;
	private Fahrzeug _escapedModel;
}