/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.hmmc.liferay.portlet.puch.model.impl;

import at.graz.hmmc.liferay.portlet.puch.model.ObjectImage;
import at.graz.hmmc.liferay.portlet.puch.model.ObjectImageModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ObjectImage service. Represents a row in the &quot;puchmuseum_objectimage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link at.graz.hmmc.liferay.portlet.puch.model.ObjectImageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObjectImageImpl}.
 * </p>
 *
 * @author reihsr
 * @see ObjectImageImpl
 * @see at.graz.hmmc.liferay.portlet.puch.model.ObjectImage
 * @see at.graz.hmmc.liferay.portlet.puch.model.ObjectImageModel
 * @generated
 */
public class ObjectImageModelImpl extends BaseModelImpl<ObjectImage>
	implements ObjectImageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a object image model instance should use the {@link at.graz.hmmc.liferay.portlet.puch.model.ObjectImage} interface instead.
	 */
	public static final String TABLE_NAME = "puchmuseum_objectimage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "objectimageId", Types.BIGINT },
			{ "puchmuseumsobjectId", Types.BIGINT },
			{ "createrUserId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedUserId", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "dlappimagerawId", Types.BIGINT },
			{ "dlappimageprocessedId", Types.BIGINT },
			{ "dlappimagewebId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table puchmuseum_objectimage (objectimageId LONG not null primary key,puchmuseumsobjectId LONG,createrUserId LONG,createDate DATE null,modifiedUserId LONG,modifiedDate DATE null,dlappimagerawId LONG,dlappimageprocessedId LONG,dlappimagewebId LONG)";
	public static final String TABLE_SQL_DROP = "drop table puchmuseum_objectimage";
	public static final String ORDER_BY_JPQL = " ORDER BY objectImage.objectimageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY puchmuseum_objectimage.objectimageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.hmmc.liferay.portlet.puch.model.ObjectImage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.hmmc.liferay.portlet.puch.model.ObjectImage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.hmmc.liferay.portlet.puch.model.ObjectImage"),
			true);
	public static long PUCHMUSEUMSOBJECTID_COLUMN_BITMASK = 1L;
	public static long OBJECTIMAGEID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.at.graz.hmmc.liferay.portlet.puch.model.ObjectImage"));

	public ObjectImageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _objectimageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setObjectimageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _objectimageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ObjectImage.class;
	}

	@Override
	public String getModelClassName() {
		return ObjectImage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("objectimageId", getObjectimageId());
		attributes.put("puchmuseumsobjectId", getPuchmuseumsobjectId());
		attributes.put("createrUserId", getCreaterUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedUserId", getModifiedUserId());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("dlappimagerawId", getDlappimagerawId());
		attributes.put("dlappimageprocessedId", getDlappimageprocessedId());
		attributes.put("dlappimagewebId", getDlappimagewebId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long objectimageId = (Long)attributes.get("objectimageId");

		if (objectimageId != null) {
			setObjectimageId(objectimageId);
		}

		Long puchmuseumsobjectId = (Long)attributes.get("puchmuseumsobjectId");

		if (puchmuseumsobjectId != null) {
			setPuchmuseumsobjectId(puchmuseumsobjectId);
		}

		Long createrUserId = (Long)attributes.get("createrUserId");

		if (createrUserId != null) {
			setCreaterUserId(createrUserId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long modifiedUserId = (Long)attributes.get("modifiedUserId");

		if (modifiedUserId != null) {
			setModifiedUserId(modifiedUserId);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long dlappimagerawId = (Long)attributes.get("dlappimagerawId");

		if (dlappimagerawId != null) {
			setDlappimagerawId(dlappimagerawId);
		}

		Long dlappimageprocessedId = (Long)attributes.get(
				"dlappimageprocessedId");

		if (dlappimageprocessedId != null) {
			setDlappimageprocessedId(dlappimageprocessedId);
		}

		Long dlappimagewebId = (Long)attributes.get("dlappimagewebId");

		if (dlappimagewebId != null) {
			setDlappimagewebId(dlappimagewebId);
		}
	}

	@Override
	public long getObjectimageId() {
		return _objectimageId;
	}

	@Override
	public void setObjectimageId(long objectimageId) {
		_objectimageId = objectimageId;
	}

	@Override
	public long getPuchmuseumsobjectId() {
		return _puchmuseumsobjectId;
	}

	@Override
	public void setPuchmuseumsobjectId(long puchmuseumsobjectId) {
		_columnBitmask |= PUCHMUSEUMSOBJECTID_COLUMN_BITMASK;

		if (!_setOriginalPuchmuseumsobjectId) {
			_setOriginalPuchmuseumsobjectId = true;

			_originalPuchmuseumsobjectId = _puchmuseumsobjectId;
		}

		_puchmuseumsobjectId = puchmuseumsobjectId;
	}

	public long getOriginalPuchmuseumsobjectId() {
		return _originalPuchmuseumsobjectId;
	}

	@Override
	public long getCreaterUserId() {
		return _createrUserId;
	}

	@Override
	public void setCreaterUserId(long createrUserId) {
		_createrUserId = createrUserId;
	}

	@Override
	public String getCreaterUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getCreaterUserId(), "uuid",
			_createrUserUuid);
	}

	@Override
	public void setCreaterUserUuid(String createrUserUuid) {
		_createrUserUuid = createrUserUuid;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public long getModifiedUserId() {
		return _modifiedUserId;
	}

	@Override
	public void setModifiedUserId(long modifiedUserId) {
		_modifiedUserId = modifiedUserId;
	}

	@Override
	public String getModifiedUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getModifiedUserId(), "uuid",
			_modifiedUserUuid);
	}

	@Override
	public void setModifiedUserUuid(String modifiedUserUuid) {
		_modifiedUserUuid = modifiedUserUuid;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getDlappimagerawId() {
		return _dlappimagerawId;
	}

	@Override
	public void setDlappimagerawId(long dlappimagerawId) {
		_dlappimagerawId = dlappimagerawId;
	}

	@Override
	public long getDlappimageprocessedId() {
		return _dlappimageprocessedId;
	}

	@Override
	public void setDlappimageprocessedId(long dlappimageprocessedId) {
		_dlappimageprocessedId = dlappimageprocessedId;
	}

	@Override
	public long getDlappimagewebId() {
		return _dlappimagewebId;
	}

	@Override
	public void setDlappimagewebId(long dlappimagewebId) {
		_dlappimagewebId = dlappimagewebId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ObjectImage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ObjectImage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ObjectImage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ObjectImageImpl objectImageImpl = new ObjectImageImpl();

		objectImageImpl.setObjectimageId(getObjectimageId());
		objectImageImpl.setPuchmuseumsobjectId(getPuchmuseumsobjectId());
		objectImageImpl.setCreaterUserId(getCreaterUserId());
		objectImageImpl.setCreateDate(getCreateDate());
		objectImageImpl.setModifiedUserId(getModifiedUserId());
		objectImageImpl.setModifiedDate(getModifiedDate());
		objectImageImpl.setDlappimagerawId(getDlappimagerawId());
		objectImageImpl.setDlappimageprocessedId(getDlappimageprocessedId());
		objectImageImpl.setDlappimagewebId(getDlappimagewebId());

		objectImageImpl.resetOriginalValues();

		return objectImageImpl;
	}

	@Override
	public int compareTo(ObjectImage objectImage) {
		long primaryKey = objectImage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ObjectImage)) {
			return false;
		}

		ObjectImage objectImage = (ObjectImage)obj;

		long primaryKey = objectImage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ObjectImageModelImpl objectImageModelImpl = this;

		objectImageModelImpl._originalPuchmuseumsobjectId = objectImageModelImpl._puchmuseumsobjectId;

		objectImageModelImpl._setOriginalPuchmuseumsobjectId = false;

		objectImageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ObjectImage> toCacheModel() {
		ObjectImageCacheModel objectImageCacheModel = new ObjectImageCacheModel();

		objectImageCacheModel.objectimageId = getObjectimageId();

		objectImageCacheModel.puchmuseumsobjectId = getPuchmuseumsobjectId();

		objectImageCacheModel.createrUserId = getCreaterUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			objectImageCacheModel.createDate = createDate.getTime();
		}
		else {
			objectImageCacheModel.createDate = Long.MIN_VALUE;
		}

		objectImageCacheModel.modifiedUserId = getModifiedUserId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			objectImageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			objectImageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		objectImageCacheModel.dlappimagerawId = getDlappimagerawId();

		objectImageCacheModel.dlappimageprocessedId = getDlappimageprocessedId();

		objectImageCacheModel.dlappimagewebId = getDlappimagewebId();

		return objectImageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{objectimageId=");
		sb.append(getObjectimageId());
		sb.append(", puchmuseumsobjectId=");
		sb.append(getPuchmuseumsobjectId());
		sb.append(", createrUserId=");
		sb.append(getCreaterUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedUserId=");
		sb.append(getModifiedUserId());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", dlappimagerawId=");
		sb.append(getDlappimagerawId());
		sb.append(", dlappimageprocessedId=");
		sb.append(getDlappimageprocessedId());
		sb.append(", dlappimagewebId=");
		sb.append(getDlappimagewebId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("at.graz.hmmc.liferay.portlet.puch.model.ObjectImage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>objectimageId</column-name><column-value><![CDATA[");
		sb.append(getObjectimageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>puchmuseumsobjectId</column-name><column-value><![CDATA[");
		sb.append(getPuchmuseumsobjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createrUserId</column-name><column-value><![CDATA[");
		sb.append(getCreaterUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedUserId</column-name><column-value><![CDATA[");
		sb.append(getModifiedUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dlappimagerawId</column-name><column-value><![CDATA[");
		sb.append(getDlappimagerawId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dlappimageprocessedId</column-name><column-value><![CDATA[");
		sb.append(getDlappimageprocessedId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dlappimagewebId</column-name><column-value><![CDATA[");
		sb.append(getDlappimagewebId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ObjectImage.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ObjectImage.class
		};
	private long _objectimageId;
	private long _puchmuseumsobjectId;
	private long _originalPuchmuseumsobjectId;
	private boolean _setOriginalPuchmuseumsobjectId;
	private long _createrUserId;
	private String _createrUserUuid;
	private Date _createDate;
	private long _modifiedUserId;
	private String _modifiedUserUuid;
	private Date _modifiedDate;
	private long _dlappimagerawId;
	private long _dlappimageprocessedId;
	private long _dlappimagewebId;
	private long _columnBitmask;
	private ObjectImage _escapedModel;
}