/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.bbmriat.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the History service. Represents a row in the &quot;history&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.liferay.portlet.bbmriat.model.impl.HistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.liferay.portlet.bbmriat.model.impl.HistoryImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see History
 * @see at.meduni.liferay.portlet.bbmriat.model.impl.HistoryImpl
 * @see at.meduni.liferay.portlet.bbmriat.model.impl.HistoryModelImpl
 * @generated
 */
public interface HistoryModel extends BaseModel<History> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a history model instance should use the {@link History} interface instead.
	 */

	/**
	 * Returns the primary key of this history.
	 *
	 * @return the primary key of this history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this history.
	 *
	 * @param primaryKey the primary key of this history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the history ID of this history.
	 *
	 * @return the history ID of this history
	 */
	public long getHistoryId();

	/**
	 * Sets the history ID of this history.
	 *
	 * @param historyId the history ID of this history
	 */
	public void setHistoryId(long historyId);

	/**
	 * Returns the action of this history.
	 *
	 * @return the action of this history
	 */
	public long getAction();

	/**
	 * Sets the action of this history.
	 *
	 * @param action the action of this history
	 */
	public void setAction(long action);

	/**
	 * Returns the time of this history.
	 *
	 * @return the time of this history
	 */
	public Date getTime();

	/**
	 * Sets the time of this history.
	 *
	 * @param time the time of this history
	 */
	public void setTime(Date time);

	/**
	 * Returns the histo_id of this history.
	 *
	 * @return the histo_id of this history
	 */
	public long getHisto_id();

	/**
	 * Sets the histo_id of this history.
	 *
	 * @param histo_id the histo_id of this history
	 */
	public void setHisto_id(long histo_id);

	/**
	 * Returns the workplace_id of this history.
	 *
	 * @return the workplace_id of this history
	 */
	public long getWorkplace_id();

	/**
	 * Sets the workplace_id of this history.
	 *
	 * @param workplace_id the workplace_id of this history
	 */
	public void setWorkplace_id(long workplace_id);

	/**
	 * Returns the order_id of this history.
	 *
	 * @return the order_id of this history
	 */
	public long getOrder_id();

	/**
	 * Sets the order_id of this history.
	 *
	 * @param order_id the order_id of this history
	 */
	public void setOrder_id(long order_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(History history);

	@Override
	public int hashCode();

	@Override
	public CacheModel<History> toCacheModel();

	@Override
	public History toEscapedModel();

	@Override
	public History toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}