/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.api.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the rdconnect service. Represents a row in the &quot;rdconnect.idcardapilog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.api.model.impl.rdconnectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.api.model.impl.rdconnectImpl}.
 * </p>
 *
 * @author reihsr
 * @see rdconnect
 * @see at.graz.meduni.liferay.api.model.impl.rdconnectImpl
 * @see at.graz.meduni.liferay.api.model.impl.rdconnectModelImpl
 * @generated
 */
public interface rdconnectModel extends BaseModel<rdconnect> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rdconnect model instance should use the {@link rdconnect} interface instead.
	 */

	/**
	 * Returns the primary key of this rdconnect.
	 *
	 * @return the primary key of this rdconnect
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rdconnect.
	 *
	 * @param primaryKey the primary key of this rdconnect
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the idcardapilog ID of this rdconnect.
	 *
	 * @return the idcardapilog ID of this rdconnect
	 */
	public long getIdcardapilogId();

	/**
	 * Sets the idcardapilog ID of this rdconnect.
	 *
	 * @param idcardapilogId the idcardapilog ID of this rdconnect
	 */
	public void setIdcardapilogId(long idcardapilogId);

	/**
	 * Returns the user ID of this rdconnect.
	 *
	 * @return the user ID of this rdconnect
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this rdconnect.
	 *
	 * @param userId the user ID of this rdconnect
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rdconnect.
	 *
	 * @return the user uuid of this rdconnect
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this rdconnect.
	 *
	 * @param userUuid the user uuid of this rdconnect
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the ipaddress of this rdconnect.
	 *
	 * @return the ipaddress of this rdconnect
	 */
	@AutoEscape
	public String getIpaddress();

	/**
	 * Sets the ipaddress of this rdconnect.
	 *
	 * @param ipaddress the ipaddress of this rdconnect
	 */
	public void setIpaddress(String ipaddress);

	/**
	 * Returns the access date of this rdconnect.
	 *
	 * @return the access date of this rdconnect
	 */
	public Date getAccessDate();

	/**
	 * Sets the access date of this rdconnect.
	 *
	 * @param accessDate the access date of this rdconnect
	 */
	public void setAccessDate(Date accessDate);

	/**
	 * Returns the requestparameter of this rdconnect.
	 *
	 * @return the requestparameter of this rdconnect
	 */
	@AutoEscape
	public String getRequestparameter();

	/**
	 * Sets the requestparameter of this rdconnect.
	 *
	 * @param requestparameter the requestparameter of this rdconnect
	 */
	public void setRequestparameter(String requestparameter);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(rdconnect rdconnect);

	@Override
	public int hashCode();

	@Override
	public CacheModel<rdconnect> toCacheModel();

	@Override
	public rdconnect toEscapedModel();

	@Override
	public rdconnect toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}