/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.rdconnect.model.impl;

import at.meduni.liferay.portlet.rdconnect.model.MasterCandidateLinkCandidate;
import at.meduni.liferay.portlet.rdconnect.service.MasterCandidateLinkCandidateLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MasterCandidateLinkCandidate service. Represents a row in the &quot;rdconnect.master_candidate_link_candidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterCandidateLinkCandidateImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see MasterCandidateLinkCandidateImpl
 * @see at.meduni.liferay.portlet.rdconnect.model.MasterCandidateLinkCandidate
 * @generated
 */
public abstract class MasterCandidateLinkCandidateBaseImpl
	extends MasterCandidateLinkCandidateModelImpl
	implements MasterCandidateLinkCandidate {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master candidate link candidate model instance should use the {@link MasterCandidateLinkCandidate} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			MasterCandidateLinkCandidateLocalServiceUtil.addMasterCandidateLinkCandidate(this);
		}
		else {
			MasterCandidateLinkCandidateLocalServiceUtil.updateMasterCandidateLinkCandidate(this);
		}
	}
}