/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Networks service. Represents a row in the &quot;rdconnect.networks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.service.model.impl.NetworksModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.service.model.impl.NetworksImpl}.
 * </p>
 *
 * @author reihsr
 * @see Networks
 * @see at.graz.meduni.liferay.portlet.bibbox.service.model.impl.NetworksImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.service.model.impl.NetworksModelImpl
 * @generated
 */
public interface NetworksModel extends BaseModel<Networks> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a networks model instance should use the {@link Networks} interface instead.
	 */

	/**
	 * Returns the primary key of this networks.
	 *
	 * @return the primary key of this networks
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this networks.
	 *
	 * @param primaryKey the primary key of this networks
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the network ID of this networks.
	 *
	 * @return the network ID of this networks
	 */
	public long getNetworkId();

	/**
	 * Sets the network ID of this networks.
	 *
	 * @param networkId the network ID of this networks
	 */
	public void setNetworkId(long networkId);

	/**
	 * Returns the organizationnetwork ID of this networks.
	 *
	 * @return the organizationnetwork ID of this networks
	 */
	public long getOrganizationnetworkId();

	/**
	 * Sets the organizationnetwork ID of this networks.
	 *
	 * @param organizationnetworkId the organizationnetwork ID of this networks
	 */
	public void setOrganizationnetworkId(long organizationnetworkId);

	/**
	 * Returns the organization ID of this networks.
	 *
	 * @return the organization ID of this networks
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this networks.
	 *
	 * @param organizationId the organization ID of this networks
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the relation of this networks.
	 *
	 * @return the relation of this networks
	 */
	@AutoEscape
	public String getRelation();

	/**
	 * Sets the relation of this networks.
	 *
	 * @param relation the relation of this networks
	 */
	public void setRelation(String relation);

	/**
	 * Returns the externalnetwork ID of this networks.
	 *
	 * @return the externalnetwork ID of this networks
	 */
	@AutoEscape
	public String getExternalnetworkId();

	/**
	 * Sets the externalnetwork ID of this networks.
	 *
	 * @param externalnetworkId the externalnetwork ID of this networks
	 */
	public void setExternalnetworkId(String externalnetworkId);

	/**
	 * Returns the yearofestablishment of this networks.
	 *
	 * @return the yearofestablishment of this networks
	 */
	@AutoEscape
	public String getYearofestablishment();

	/**
	 * Sets the yearofestablishment of this networks.
	 *
	 * @param yearofestablishment the yearofestablishment of this networks
	 */
	public void setYearofestablishment(String yearofestablishment);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Networks networks);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Networks> toCacheModel();

	@Override
	public Networks toEscapedModel();

	@Override
	public Networks toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}