create table bbmrieric.biobank (
	biobankId LONG not null primary key,
	organisationid LONG,
	ldapbiobankID TEXT null,
	biobankcountry TEXT null,
	biobankname TEXT null,
	biobanktype TEXT null,
	biobanksize TEXT null,
	biobankdescription TEXT null,
	biobankjuristicperson TEXT null,
	UUID VARCHAR(75) null
);

create table bbmrieric.contactinformation (
	uuid_ VARCHAR(75) null,
	contactinformationId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName TEXT null,
	createDate DATE null,
	modifiedDate DATE null,
	updateuuid TEXT null,
	contactID TEXT null,
	contactEmail TEXT null,
	contactCountry TEXT null,
	contactFirstName TEXT null,
	contactLastName TEXT null,
	contactPhone TEXT null,
	contactAddress TEXT null,
	contactZIP TEXT null,
	contactCity TEXT null
);

create table bbmrieric.d2biobank (
	uuid_ VARCHAR(75) null,
	biobankId LONG not null primary key,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName TEXT null,
	statusDate DATE null,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName TEXT null,
	createDate DATE null,
	modifiedDate DATE null,
	updateuuid TEXT null,
	contactIDRef TEXT null,
	contactPriority LONG,
	bbmribiobankID TEXT null,
	biobankName TEXT null,
	biobankJurisdicalPerson TEXT null,
	biobankCountry TEXT null,
	biobankPartnerCharterSigned BOOLEAN,
	bioresourceReference TEXT null,
	biobankNetworkIDRef TEXT null,
	geoLatitude TEXT null,
	geoLongitude TEXT null,
	collaborationPartnersCommercial BOOLEAN,
	collaborationPartnersNonforprofit BOOLEAN,
	biobankITSupportAvailable BOOLEAN,
	biobankITStaffSize LONG,
	biobankISAvailable BOOLEAN,
	biobankHISAvailable BOOLEAN,
	biobankAcronym TEXT null,
	biobankDescription TEXT null,
	biobankURL VARCHAR(500) null,
	biobankHeadFirstName TEXT null,
	biobankHeadLastName TEXT null,
	biobankHeadRole VARCHAR(500) null,
	biobankClinical BOOLEAN,
	biobankPopulation BOOLEAN,
	biobankResearchStudy BOOLEAN,
	biobankNonHuman BOOLEAN,
	biobankCollection BOOLEAN,
	biobankType TEXT null
);

create table bbmrieric.d2biobanknetwork (
	uuid_ VARCHAR(75) null,
	d2biobanknetworkId LONG not null primary key,
	parentd2biobanknetworkId LONG,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName TEXT null,
	statusDate DATE null,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName TEXT null,
	createDate DATE null,
	modifiedDate DATE null,
	updateuuid TEXT null,
	contactIDRef TEXT null,
	contactPriority LONG,
	bbmriBiobankNetworkID TEXT null,
	biobankNetworkName TEXT null,
	biobankNetworkCommonCollectionFocus BOOLEAN,
	biobankNetworkCommonCharter BOOLEAN,
	biobankNetworkCommonSOPs BOOLEAN,
	biobankNetworkCommonDataAccessPolicy BOOLEAN,
	biobankNetworkCommonSampleAccessPolicy BOOLEAN,
	biobankNetworkCommonMTA BOOLEAN,
	biobankNetworkCommonRepresentation BOOLEAN,
	biobankNetworkCommonURL BOOLEAN,
	biobankNetworkIDRef TEXT null,
	geoLatitude TEXT null,
	geoLongitude TEXT null,
	biobankNetworkAcronym TEXT null,
	biobankNetworkDescription TEXT null,
	biobankNetworkURL TEXT null,
	biobankNetworkJuridicalPerson TEXT null
);

create table bbmrieric.d2biobanknetworklink (
	uuid_ VARCHAR(75) null,
	d2biobanknetworklinkId LONG not null primary key,
	d2biobanknetworkId LONG,
	d2linkId LONG,
	d2linktype TEXT null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName TEXT null,
	statusDate DATE null,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName TEXT null,
	createDate DATE null,
	modifiedDate DATE null,
	updateuuid TEXT null
);

create table bbmrieric.d2collection (
	uuid_ VARCHAR(75) null,
	d2collectionId LONG not null primary key,
	biobankId LONG,
	parentd2collectionId LONG,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName TEXT null,
	createDate DATE null,
	modifiedDate DATE null,
	updateuuid TEXT null,
	bbmricollectionID TEXT null,
	bbmriparentcollectionID TEXT null,
	bbmribiobankID TEXT null,
	collectionName TEXT null,
	materialStoredDNA BOOLEAN,
	materialStoredPlasma BOOLEAN,
	materialStoredSerum BOOLEAN,
	materialStoredUrine BOOLEAN,
	materialStoredSaliva BOOLEAN,
	materialStoredFaeces BOOLEAN,
	materialStoredRNA BOOLEAN,
	materialStoredBlood BOOLEAN,
	materialStoredTissueFrozen BOOLEAN,
	materialStoredTissueFFPE BOOLEAN,
	materialStoredImmortalizedCellLines BOOLEAN,
	materialStoredIsolatedPathogen BOOLEAN,
	materialStoredOther TEXT null,
	collectionTypeCaseControl BOOLEAN,
	collectionTypeCohort BOOLEAN,
	collectionTypeCrossSectional BOOLEAN,
	collectionTypeLongitudinal BOOLEAN,
	collectionTypeTwinStudy BOOLEAN,
	collectionTypeQualityControl BOOLEAN,
	collectionTypePopulationBased BOOLEAN,
	collectionTypeDiseaseSpecific BOOLEAN,
	collectionTypeBirthCohort BOOLEAN,
	collectionTypeOther TEXT null,
	collectionOrderOfMagnitude LONG,
	bioresourceReference TEXT null,
	contactIDRef TEXT null,
	contactPriority LONG,
	biobankNetworkIDRef TEXT null,
	geoLatitude TEXT null,
	geoLongitude TEXT null,
	collaborationPartnersCommercial BOOLEAN,
	collaborationPartnersNonforprofit BOOLEAN,
	collectionAcronym TEXT null,
	collectionDescription TEXT null,
	collectionSexMale BOOLEAN,
	collectionSexFemale BOOLEAN,
	collectionSexUnknown BOOLEAN,
	collectionSexUndiferrentiated BOOLEAN,
	collectionAgeLow LONG,
	collectionAgeHigh LONG,
	collectionAgeUnit TEXT null,
	collectionAvailableBiologicalSamples BOOLEAN,
	collectionAvailableSurveyData BOOLEAN,
	collectionAvailableImagingData BOOLEAN,
	collectionAvailableMedicalRecords BOOLEAN,
	collectionAvailableNationalRegistries BOOLEAN,
	collectionAvailableGenealogicalRecords BOOLEAN,
	collectionAvailablePhysioBiochemMeasurements BOOLEAN,
	collectionAvailableOther TEXT null,
	temperatureRoom BOOLEAN,
	temperature2to10 BOOLEAN,
	temperature18to35 BOOLEAN,
	temperature60to85 BOOLEAN,
	temperatureLN BOOLEAN,
	temperatureOther TEXT null,
	diagnosisAvailable TEXT null,
	collectionHeadFirstName TEXT null,
	collectionHeadLastName TEXT null,
	collectionHeadRole TEXT null,
	collectionSampleAccessFee BOOLEAN,
	collectionSampleAccessJointProjects BOOLEAN,
	collectionSampleAccessDescription TEXT null,
	collectionSampleAccessURI TEXT null,
	collectionDataAccessFee BOOLEAN,
	collectionDataAccessJointProjects BOOLEAN,
	collectionDataAccessDescription TEXT null,
	collectionDataAccessURI TEXT null,
	collectionSize LONG,
	collectionSizeTimestamp LONG
);

create table bbmrieric.diseasediscription (
	diseasediscriptionId LONG not null primary key,
	diseasecode TEXT null,
	diseasegroup TEXT null,
	diseasediscription TEXT null,
	root BOOLEAN
);

create table bbmrieric.searchindex (
	searchid LONG not null primary key,
	organisationid LONG,
	locationid LONG,
	location TEXT null,
	searchindexkey TEXT null,
	searchindexvalue TEXT null,
	UUID VARCHAR(75) null
);