/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.bbmrieric.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BioBank service. Represents a row in the &quot;bbmrieric.biobank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.liferay.portlet.bbmrieric.model.impl.BioBankModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.liferay.portlet.bbmrieric.model.impl.BioBankImpl}.
 * </p>
 *
 * @author reihsr
 * @see BioBank
 * @see at.meduni.liferay.portlet.bbmrieric.model.impl.BioBankImpl
 * @see at.meduni.liferay.portlet.bbmrieric.model.impl.BioBankModelImpl
 * @generated
 */
public interface BioBankModel extends BaseModel<BioBank> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bio bank model instance should use the {@link BioBank} interface instead.
	 */

	/**
	 * Returns the primary key of this bio bank.
	 *
	 * @return the primary key of this bio bank
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bio bank.
	 *
	 * @param primaryKey the primary key of this bio bank
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the biobank ID of this bio bank.
	 *
	 * @return the biobank ID of this bio bank
	 */
	public long getBiobankId();

	/**
	 * Sets the biobank ID of this bio bank.
	 *
	 * @param biobankId the biobank ID of this bio bank
	 */
	public void setBiobankId(long biobankId);

	/**
	 * Returns the organisationid of this bio bank.
	 *
	 * @return the organisationid of this bio bank
	 */
	public long getOrganisationid();

	/**
	 * Sets the organisationid of this bio bank.
	 *
	 * @param organisationid the organisationid of this bio bank
	 */
	public void setOrganisationid(long organisationid);

	/**
	 * Returns the ldapbiobank i d of this bio bank.
	 *
	 * @return the ldapbiobank i d of this bio bank
	 */
	@AutoEscape
	public String getLdapbiobankID();

	/**
	 * Sets the ldapbiobank i d of this bio bank.
	 *
	 * @param ldapbiobankID the ldapbiobank i d of this bio bank
	 */
	public void setLdapbiobankID(String ldapbiobankID);

	/**
	 * Returns the biobankcountry of this bio bank.
	 *
	 * @return the biobankcountry of this bio bank
	 */
	@AutoEscape
	public String getBiobankcountry();

	/**
	 * Sets the biobankcountry of this bio bank.
	 *
	 * @param biobankcountry the biobankcountry of this bio bank
	 */
	public void setBiobankcountry(String biobankcountry);

	/**
	 * Returns the biobankname of this bio bank.
	 *
	 * @return the biobankname of this bio bank
	 */
	@AutoEscape
	public String getBiobankname();

	/**
	 * Sets the biobankname of this bio bank.
	 *
	 * @param biobankname the biobankname of this bio bank
	 */
	public void setBiobankname(String biobankname);

	/**
	 * Returns the biobanktype of this bio bank.
	 *
	 * @return the biobanktype of this bio bank
	 */
	@AutoEscape
	public String getBiobanktype();

	/**
	 * Sets the biobanktype of this bio bank.
	 *
	 * @param biobanktype the biobanktype of this bio bank
	 */
	public void setBiobanktype(String biobanktype);

	/**
	 * Returns the biobanksize of this bio bank.
	 *
	 * @return the biobanksize of this bio bank
	 */
	@AutoEscape
	public String getBiobanksize();

	/**
	 * Sets the biobanksize of this bio bank.
	 *
	 * @param biobanksize the biobanksize of this bio bank
	 */
	public void setBiobanksize(String biobanksize);

	/**
	 * Returns the biobankdescription of this bio bank.
	 *
	 * @return the biobankdescription of this bio bank
	 */
	@AutoEscape
	public String getBiobankdescription();

	/**
	 * Sets the biobankdescription of this bio bank.
	 *
	 * @param biobankdescription the biobankdescription of this bio bank
	 */
	public void setBiobankdescription(String biobankdescription);

	/**
	 * Returns the biobankjuristicperson of this bio bank.
	 *
	 * @return the biobankjuristicperson of this bio bank
	 */
	@AutoEscape
	public String getBiobankjuristicperson();

	/**
	 * Sets the biobankjuristicperson of this bio bank.
	 *
	 * @param biobankjuristicperson the biobankjuristicperson of this bio bank
	 */
	public void setBiobankjuristicperson(String biobankjuristicperson);

	/**
	 * Returns the u u i d of this bio bank.
	 *
	 * @return the u u i d of this bio bank
	 */
	@AutoEscape
	public String getUUID();

	/**
	 * Sets the u u i d of this bio bank.
	 *
	 * @param UUID the u u i d of this bio bank
	 */
	public void setUUID(String UUID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BioBank bioBank);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BioBank> toCacheModel();

	@Override
	public BioBank toEscapedModel();

	@Override
	public BioBank toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}