/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.bbmrieric.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the D2BiobankNetwork service. Represents a row in the &quot;bbmrieric.d2biobanknetwork&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.liferay.portlet.bbmrieric.model.impl.D2BiobankNetworkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.liferay.portlet.bbmrieric.model.impl.D2BiobankNetworkImpl}.
 * </p>
 *
 * @author reihsr
 * @see D2BiobankNetwork
 * @see at.meduni.liferay.portlet.bbmrieric.model.impl.D2BiobankNetworkImpl
 * @see at.meduni.liferay.portlet.bbmrieric.model.impl.D2BiobankNetworkModelImpl
 * @generated
 */
public interface D2BiobankNetworkModel extends BaseModel<D2BiobankNetwork>,
	StagedGroupedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a d2 biobank network model instance should use the {@link D2BiobankNetwork} interface instead.
	 */

	/**
	 * Returns the primary key of this d2 biobank network.
	 *
	 * @return the primary key of this d2 biobank network
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this d2 biobank network.
	 *
	 * @param primaryKey the primary key of this d2 biobank network
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this d2 biobank network.
	 *
	 * @return the uuid of this d2 biobank network
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this d2 biobank network.
	 *
	 * @param uuid the uuid of this d2 biobank network
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the d2biobanknetwork ID of this d2 biobank network.
	 *
	 * @return the d2biobanknetwork ID of this d2 biobank network
	 */
	public long getD2biobanknetworkId();

	/**
	 * Sets the d2biobanknetwork ID of this d2 biobank network.
	 *
	 * @param d2biobanknetworkId the d2biobanknetwork ID of this d2 biobank network
	 */
	public void setD2biobanknetworkId(long d2biobanknetworkId);

	/**
	 * Returns the parentd2biobanknetwork ID of this d2 biobank network.
	 *
	 * @return the parentd2biobanknetwork ID of this d2 biobank network
	 */
	public long getParentd2biobanknetworkId();

	/**
	 * Sets the parentd2biobanknetwork ID of this d2 biobank network.
	 *
	 * @param parentd2biobanknetworkId the parentd2biobanknetwork ID of this d2 biobank network
	 */
	public void setParentd2biobanknetworkId(long parentd2biobanknetworkId);

	/**
	 * Returns the status of this d2 biobank network.
	 *
	 * @return the status of this d2 biobank network
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this d2 biobank network.
	 *
	 * @param status the status of this d2 biobank network
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this d2 biobank network.
	 *
	 * @return the status by user ID of this d2 biobank network
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this d2 biobank network.
	 *
	 * @param statusByUserId the status by user ID of this d2 biobank network
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this d2 biobank network.
	 *
	 * @return the status by user uuid of this d2 biobank network
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this d2 biobank network.
	 *
	 * @param statusByUserUuid the status by user uuid of this d2 biobank network
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this d2 biobank network.
	 *
	 * @return the status by user name of this d2 biobank network
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this d2 biobank network.
	 *
	 * @param statusByUserName the status by user name of this d2 biobank network
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this d2 biobank network.
	 *
	 * @return the status date of this d2 biobank network
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this d2 biobank network.
	 *
	 * @param statusDate the status date of this d2 biobank network
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the company ID of this d2 biobank network.
	 *
	 * @return the company ID of this d2 biobank network
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this d2 biobank network.
	 *
	 * @param companyId the company ID of this d2 biobank network
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this d2 biobank network.
	 *
	 * @return the group ID of this d2 biobank network
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this d2 biobank network.
	 *
	 * @param groupId the group ID of this d2 biobank network
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this d2 biobank network.
	 *
	 * @return the user ID of this d2 biobank network
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this d2 biobank network.
	 *
	 * @param userId the user ID of this d2 biobank network
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this d2 biobank network.
	 *
	 * @return the user uuid of this d2 biobank network
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this d2 biobank network.
	 *
	 * @param userUuid the user uuid of this d2 biobank network
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this d2 biobank network.
	 *
	 * @return the user name of this d2 biobank network
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this d2 biobank network.
	 *
	 * @param userName the user name of this d2 biobank network
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this d2 biobank network.
	 *
	 * @return the create date of this d2 biobank network
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this d2 biobank network.
	 *
	 * @param createDate the create date of this d2 biobank network
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this d2 biobank network.
	 *
	 * @return the modified date of this d2 biobank network
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this d2 biobank network.
	 *
	 * @param modifiedDate the modified date of this d2 biobank network
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the updateuuid of this d2 biobank network.
	 *
	 * @return the updateuuid of this d2 biobank network
	 */
	@AutoEscape
	public String getUpdateuuid();

	/**
	 * Sets the updateuuid of this d2 biobank network.
	 *
	 * @param updateuuid the updateuuid of this d2 biobank network
	 */
	public void setUpdateuuid(String updateuuid);

	/**
	 * Returns the contact i d ref of this d2 biobank network.
	 *
	 * @return the contact i d ref of this d2 biobank network
	 */
	@AutoEscape
	public String getContactIDRef();

	/**
	 * Sets the contact i d ref of this d2 biobank network.
	 *
	 * @param contactIDRef the contact i d ref of this d2 biobank network
	 */
	public void setContactIDRef(String contactIDRef);

	/**
	 * Returns the contact priority of this d2 biobank network.
	 *
	 * @return the contact priority of this d2 biobank network
	 */
	public long getContactPriority();

	/**
	 * Sets the contact priority of this d2 biobank network.
	 *
	 * @param contactPriority the contact priority of this d2 biobank network
	 */
	public void setContactPriority(long contactPriority);

	/**
	 * Returns the bbmri biobank network i d of this d2 biobank network.
	 *
	 * @return the bbmri biobank network i d of this d2 biobank network
	 */
	@AutoEscape
	public String getBbmriBiobankNetworkID();

	/**
	 * Sets the bbmri biobank network i d of this d2 biobank network.
	 *
	 * @param bbmriBiobankNetworkID the bbmri biobank network i d of this d2 biobank network
	 */
	public void setBbmriBiobankNetworkID(String bbmriBiobankNetworkID);

	/**
	 * Returns the biobank network name of this d2 biobank network.
	 *
	 * @return the biobank network name of this d2 biobank network
	 */
	@AutoEscape
	public String getBiobankNetworkName();

	/**
	 * Sets the biobank network name of this d2 biobank network.
	 *
	 * @param biobankNetworkName the biobank network name of this d2 biobank network
	 */
	public void setBiobankNetworkName(String biobankNetworkName);

	/**
	 * Returns the biobank network common collection focus of this d2 biobank network.
	 *
	 * @return the biobank network common collection focus of this d2 biobank network
	 */
	public boolean getBiobankNetworkCommonCollectionFocus();

	/**
	 * Returns <code>true</code> if this d2 biobank network is biobank network common collection focus.
	 *
	 * @return <code>true</code> if this d2 biobank network is biobank network common collection focus; <code>false</code> otherwise
	 */
	public boolean isBiobankNetworkCommonCollectionFocus();

	/**
	 * Sets whether this d2 biobank network is biobank network common collection focus.
	 *
	 * @param biobankNetworkCommonCollectionFocus the biobank network common collection focus of this d2 biobank network
	 */
	public void setBiobankNetworkCommonCollectionFocus(
		boolean biobankNetworkCommonCollectionFocus);

	/**
	 * Returns the biobank network common charter of this d2 biobank network.
	 *
	 * @return the biobank network common charter of this d2 biobank network
	 */
	public boolean getBiobankNetworkCommonCharter();

	/**
	 * Returns <code>true</code> if this d2 biobank network is biobank network common charter.
	 *
	 * @return <code>true</code> if this d2 biobank network is biobank network common charter; <code>false</code> otherwise
	 */
	public boolean isBiobankNetworkCommonCharter();

	/**
	 * Sets whether this d2 biobank network is biobank network common charter.
	 *
	 * @param biobankNetworkCommonCharter the biobank network common charter of this d2 biobank network
	 */
	public void setBiobankNetworkCommonCharter(
		boolean biobankNetworkCommonCharter);

	/**
	 * Returns the biobank network common s o ps of this d2 biobank network.
	 *
	 * @return the biobank network common s o ps of this d2 biobank network
	 */
	public boolean getBiobankNetworkCommonSOPs();

	/**
	 * Returns <code>true</code> if this d2 biobank network is biobank network common s o ps.
	 *
	 * @return <code>true</code> if this d2 biobank network is biobank network common s o ps; <code>false</code> otherwise
	 */
	public boolean isBiobankNetworkCommonSOPs();

	/**
	 * Sets whether this d2 biobank network is biobank network common s o ps.
	 *
	 * @param biobankNetworkCommonSOPs the biobank network common s o ps of this d2 biobank network
	 */
	public void setBiobankNetworkCommonSOPs(boolean biobankNetworkCommonSOPs);

	/**
	 * Returns the biobank network common data access policy of this d2 biobank network.
	 *
	 * @return the biobank network common data access policy of this d2 biobank network
	 */
	public boolean getBiobankNetworkCommonDataAccessPolicy();

	/**
	 * Returns <code>true</code> if this d2 biobank network is biobank network common data access policy.
	 *
	 * @return <code>true</code> if this d2 biobank network is biobank network common data access policy; <code>false</code> otherwise
	 */
	public boolean isBiobankNetworkCommonDataAccessPolicy();

	/**
	 * Sets whether this d2 biobank network is biobank network common data access policy.
	 *
	 * @param biobankNetworkCommonDataAccessPolicy the biobank network common data access policy of this d2 biobank network
	 */
	public void setBiobankNetworkCommonDataAccessPolicy(
		boolean biobankNetworkCommonDataAccessPolicy);

	/**
	 * Returns the biobank network common sample access policy of this d2 biobank network.
	 *
	 * @return the biobank network common sample access policy of this d2 biobank network
	 */
	public boolean getBiobankNetworkCommonSampleAccessPolicy();

	/**
	 * Returns <code>true</code> if this d2 biobank network is biobank network common sample access policy.
	 *
	 * @return <code>true</code> if this d2 biobank network is biobank network common sample access policy; <code>false</code> otherwise
	 */
	public boolean isBiobankNetworkCommonSampleAccessPolicy();

	/**
	 * Sets whether this d2 biobank network is biobank network common sample access policy.
	 *
	 * @param biobankNetworkCommonSampleAccessPolicy the biobank network common sample access policy of this d2 biobank network
	 */
	public void setBiobankNetworkCommonSampleAccessPolicy(
		boolean biobankNetworkCommonSampleAccessPolicy);

	/**
	 * Returns the biobank network common m t a of this d2 biobank network.
	 *
	 * @return the biobank network common m t a of this d2 biobank network
	 */
	public boolean getBiobankNetworkCommonMTA();

	/**
	 * Returns <code>true</code> if this d2 biobank network is biobank network common m t a.
	 *
	 * @return <code>true</code> if this d2 biobank network is biobank network common m t a; <code>false</code> otherwise
	 */
	public boolean isBiobankNetworkCommonMTA();

	/**
	 * Sets whether this d2 biobank network is biobank network common m t a.
	 *
	 * @param biobankNetworkCommonMTA the biobank network common m t a of this d2 biobank network
	 */
	public void setBiobankNetworkCommonMTA(boolean biobankNetworkCommonMTA);

	/**
	 * Returns the biobank network common representation of this d2 biobank network.
	 *
	 * @return the biobank network common representation of this d2 biobank network
	 */
	public boolean getBiobankNetworkCommonRepresentation();

	/**
	 * Returns <code>true</code> if this d2 biobank network is biobank network common representation.
	 *
	 * @return <code>true</code> if this d2 biobank network is biobank network common representation; <code>false</code> otherwise
	 */
	public boolean isBiobankNetworkCommonRepresentation();

	/**
	 * Sets whether this d2 biobank network is biobank network common representation.
	 *
	 * @param biobankNetworkCommonRepresentation the biobank network common representation of this d2 biobank network
	 */
	public void setBiobankNetworkCommonRepresentation(
		boolean biobankNetworkCommonRepresentation);

	/**
	 * Returns the biobank network common u r l of this d2 biobank network.
	 *
	 * @return the biobank network common u r l of this d2 biobank network
	 */
	public boolean getBiobankNetworkCommonURL();

	/**
	 * Returns <code>true</code> if this d2 biobank network is biobank network common u r l.
	 *
	 * @return <code>true</code> if this d2 biobank network is biobank network common u r l; <code>false</code> otherwise
	 */
	public boolean isBiobankNetworkCommonURL();

	/**
	 * Sets whether this d2 biobank network is biobank network common u r l.
	 *
	 * @param biobankNetworkCommonURL the biobank network common u r l of this d2 biobank network
	 */
	public void setBiobankNetworkCommonURL(boolean biobankNetworkCommonURL);

	/**
	 * Returns the biobank network i d ref of this d2 biobank network.
	 *
	 * @return the biobank network i d ref of this d2 biobank network
	 */
	@AutoEscape
	public String getBiobankNetworkIDRef();

	/**
	 * Sets the biobank network i d ref of this d2 biobank network.
	 *
	 * @param biobankNetworkIDRef the biobank network i d ref of this d2 biobank network
	 */
	public void setBiobankNetworkIDRef(String biobankNetworkIDRef);

	/**
	 * Returns the geo latitude of this d2 biobank network.
	 *
	 * @return the geo latitude of this d2 biobank network
	 */
	@AutoEscape
	public String getGeoLatitude();

	/**
	 * Sets the geo latitude of this d2 biobank network.
	 *
	 * @param geoLatitude the geo latitude of this d2 biobank network
	 */
	public void setGeoLatitude(String geoLatitude);

	/**
	 * Returns the geo longitude of this d2 biobank network.
	 *
	 * @return the geo longitude of this d2 biobank network
	 */
	@AutoEscape
	public String getGeoLongitude();

	/**
	 * Sets the geo longitude of this d2 biobank network.
	 *
	 * @param geoLongitude the geo longitude of this d2 biobank network
	 */
	public void setGeoLongitude(String geoLongitude);

	/**
	 * Returns the biobank network acronym of this d2 biobank network.
	 *
	 * @return the biobank network acronym of this d2 biobank network
	 */
	@AutoEscape
	public String getBiobankNetworkAcronym();

	/**
	 * Sets the biobank network acronym of this d2 biobank network.
	 *
	 * @param biobankNetworkAcronym the biobank network acronym of this d2 biobank network
	 */
	public void setBiobankNetworkAcronym(String biobankNetworkAcronym);

	/**
	 * Returns the biobank network description of this d2 biobank network.
	 *
	 * @return the biobank network description of this d2 biobank network
	 */
	@AutoEscape
	public String getBiobankNetworkDescription();

	/**
	 * Sets the biobank network description of this d2 biobank network.
	 *
	 * @param biobankNetworkDescription the biobank network description of this d2 biobank network
	 */
	public void setBiobankNetworkDescription(String biobankNetworkDescription);

	/**
	 * Returns the biobank network u r l of this d2 biobank network.
	 *
	 * @return the biobank network u r l of this d2 biobank network
	 */
	@AutoEscape
	public String getBiobankNetworkURL();

	/**
	 * Sets the biobank network u r l of this d2 biobank network.
	 *
	 * @param biobankNetworkURL the biobank network u r l of this d2 biobank network
	 */
	public void setBiobankNetworkURL(String biobankNetworkURL);

	/**
	 * Returns the biobank network juridical person of this d2 biobank network.
	 *
	 * @return the biobank network juridical person of this d2 biobank network
	 */
	@AutoEscape
	public String getBiobankNetworkJuridicalPerson();

	/**
	 * Sets the biobank network juridical person of this d2 biobank network.
	 *
	 * @param biobankNetworkJuridicalPerson the biobank network juridical person of this d2 biobank network
	 */
	public void setBiobankNetworkJuridicalPerson(
		String biobankNetworkJuridicalPerson);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this d2 biobank network is approved.
	 *
	 * @return <code>true</code> if this d2 biobank network is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this d2 biobank network is denied.
	 *
	 * @return <code>true</code> if this d2 biobank network is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this d2 biobank network is a draft.
	 *
	 * @return <code>true</code> if this d2 biobank network is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this d2 biobank network is expired.
	 *
	 * @return <code>true</code> if this d2 biobank network is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this d2 biobank network is inactive.
	 *
	 * @return <code>true</code> if this d2 biobank network is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this d2 biobank network is incomplete.
	 *
	 * @return <code>true</code> if this d2 biobank network is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this d2 biobank network is pending.
	 *
	 * @return <code>true</code> if this d2 biobank network is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this d2 biobank network is scheduled.
	 *
	 * @return <code>true</code> if this d2 biobank network is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(D2BiobankNetwork d2BiobankNetwork);

	@Override
	public int hashCode();

	@Override
	public CacheModel<D2BiobankNetwork> toCacheModel();

	@Override
	public D2BiobankNetwork toEscapedModel();

	@Override
	public D2BiobankNetwork toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}