/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.bbmrieric.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the D2BiobankNetworkLink service. Represents a row in the &quot;bbmrieric.d2biobanknetworklink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.liferay.portlet.bbmrieric.model.impl.D2BiobankNetworkLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.liferay.portlet.bbmrieric.model.impl.D2BiobankNetworkLinkImpl}.
 * </p>
 *
 * @author reihsr
 * @see D2BiobankNetworkLink
 * @see at.meduni.liferay.portlet.bbmrieric.model.impl.D2BiobankNetworkLinkImpl
 * @see at.meduni.liferay.portlet.bbmrieric.model.impl.D2BiobankNetworkLinkModelImpl
 * @generated
 */
public interface D2BiobankNetworkLinkModel extends BaseModel<D2BiobankNetworkLink>,
	StagedGroupedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a d2 biobank network link model instance should use the {@link D2BiobankNetworkLink} interface instead.
	 */

	/**
	 * Returns the primary key of this d2 biobank network link.
	 *
	 * @return the primary key of this d2 biobank network link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this d2 biobank network link.
	 *
	 * @param primaryKey the primary key of this d2 biobank network link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this d2 biobank network link.
	 *
	 * @return the uuid of this d2 biobank network link
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this d2 biobank network link.
	 *
	 * @param uuid the uuid of this d2 biobank network link
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the d2biobanknetworklink ID of this d2 biobank network link.
	 *
	 * @return the d2biobanknetworklink ID of this d2 biobank network link
	 */
	public long getD2biobanknetworklinkId();

	/**
	 * Sets the d2biobanknetworklink ID of this d2 biobank network link.
	 *
	 * @param d2biobanknetworklinkId the d2biobanknetworklink ID of this d2 biobank network link
	 */
	public void setD2biobanknetworklinkId(long d2biobanknetworklinkId);

	/**
	 * Returns the d2biobanknetwork ID of this d2 biobank network link.
	 *
	 * @return the d2biobanknetwork ID of this d2 biobank network link
	 */
	public long getD2biobanknetworkId();

	/**
	 * Sets the d2biobanknetwork ID of this d2 biobank network link.
	 *
	 * @param d2biobanknetworkId the d2biobanknetwork ID of this d2 biobank network link
	 */
	public void setD2biobanknetworkId(long d2biobanknetworkId);

	/**
	 * Returns the d2link ID of this d2 biobank network link.
	 *
	 * @return the d2link ID of this d2 biobank network link
	 */
	public long getD2linkId();

	/**
	 * Sets the d2link ID of this d2 biobank network link.
	 *
	 * @param d2linkId the d2link ID of this d2 biobank network link
	 */
	public void setD2linkId(long d2linkId);

	/**
	 * Returns the d2linktype of this d2 biobank network link.
	 *
	 * @return the d2linktype of this d2 biobank network link
	 */
	@AutoEscape
	public String getD2linktype();

	/**
	 * Sets the d2linktype of this d2 biobank network link.
	 *
	 * @param d2linktype the d2linktype of this d2 biobank network link
	 */
	public void setD2linktype(String d2linktype);

	/**
	 * Returns the status of this d2 biobank network link.
	 *
	 * @return the status of this d2 biobank network link
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this d2 biobank network link.
	 *
	 * @param status the status of this d2 biobank network link
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this d2 biobank network link.
	 *
	 * @return the status by user ID of this d2 biobank network link
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this d2 biobank network link.
	 *
	 * @param statusByUserId the status by user ID of this d2 biobank network link
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this d2 biobank network link.
	 *
	 * @return the status by user uuid of this d2 biobank network link
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this d2 biobank network link.
	 *
	 * @param statusByUserUuid the status by user uuid of this d2 biobank network link
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this d2 biobank network link.
	 *
	 * @return the status by user name of this d2 biobank network link
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this d2 biobank network link.
	 *
	 * @param statusByUserName the status by user name of this d2 biobank network link
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this d2 biobank network link.
	 *
	 * @return the status date of this d2 biobank network link
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this d2 biobank network link.
	 *
	 * @param statusDate the status date of this d2 biobank network link
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the company ID of this d2 biobank network link.
	 *
	 * @return the company ID of this d2 biobank network link
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this d2 biobank network link.
	 *
	 * @param companyId the company ID of this d2 biobank network link
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this d2 biobank network link.
	 *
	 * @return the group ID of this d2 biobank network link
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this d2 biobank network link.
	 *
	 * @param groupId the group ID of this d2 biobank network link
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this d2 biobank network link.
	 *
	 * @return the user ID of this d2 biobank network link
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this d2 biobank network link.
	 *
	 * @param userId the user ID of this d2 biobank network link
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this d2 biobank network link.
	 *
	 * @return the user uuid of this d2 biobank network link
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this d2 biobank network link.
	 *
	 * @param userUuid the user uuid of this d2 biobank network link
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this d2 biobank network link.
	 *
	 * @return the user name of this d2 biobank network link
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this d2 biobank network link.
	 *
	 * @param userName the user name of this d2 biobank network link
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this d2 biobank network link.
	 *
	 * @return the create date of this d2 biobank network link
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this d2 biobank network link.
	 *
	 * @param createDate the create date of this d2 biobank network link
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this d2 biobank network link.
	 *
	 * @return the modified date of this d2 biobank network link
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this d2 biobank network link.
	 *
	 * @param modifiedDate the modified date of this d2 biobank network link
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the updateuuid of this d2 biobank network link.
	 *
	 * @return the updateuuid of this d2 biobank network link
	 */
	@AutoEscape
	public String getUpdateuuid();

	/**
	 * Sets the updateuuid of this d2 biobank network link.
	 *
	 * @param updateuuid the updateuuid of this d2 biobank network link
	 */
	public void setUpdateuuid(String updateuuid);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this d2 biobank network link is approved.
	 *
	 * @return <code>true</code> if this d2 biobank network link is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this d2 biobank network link is denied.
	 *
	 * @return <code>true</code> if this d2 biobank network link is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this d2 biobank network link is a draft.
	 *
	 * @return <code>true</code> if this d2 biobank network link is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this d2 biobank network link is expired.
	 *
	 * @return <code>true</code> if this d2 biobank network link is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this d2 biobank network link is inactive.
	 *
	 * @return <code>true</code> if this d2 biobank network link is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this d2 biobank network link is incomplete.
	 *
	 * @return <code>true</code> if this d2 biobank network link is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this d2 biobank network link is pending.
	 *
	 * @return <code>true</code> if this d2 biobank network link is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this d2 biobank network link is scheduled.
	 *
	 * @return <code>true</code> if this d2 biobank network link is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(D2BiobankNetworkLink d2BiobankNetworkLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<D2BiobankNetworkLink> toCacheModel();

	@Override
	public D2BiobankNetworkLink toEscapedModel();

	@Override
	public D2BiobankNetworkLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}