/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.bbmrieric.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SearchIndex service. Represents a row in the &quot;bbmrieric.searchindex&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.liferay.portlet.bbmrieric.model.impl.SearchIndexModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.liferay.portlet.bbmrieric.model.impl.SearchIndexImpl}.
 * </p>
 *
 * @author reihsr
 * @see SearchIndex
 * @see at.meduni.liferay.portlet.bbmrieric.model.impl.SearchIndexImpl
 * @see at.meduni.liferay.portlet.bbmrieric.model.impl.SearchIndexModelImpl
 * @generated
 */
public interface SearchIndexModel extends BaseModel<SearchIndex> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a search index model instance should use the {@link SearchIndex} interface instead.
	 */

	/**
	 * Returns the primary key of this search index.
	 *
	 * @return the primary key of this search index
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this search index.
	 *
	 * @param primaryKey the primary key of this search index
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the searchid of this search index.
	 *
	 * @return the searchid of this search index
	 */
	public long getSearchid();

	/**
	 * Sets the searchid of this search index.
	 *
	 * @param searchid the searchid of this search index
	 */
	public void setSearchid(long searchid);

	/**
	 * Returns the organisationid of this search index.
	 *
	 * @return the organisationid of this search index
	 */
	public long getOrganisationid();

	/**
	 * Sets the organisationid of this search index.
	 *
	 * @param organisationid the organisationid of this search index
	 */
	public void setOrganisationid(long organisationid);

	/**
	 * Returns the locationid of this search index.
	 *
	 * @return the locationid of this search index
	 */
	public long getLocationid();

	/**
	 * Sets the locationid of this search index.
	 *
	 * @param locationid the locationid of this search index
	 */
	public void setLocationid(long locationid);

	/**
	 * Returns the location of this search index.
	 *
	 * @return the location of this search index
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this search index.
	 *
	 * @param location the location of this search index
	 */
	public void setLocation(String location);

	/**
	 * Returns the searchindexkey of this search index.
	 *
	 * @return the searchindexkey of this search index
	 */
	@AutoEscape
	public String getSearchindexkey();

	/**
	 * Sets the searchindexkey of this search index.
	 *
	 * @param searchindexkey the searchindexkey of this search index
	 */
	public void setSearchindexkey(String searchindexkey);

	/**
	 * Returns the searchindexvalue of this search index.
	 *
	 * @return the searchindexvalue of this search index
	 */
	@AutoEscape
	public String getSearchindexvalue();

	/**
	 * Sets the searchindexvalue of this search index.
	 *
	 * @param searchindexvalue the searchindexvalue of this search index
	 */
	public void setSearchindexvalue(String searchindexvalue);

	/**
	 * Returns the u u i d of this search index.
	 *
	 * @return the u u i d of this search index
	 */
	@AutoEscape
	public String getUUID();

	/**
	 * Sets the u u i d of this search index.
	 *
	 * @param UUID the u u i d of this search index
	 */
	public void setUUID(String UUID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SearchIndex searchIndex);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SearchIndex> toCacheModel();

	@Override
	public SearchIndex toEscapedModel();

	@Override
	public SearchIndex toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}