/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.saat.service.base;

import at.graz.meduni.liferay.portlet.saat.model.Dictionary;
import at.graz.meduni.liferay.portlet.saat.service.DictionaryService;
import at.graz.meduni.liferay.portlet.saat.service.persistence.DictionaryDictionaryLinkPersistence;
import at.graz.meduni.liferay.portlet.saat.service.persistence.DictionaryPersistence;
import at.graz.meduni.liferay.portlet.saat.service.persistence.ICD10Persistence;
import at.graz.meduni.liferay.portlet.saat.service.persistence.ICDO3Persistence;
import at.graz.meduni.liferay.portlet.saat.service.persistence.SCGPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dictionary remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link at.graz.meduni.liferay.portlet.saat.service.impl.DictionaryServiceImpl}.
 * </p>
 *
 * @author reihsr
 * @see at.graz.meduni.liferay.portlet.saat.service.impl.DictionaryServiceImpl
 * @see at.graz.meduni.liferay.portlet.saat.service.DictionaryServiceUtil
 * @generated
 */
public abstract class DictionaryServiceBaseImpl extends BaseServiceImpl
	implements DictionaryService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link at.graz.meduni.liferay.portlet.saat.service.DictionaryServiceUtil} to access the dictionary remote service.
	 */

	/**
	 * Returns the dictionary local service.
	 *
	 * @return the dictionary local service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.DictionaryLocalService getDictionaryLocalService() {
		return dictionaryLocalService;
	}

	/**
	 * Sets the dictionary local service.
	 *
	 * @param dictionaryLocalService the dictionary local service
	 */
	public void setDictionaryLocalService(
		at.graz.meduni.liferay.portlet.saat.service.DictionaryLocalService dictionaryLocalService) {
		this.dictionaryLocalService = dictionaryLocalService;
	}

	/**
	 * Returns the dictionary remote service.
	 *
	 * @return the dictionary remote service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.DictionaryService getDictionaryService() {
		return dictionaryService;
	}

	/**
	 * Sets the dictionary remote service.
	 *
	 * @param dictionaryService the dictionary remote service
	 */
	public void setDictionaryService(
		at.graz.meduni.liferay.portlet.saat.service.DictionaryService dictionaryService) {
		this.dictionaryService = dictionaryService;
	}

	/**
	 * Returns the dictionary persistence.
	 *
	 * @return the dictionary persistence
	 */
	public DictionaryPersistence getDictionaryPersistence() {
		return dictionaryPersistence;
	}

	/**
	 * Sets the dictionary persistence.
	 *
	 * @param dictionaryPersistence the dictionary persistence
	 */
	public void setDictionaryPersistence(
		DictionaryPersistence dictionaryPersistence) {
		this.dictionaryPersistence = dictionaryPersistence;
	}

	/**
	 * Returns the dictionary dictionary link local service.
	 *
	 * @return the dictionary dictionary link local service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.DictionaryDictionaryLinkLocalService getDictionaryDictionaryLinkLocalService() {
		return dictionaryDictionaryLinkLocalService;
	}

	/**
	 * Sets the dictionary dictionary link local service.
	 *
	 * @param dictionaryDictionaryLinkLocalService the dictionary dictionary link local service
	 */
	public void setDictionaryDictionaryLinkLocalService(
		at.graz.meduni.liferay.portlet.saat.service.DictionaryDictionaryLinkLocalService dictionaryDictionaryLinkLocalService) {
		this.dictionaryDictionaryLinkLocalService = dictionaryDictionaryLinkLocalService;
	}

	/**
	 * Returns the dictionary dictionary link remote service.
	 *
	 * @return the dictionary dictionary link remote service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.DictionaryDictionaryLinkService getDictionaryDictionaryLinkService() {
		return dictionaryDictionaryLinkService;
	}

	/**
	 * Sets the dictionary dictionary link remote service.
	 *
	 * @param dictionaryDictionaryLinkService the dictionary dictionary link remote service
	 */
	public void setDictionaryDictionaryLinkService(
		at.graz.meduni.liferay.portlet.saat.service.DictionaryDictionaryLinkService dictionaryDictionaryLinkService) {
		this.dictionaryDictionaryLinkService = dictionaryDictionaryLinkService;
	}

	/**
	 * Returns the dictionary dictionary link persistence.
	 *
	 * @return the dictionary dictionary link persistence
	 */
	public DictionaryDictionaryLinkPersistence getDictionaryDictionaryLinkPersistence() {
		return dictionaryDictionaryLinkPersistence;
	}

	/**
	 * Sets the dictionary dictionary link persistence.
	 *
	 * @param dictionaryDictionaryLinkPersistence the dictionary dictionary link persistence
	 */
	public void setDictionaryDictionaryLinkPersistence(
		DictionaryDictionaryLinkPersistence dictionaryDictionaryLinkPersistence) {
		this.dictionaryDictionaryLinkPersistence = dictionaryDictionaryLinkPersistence;
	}

	/**
	 * Returns the i c d10 local service.
	 *
	 * @return the i c d10 local service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.ICD10LocalService getICD10LocalService() {
		return icd10LocalService;
	}

	/**
	 * Sets the i c d10 local service.
	 *
	 * @param icd10LocalService the i c d10 local service
	 */
	public void setICD10LocalService(
		at.graz.meduni.liferay.portlet.saat.service.ICD10LocalService icd10LocalService) {
		this.icd10LocalService = icd10LocalService;
	}

	/**
	 * Returns the i c d10 remote service.
	 *
	 * @return the i c d10 remote service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.ICD10Service getICD10Service() {
		return icd10Service;
	}

	/**
	 * Sets the i c d10 remote service.
	 *
	 * @param icd10Service the i c d10 remote service
	 */
	public void setICD10Service(
		at.graz.meduni.liferay.portlet.saat.service.ICD10Service icd10Service) {
		this.icd10Service = icd10Service;
	}

	/**
	 * Returns the i c d10 persistence.
	 *
	 * @return the i c d10 persistence
	 */
	public ICD10Persistence getICD10Persistence() {
		return icd10Persistence;
	}

	/**
	 * Sets the i c d10 persistence.
	 *
	 * @param icd10Persistence the i c d10 persistence
	 */
	public void setICD10Persistence(ICD10Persistence icd10Persistence) {
		this.icd10Persistence = icd10Persistence;
	}

	/**
	 * Returns the i c d o3 local service.
	 *
	 * @return the i c d o3 local service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.ICDO3LocalService getICDO3LocalService() {
		return icdo3LocalService;
	}

	/**
	 * Sets the i c d o3 local service.
	 *
	 * @param icdo3LocalService the i c d o3 local service
	 */
	public void setICDO3LocalService(
		at.graz.meduni.liferay.portlet.saat.service.ICDO3LocalService icdo3LocalService) {
		this.icdo3LocalService = icdo3LocalService;
	}

	/**
	 * Returns the i c d o3 remote service.
	 *
	 * @return the i c d o3 remote service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.ICDO3Service getICDO3Service() {
		return icdo3Service;
	}

	/**
	 * Sets the i c d o3 remote service.
	 *
	 * @param icdo3Service the i c d o3 remote service
	 */
	public void setICDO3Service(
		at.graz.meduni.liferay.portlet.saat.service.ICDO3Service icdo3Service) {
		this.icdo3Service = icdo3Service;
	}

	/**
	 * Returns the i c d o3 persistence.
	 *
	 * @return the i c d o3 persistence
	 */
	public ICDO3Persistence getICDO3Persistence() {
		return icdo3Persistence;
	}

	/**
	 * Sets the i c d o3 persistence.
	 *
	 * @param icdo3Persistence the i c d o3 persistence
	 */
	public void setICDO3Persistence(ICDO3Persistence icdo3Persistence) {
		this.icdo3Persistence = icdo3Persistence;
	}

	/**
	 * Returns the s c g local service.
	 *
	 * @return the s c g local service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.SCGLocalService getSCGLocalService() {
		return scgLocalService;
	}

	/**
	 * Sets the s c g local service.
	 *
	 * @param scgLocalService the s c g local service
	 */
	public void setSCGLocalService(
		at.graz.meduni.liferay.portlet.saat.service.SCGLocalService scgLocalService) {
		this.scgLocalService = scgLocalService;
	}

	/**
	 * Returns the s c g remote service.
	 *
	 * @return the s c g remote service
	 */
	public at.graz.meduni.liferay.portlet.saat.service.SCGService getSCGService() {
		return scgService;
	}

	/**
	 * Sets the s c g remote service.
	 *
	 * @param scgService the s c g remote service
	 */
	public void setSCGService(
		at.graz.meduni.liferay.portlet.saat.service.SCGService scgService) {
		this.scgService = scgService;
	}

	/**
	 * Returns the s c g persistence.
	 *
	 * @return the s c g persistence
	 */
	public SCGPersistence getSCGPersistence() {
		return scgPersistence;
	}

	/**
	 * Sets the s c g persistence.
	 *
	 * @param scgPersistence the s c g persistence
	 */
	public void setSCGPersistence(SCGPersistence scgPersistence) {
		this.scgPersistence = scgPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Dictionary.class;
	}

	protected String getModelClassName() {
		return Dictionary.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = dictionaryPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.DictionaryLocalService.class)
	protected at.graz.meduni.liferay.portlet.saat.service.DictionaryLocalService dictionaryLocalService;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.DictionaryService.class)
	protected at.graz.meduni.liferay.portlet.saat.service.DictionaryService dictionaryService;
	@BeanReference(type = DictionaryPersistence.class)
	protected DictionaryPersistence dictionaryPersistence;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.DictionaryDictionaryLinkLocalService.class)
	protected at.graz.meduni.liferay.portlet.saat.service.DictionaryDictionaryLinkLocalService dictionaryDictionaryLinkLocalService;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.DictionaryDictionaryLinkService.class)
	protected at.graz.meduni.liferay.portlet.saat.service.DictionaryDictionaryLinkService dictionaryDictionaryLinkService;
	@BeanReference(type = DictionaryDictionaryLinkPersistence.class)
	protected DictionaryDictionaryLinkPersistence dictionaryDictionaryLinkPersistence;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.ICD10LocalService.class)
	protected at.graz.meduni.liferay.portlet.saat.service.ICD10LocalService icd10LocalService;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.ICD10Service.class)
	protected at.graz.meduni.liferay.portlet.saat.service.ICD10Service icd10Service;
	@BeanReference(type = ICD10Persistence.class)
	protected ICD10Persistence icd10Persistence;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.ICDO3LocalService.class)
	protected at.graz.meduni.liferay.portlet.saat.service.ICDO3LocalService icdo3LocalService;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.ICDO3Service.class)
	protected at.graz.meduni.liferay.portlet.saat.service.ICDO3Service icdo3Service;
	@BeanReference(type = ICDO3Persistence.class)
	protected ICDO3Persistence icdo3Persistence;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.SCGLocalService.class)
	protected at.graz.meduni.liferay.portlet.saat.service.SCGLocalService scgLocalService;
	@BeanReference(type = at.graz.meduni.liferay.portlet.saat.service.SCGService.class)
	protected at.graz.meduni.liferay.portlet.saat.service.SCGService scgService;
	@BeanReference(type = SCGPersistence.class)
	protected SCGPersistence scgPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private DictionaryServiceClpInvoker _clpInvoker = new DictionaryServiceClpInvoker();
}