/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.graz.patho.haybaeck.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Patient service. Represents a row in the &quot;haybaeck.patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.graz.patho.haybaeck.model.impl.PatientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.graz.patho.haybaeck.model.impl.PatientImpl}.
 * </p>
 *
 * @author reihsr
 * @see Patient
 * @see at.meduni.graz.patho.haybaeck.model.impl.PatientImpl
 * @see at.meduni.graz.patho.haybaeck.model.impl.PatientModelImpl
 * @generated
 */
public interface PatientModel extends BaseModel<Patient> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patient model instance should use the {@link Patient} interface instead.
	 */

	/**
	 * Returns the primary key of this patient.
	 *
	 * @return the primary key of this patient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patient.
	 *
	 * @param primaryKey the primary key of this patient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patient_ ID of this patient.
	 *
	 * @return the patient_ ID of this patient
	 */
	public long getPatient_Id();

	/**
	 * Sets the patient_ ID of this patient.
	 *
	 * @param patient_Id the patient_ ID of this patient
	 */
	public void setPatient_Id(long patient_Id);

	/**
	 * Returns the identifier of this patient.
	 *
	 * @return the identifier of this patient
	 */
	@AutoEscape
	public String getIdentifier();

	/**
	 * Sets the identifier of this patient.
	 *
	 * @param identifier the identifier of this patient
	 */
	public void setIdentifier(String identifier);

	/**
	 * Returns the cohort of this patient.
	 *
	 * @return the cohort of this patient
	 */
	@AutoEscape
	public String getCohort();

	/**
	 * Sets the cohort of this patient.
	 *
	 * @param cohort the cohort of this patient
	 */
	public void setCohort(String cohort);

	/**
	 * Returns the first_name of this patient.
	 *
	 * @return the first_name of this patient
	 */
	@AutoEscape
	public String getFirst_name();

	/**
	 * Sets the first_name of this patient.
	 *
	 * @param first_name the first_name of this patient
	 */
	public void setFirst_name(String first_name);

	/**
	 * Returns the last_name of this patient.
	 *
	 * @return the last_name of this patient
	 */
	@AutoEscape
	public String getLast_name();

	/**
	 * Sets the last_name of this patient.
	 *
	 * @param last_name the last_name of this patient
	 */
	public void setLast_name(String last_name);

	/**
	 * Returns the date_of_birth of this patient.
	 *
	 * @return the date_of_birth of this patient
	 */
	public Date getDate_of_birth();

	/**
	 * Sets the date_of_birth of this patient.
	 *
	 * @param date_of_birth the date_of_birth of this patient
	 */
	public void setDate_of_birth(Date date_of_birth);

	/**
	 * Returns the date_of_death of this patient.
	 *
	 * @return the date_of_death of this patient
	 */
	public Date getDate_of_death();

	/**
	 * Sets the date_of_death of this patient.
	 *
	 * @param date_of_death the date_of_death of this patient
	 */
	public void setDate_of_death(Date date_of_death);

	/**
	 * Returns the couse_of_death of this patient.
	 *
	 * @return the couse_of_death of this patient
	 */
	@AutoEscape
	public String getCouse_of_death();

	/**
	 * Sets the couse_of_death of this patient.
	 *
	 * @param couse_of_death the couse_of_death of this patient
	 */
	public void setCouse_of_death(String couse_of_death);

	/**
	 * Returns the gender of this patient.
	 *
	 * @return the gender of this patient
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this patient.
	 *
	 * @param gender the gender of this patient
	 */
	public void setGender(String gender);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Patient patient);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Patient> toCacheModel();

	@Override
	public Patient toEscapedModel();

	@Override
	public Patient toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}