/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.graz.patho.haybaeck.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Sample service. Represents a row in the &quot;haybaeck.sample&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.graz.patho.haybaeck.model.impl.SampleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.graz.patho.haybaeck.model.impl.SampleImpl}.
 * </p>
 *
 * @author reihsr
 * @see Sample
 * @see at.meduni.graz.patho.haybaeck.model.impl.SampleImpl
 * @see at.meduni.graz.patho.haybaeck.model.impl.SampleModelImpl
 * @generated
 */
public interface SampleModel extends BaseModel<Sample> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sample model instance should use the {@link Sample} interface instead.
	 */

	/**
	 * Returns the primary key of this sample.
	 *
	 * @return the primary key of this sample
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sample.
	 *
	 * @param primaryKey the primary key of this sample
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sample_ ID of this sample.
	 *
	 * @return the sample_ ID of this sample
	 */
	public long getSample_Id();

	/**
	 * Sets the sample_ ID of this sample.
	 *
	 * @param sample_Id the sample_ ID of this sample
	 */
	public void setSample_Id(long sample_Id);

	/**
	 * Returns the patient_id of this sample.
	 *
	 * @return the patient_id of this sample
	 */
	public long getPatient_id();

	/**
	 * Sets the patient_id of this sample.
	 *
	 * @param patient_id the patient_id of this sample
	 */
	public void setPatient_id(long patient_id);

	/**
	 * Returns the t of this sample.
	 *
	 * @return the t of this sample
	 */
	@AutoEscape
	public String getT();

	/**
	 * Sets the t of this sample.
	 *
	 * @param t the t of this sample
	 */
	public void setT(String t);

	/**
	 * Returns the n of this sample.
	 *
	 * @return the n of this sample
	 */
	@AutoEscape
	public String getN();

	/**
	 * Sets the n of this sample.
	 *
	 * @param n the n of this sample
	 */
	public void setN(String n);

	/**
	 * Returns the m of this sample.
	 *
	 * @return the m of this sample
	 */
	@AutoEscape
	public String getM();

	/**
	 * Sets the m of this sample.
	 *
	 * @param m the m of this sample
	 */
	public void setM(String m);

	/**
	 * Returns the g of this sample.
	 *
	 * @return the g of this sample
	 */
	@AutoEscape
	public String getG();

	/**
	 * Sets the g of this sample.
	 *
	 * @param g the g of this sample
	 */
	public void setG(String g);

	/**
	 * Returns the r of this sample.
	 *
	 * @return the r of this sample
	 */
	@AutoEscape
	public String getR();

	/**
	 * Sets the r of this sample.
	 *
	 * @param r the r of this sample
	 */
	public void setR(String r);

	/**
	 * Returns the p of this sample.
	 *
	 * @return the p of this sample
	 */
	@AutoEscape
	public String getP();

	/**
	 * Sets the p of this sample.
	 *
	 * @param p the p of this sample
	 */
	public void setP(String p);

	/**
	 * Returns the l of this sample.
	 *
	 * @return the l of this sample
	 */
	@AutoEscape
	public String getL();

	/**
	 * Sets the l of this sample.
	 *
	 * @param l the l of this sample
	 */
	public void setL(String l);

	/**
	 * Returns the v of this sample.
	 *
	 * @return the v of this sample
	 */
	@AutoEscape
	public String getV();

	/**
	 * Sets the v of this sample.
	 *
	 * @param v the v of this sample
	 */
	public void setV(String v);

	/**
	 * Returns the stage of this sample.
	 *
	 * @return the stage of this sample
	 */
	@AutoEscape
	public String getStage();

	/**
	 * Sets the stage of this sample.
	 *
	 * @param stage the stage of this sample
	 */
	public void setStage(String stage);

	/**
	 * Returns the operation of this sample.
	 *
	 * @return the operation of this sample
	 */
	@AutoEscape
	public String getOperation();

	/**
	 * Sets the operation of this sample.
	 *
	 * @param operation the operation of this sample
	 */
	public void setOperation(String operation);

	/**
	 * Returns the post_op_treatment of this sample.
	 *
	 * @return the post_op_treatment of this sample
	 */
	@AutoEscape
	public String getPost_op_treatment();

	/**
	 * Sets the post_op_treatment of this sample.
	 *
	 * @param post_op_treatment the post_op_treatment of this sample
	 */
	public void setPost_op_treatment(String post_op_treatment);

	/**
	 * Returns the recurrence of this sample.
	 *
	 * @return the recurrence of this sample
	 */
	public boolean getRecurrence();

	/**
	 * Returns <code>true</code> if this sample is recurrence.
	 *
	 * @return <code>true</code> if this sample is recurrence; <code>false</code> otherwise
	 */
	public boolean isRecurrence();

	/**
	 * Sets whether this sample is recurrence.
	 *
	 * @param recurrence the recurrence of this sample
	 */
	public void setRecurrence(boolean recurrence);

	/**
	 * Returns the recurrence_date of this sample.
	 *
	 * @return the recurrence_date of this sample
	 */
	public Date getRecurrence_date();

	/**
	 * Sets the recurrence_date of this sample.
	 *
	 * @param recurrence_date the recurrence_date of this sample
	 */
	public void setRecurrence_date(Date recurrence_date);

	/**
	 * Returns the dead_live of this sample.
	 *
	 * @return the dead_live of this sample
	 */
	@AutoEscape
	public String getDead_live();

	/**
	 * Sets the dead_live of this sample.
	 *
	 * @param dead_live the dead_live of this sample
	 */
	public void setDead_live(String dead_live);

	/**
	 * Returns the last_follow_up_date of this sample.
	 *
	 * @return the last_follow_up_date of this sample
	 */
	public Date getLast_follow_up_date();

	/**
	 * Sets the last_follow_up_date of this sample.
	 *
	 * @param last_follow_up_date the last_follow_up_date of this sample
	 */
	public void setLast_follow_up_date(Date last_follow_up_date);

	/**
	 * Returns the hospital of this sample.
	 *
	 * @return the hospital of this sample
	 */
	@AutoEscape
	public String getHospital();

	/**
	 * Sets the hospital of this sample.
	 *
	 * @param hospital the hospital of this sample
	 */
	public void setHospital(String hospital);

	/**
	 * Returns the tnm_staging of this sample.
	 *
	 * @return the tnm_staging of this sample
	 */
	@AutoEscape
	public String getTnm_staging();

	/**
	 * Sets the tnm_staging of this sample.
	 *
	 * @param tnm_staging the tnm_staging of this sample
	 */
	public void setTnm_staging(String tnm_staging);

	/**
	 * Returns the diagnosis of this sample.
	 *
	 * @return the diagnosis of this sample
	 */
	@AutoEscape
	public String getDiagnosis();

	/**
	 * Sets the diagnosis of this sample.
	 *
	 * @param diagnosis the diagnosis of this sample
	 */
	public void setDiagnosis(String diagnosis);

	/**
	 * Returns the operation_date of this sample.
	 *
	 * @return the operation_date of this sample
	 */
	public Date getOperation_date();

	/**
	 * Sets the operation_date of this sample.
	 *
	 * @param operation_date the operation_date of this sample
	 */
	public void setOperation_date(Date operation_date);

	/**
	 * Returns the tmp_identifier of this sample.
	 *
	 * @return the tmp_identifier of this sample
	 */
	@AutoEscape
	public String getTmp_identifier();

	/**
	 * Sets the tmp_identifier of this sample.
	 *
	 * @param tmp_identifier the tmp_identifier of this sample
	 */
	public void setTmp_identifier(String tmp_identifier);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Sample sample);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Sample> toCacheModel();

	@Override
	public Sample toEscapedModel();

	@Override
	public Sample toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}