/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.graz.patho.haybaeck.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TMA service. Represents a row in the &quot;haybaeck.tma&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.graz.patho.haybaeck.model.impl.TMAModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.graz.patho.haybaeck.model.impl.TMAImpl}.
 * </p>
 *
 * @author reihsr
 * @see TMA
 * @see at.meduni.graz.patho.haybaeck.model.impl.TMAImpl
 * @see at.meduni.graz.patho.haybaeck.model.impl.TMAModelImpl
 * @generated
 */
public interface TMAModel extends BaseModel<TMA> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t m a model instance should use the {@link TMA} interface instead.
	 */

	/**
	 * Returns the primary key of this t m a.
	 *
	 * @return the primary key of this t m a
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t m a.
	 *
	 * @param primaryKey the primary key of this t m a
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tma_ ID of this t m a.
	 *
	 * @return the tma_ ID of this t m a
	 */
	public long getTma_Id();

	/**
	 * Sets the tma_ ID of this t m a.
	 *
	 * @param tma_Id the tma_ ID of this t m a
	 */
	public void setTma_Id(long tma_Id);

	/**
	 * Returns the sample_id of this t m a.
	 *
	 * @return the sample_id of this t m a
	 */
	public long getSample_id();

	/**
	 * Sets the sample_id of this t m a.
	 *
	 * @param sample_id the sample_id of this t m a
	 */
	public void setSample_id(long sample_id);

	/**
	 * Returns the tma_name of this t m a.
	 *
	 * @return the tma_name of this t m a
	 */
	@AutoEscape
	public String getTma_name();

	/**
	 * Sets the tma_name of this t m a.
	 *
	 * @param tma_name the tma_name of this t m a
	 */
	public void setTma_name(String tma_name);

	/**
	 * Returns the tma_number of this t m a.
	 *
	 * @return the tma_number of this t m a
	 */
	@AutoEscape
	public String getTma_number();

	/**
	 * Sets the tma_number of this t m a.
	 *
	 * @param tma_number the tma_number of this t m a
	 */
	public void setTma_number(String tma_number);

	/**
	 * Returns the tma_comment of this t m a.
	 *
	 * @return the tma_comment of this t m a
	 */
	@AutoEscape
	public String getTma_comment();

	/**
	 * Sets the tma_comment of this t m a.
	 *
	 * @param tma_comment the tma_comment of this t m a
	 */
	public void setTma_comment(String tma_comment);

	/**
	 * Returns the cytoplasmic_stat_5_intensity of this t m a.
	 *
	 * @return the cytoplasmic_stat_5_intensity of this t m a
	 */
	public long getCytoplasmic_stat_5_intensity();

	/**
	 * Sets the cytoplasmic_stat_5_intensity of this t m a.
	 *
	 * @param cytoplasmic_stat_5_intensity the cytoplasmic_stat_5_intensity of this t m a
	 */
	public void setCytoplasmic_stat_5_intensity(
		long cytoplasmic_stat_5_intensity);

	/**
	 * Returns the cytoplasmic_stat_5_density of this t m a.
	 *
	 * @return the cytoplasmic_stat_5_density of this t m a
	 */
	public long getCytoplasmic_stat_5_density();

	/**
	 * Sets the cytoplasmic_stat_5_density of this t m a.
	 *
	 * @param cytoplasmic_stat_5_density the cytoplasmic_stat_5_density of this t m a
	 */
	public void setCytoplasmic_stat_5_density(long cytoplasmic_stat_5_density);

	/**
	 * Returns the nuclear_stat_5_intensity of this t m a.
	 *
	 * @return the nuclear_stat_5_intensity of this t m a
	 */
	public long getNuclear_stat_5_intensity();

	/**
	 * Sets the nuclear_stat_5_intensity of this t m a.
	 *
	 * @param nuclear_stat_5_intensity the nuclear_stat_5_intensity of this t m a
	 */
	public void setNuclear_stat_5_intensity(long nuclear_stat_5_intensity);

	/**
	 * Returns the nuclear_stat_5_density of this t m a.
	 *
	 * @return the nuclear_stat_5_density of this t m a
	 */
	public long getNuclear_stat_5_density();

	/**
	 * Sets the nuclear_stat_5_density of this t m a.
	 *
	 * @param nuclear_stat_5_density the nuclear_stat_5_density of this t m a
	 */
	public void setNuclear_stat_5_density(long nuclear_stat_5_density);

	/**
	 * Returns the cytoplasmic_cjun_intensity of this t m a.
	 *
	 * @return the cytoplasmic_cjun_intensity of this t m a
	 */
	public long getCytoplasmic_cjun_intensity();

	/**
	 * Sets the cytoplasmic_cjun_intensity of this t m a.
	 *
	 * @param cytoplasmic_cjun_intensity the cytoplasmic_cjun_intensity of this t m a
	 */
	public void setCytoplasmic_cjun_intensity(long cytoplasmic_cjun_intensity);

	/**
	 * Returns the cytoplasmic_cjun_density of this t m a.
	 *
	 * @return the cytoplasmic_cjun_density of this t m a
	 */
	public long getCytoplasmic_cjun_density();

	/**
	 * Sets the cytoplasmic_cjun_density of this t m a.
	 *
	 * @param cytoplasmic_cjun_density the cytoplasmic_cjun_density of this t m a
	 */
	public void setCytoplasmic_cjun_density(long cytoplasmic_cjun_density);

	/**
	 * Returns the nuclear_cjun_intensity of this t m a.
	 *
	 * @return the nuclear_cjun_intensity of this t m a
	 */
	public long getNuclear_cjun_intensity();

	/**
	 * Sets the nuclear_cjun_intensity of this t m a.
	 *
	 * @param nuclear_cjun_intensity the nuclear_cjun_intensity of this t m a
	 */
	public void setNuclear_cjun_intensity(long nuclear_cjun_intensity);

	/**
	 * Returns the nuclear_cjun_density of this t m a.
	 *
	 * @return the nuclear_cjun_density of this t m a
	 */
	public long getNuclear_cjun_density();

	/**
	 * Sets the nuclear_cjun_density of this t m a.
	 *
	 * @param nuclear_cjun_density the nuclear_cjun_density of this t m a
	 */
	public void setNuclear_cjun_density(long nuclear_cjun_density);

	/**
	 * Returns the cytoplasmic_pstat_3_intensity of this t m a.
	 *
	 * @return the cytoplasmic_pstat_3_intensity of this t m a
	 */
	public long getCytoplasmic_pstat_3_intensity();

	/**
	 * Sets the cytoplasmic_pstat_3_intensity of this t m a.
	 *
	 * @param cytoplasmic_pstat_3_intensity the cytoplasmic_pstat_3_intensity of this t m a
	 */
	public void setCytoplasmic_pstat_3_intensity(
		long cytoplasmic_pstat_3_intensity);

	/**
	 * Returns the cytoplasmic_pstat_3_density of this t m a.
	 *
	 * @return the cytoplasmic_pstat_3_density of this t m a
	 */
	public long getCytoplasmic_pstat_3_density();

	/**
	 * Sets the cytoplasmic_pstat_3_density of this t m a.
	 *
	 * @param cytoplasmic_pstat_3_density the cytoplasmic_pstat_3_density of this t m a
	 */
	public void setCytoplasmic_pstat_3_density(long cytoplasmic_pstat_3_density);

	/**
	 * Returns the nuclear_pstat_3_intensity of this t m a.
	 *
	 * @return the nuclear_pstat_3_intensity of this t m a
	 */
	public long getNuclear_pstat_3_intensity();

	/**
	 * Sets the nuclear_pstat_3_intensity of this t m a.
	 *
	 * @param nuclear_pstat_3_intensity the nuclear_pstat_3_intensity of this t m a
	 */
	public void setNuclear_pstat_3_intensity(long nuclear_pstat_3_intensity);

	/**
	 * Returns the nuclear_pstat_3_density of this t m a.
	 *
	 * @return the nuclear_pstat_3_density of this t m a
	 */
	public long getNuclear_pstat_3_density();

	/**
	 * Sets the nuclear_pstat_3_density of this t m a.
	 *
	 * @param nuclear_pstat_3_density the nuclear_pstat_3_density of this t m a
	 */
	public void setNuclear_pstat_3_density(long nuclear_pstat_3_density);

	/**
	 * Returns the cytoplasmic_pstat_5_intensity of this t m a.
	 *
	 * @return the cytoplasmic_pstat_5_intensity of this t m a
	 */
	public long getCytoplasmic_pstat_5_intensity();

	/**
	 * Sets the cytoplasmic_pstat_5_intensity of this t m a.
	 *
	 * @param cytoplasmic_pstat_5_intensity the cytoplasmic_pstat_5_intensity of this t m a
	 */
	public void setCytoplasmic_pstat_5_intensity(
		long cytoplasmic_pstat_5_intensity);

	/**
	 * Returns the cytoplasmic_pstat_5_density of this t m a.
	 *
	 * @return the cytoplasmic_pstat_5_density of this t m a
	 */
	public long getCytoplasmic_pstat_5_density();

	/**
	 * Sets the cytoplasmic_pstat_5_density of this t m a.
	 *
	 * @param cytoplasmic_pstat_5_density the cytoplasmic_pstat_5_density of this t m a
	 */
	public void setCytoplasmic_pstat_5_density(long cytoplasmic_pstat_5_density);

	/**
	 * Returns the nuclear_pstat_5_intensity of this t m a.
	 *
	 * @return the nuclear_pstat_5_intensity of this t m a
	 */
	public long getNuclear_pstat_5_intensity();

	/**
	 * Sets the nuclear_pstat_5_intensity of this t m a.
	 *
	 * @param nuclear_pstat_5_intensity the nuclear_pstat_5_intensity of this t m a
	 */
	public void setNuclear_pstat_5_intensity(long nuclear_pstat_5_intensity);

	/**
	 * Returns the nuclear_pstat_5_density of this t m a.
	 *
	 * @return the nuclear_pstat_5_density of this t m a
	 */
	public long getNuclear_pstat_5_density();

	/**
	 * Sets the nuclear_pstat_5_density of this t m a.
	 *
	 * @param nuclear_pstat_5_density the nuclear_pstat_5_density of this t m a
	 */
	public void setNuclear_pstat_5_density(long nuclear_pstat_5_density);

	/**
	 * Returns the cytoplasmic_pstat_1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_pstat_1_intensity of this t m a
	 */
	public long getCytoplasmic_pstat_1_intensity();

	/**
	 * Sets the cytoplasmic_pstat_1_intensity of this t m a.
	 *
	 * @param cytoplasmic_pstat_1_intensity the cytoplasmic_pstat_1_intensity of this t m a
	 */
	public void setCytoplasmic_pstat_1_intensity(
		long cytoplasmic_pstat_1_intensity);

	/**
	 * Returns the cytoplasmic_pstat_1_density of this t m a.
	 *
	 * @return the cytoplasmic_pstat_1_density of this t m a
	 */
	public long getCytoplasmic_pstat_1_density();

	/**
	 * Sets the cytoplasmic_pstat_1_density of this t m a.
	 *
	 * @param cytoplasmic_pstat_1_density the cytoplasmic_pstat_1_density of this t m a
	 */
	public void setCytoplasmic_pstat_1_density(long cytoplasmic_pstat_1_density);

	/**
	 * Returns the nuclear_pstat_1_intensity of this t m a.
	 *
	 * @return the nuclear_pstat_1_intensity of this t m a
	 */
	public long getNuclear_pstat_1_intensity();

	/**
	 * Sets the nuclear_pstat_1_intensity of this t m a.
	 *
	 * @param nuclear_pstat_1_intensity the nuclear_pstat_1_intensity of this t m a
	 */
	public void setNuclear_pstat_1_intensity(long nuclear_pstat_1_intensity);

	/**
	 * Returns the cytoplasmic_il6r_intensity of this t m a.
	 *
	 * @return the cytoplasmic_il6r_intensity of this t m a
	 */
	public long getCytoplasmic_il6r_intensity();

	/**
	 * Sets the cytoplasmic_il6r_intensity of this t m a.
	 *
	 * @param cytoplasmic_il6r_intensity the cytoplasmic_il6r_intensity of this t m a
	 */
	public void setCytoplasmic_il6r_intensity(long cytoplasmic_il6r_intensity);

	/**
	 * Returns the cytoplasmic_il6r_density of this t m a.
	 *
	 * @return the cytoplasmic_il6r_density of this t m a
	 */
	public long getCytoplasmic_il6r_density();

	/**
	 * Sets the cytoplasmic_il6r_density of this t m a.
	 *
	 * @param cytoplasmic_il6r_density the cytoplasmic_il6r_density of this t m a
	 */
	public void setCytoplasmic_il6r_density(long cytoplasmic_il6r_density);

	/**
	 * Returns the nuclear_il6r_intensity of this t m a.
	 *
	 * @return the nuclear_il6r_intensity of this t m a
	 */
	public long getNuclear_il6r_intensity();

	/**
	 * Sets the nuclear_il6r_intensity of this t m a.
	 *
	 * @param nuclear_il6r_intensity the nuclear_il6r_intensity of this t m a
	 */
	public void setNuclear_il6r_intensity(long nuclear_il6r_intensity);

	/**
	 * Returns the nuclear_il6r_density of this t m a.
	 *
	 * @return the nuclear_il6r_density of this t m a
	 */
	public long getNuclear_il6r_density();

	/**
	 * Sets the nuclear_il6r_density of this t m a.
	 *
	 * @param nuclear_il6r_density the nuclear_il6r_density of this t m a
	 */
	public void setNuclear_il6r_density(long nuclear_il6r_density);

	/**
	 * Returns the cytoplasmic_socs1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_socs1_intensity of this t m a
	 */
	public long getCytoplasmic_socs1_intensity();

	/**
	 * Sets the cytoplasmic_socs1_intensity of this t m a.
	 *
	 * @param cytoplasmic_socs1_intensity the cytoplasmic_socs1_intensity of this t m a
	 */
	public void setCytoplasmic_socs1_intensity(long cytoplasmic_socs1_intensity);

	/**
	 * Returns the cytoplasmic_socs1_density of this t m a.
	 *
	 * @return the cytoplasmic_socs1_density of this t m a
	 */
	public long getCytoplasmic_socs1_density();

	/**
	 * Sets the cytoplasmic_socs1_density of this t m a.
	 *
	 * @param cytoplasmic_socs1_density the cytoplasmic_socs1_density of this t m a
	 */
	public void setCytoplasmic_socs1_density(long cytoplasmic_socs1_density);

	/**
	 * Returns the nuclear_socs1_intensity of this t m a.
	 *
	 * @return the nuclear_socs1_intensity of this t m a
	 */
	public long getNuclear_socs1_intensity();

	/**
	 * Sets the nuclear_socs1_intensity of this t m a.
	 *
	 * @param nuclear_socs1_intensity the nuclear_socs1_intensity of this t m a
	 */
	public void setNuclear_socs1_intensity(long nuclear_socs1_intensity);

	/**
	 * Returns the nuclear_socs1_density of this t m a.
	 *
	 * @return the nuclear_socs1_density of this t m a
	 */
	public long getNuclear_socs1_density();

	/**
	 * Sets the nuclear_socs1_density of this t m a.
	 *
	 * @param nuclear_socs1_density the nuclear_socs1_density of this t m a
	 */
	public void setNuclear_socs1_density(long nuclear_socs1_density);

	/**
	 * Returns the cytoplasmic_socs3_intensity of this t m a.
	 *
	 * @return the cytoplasmic_socs3_intensity of this t m a
	 */
	public long getCytoplasmic_socs3_intensity();

	/**
	 * Sets the cytoplasmic_socs3_intensity of this t m a.
	 *
	 * @param cytoplasmic_socs3_intensity the cytoplasmic_socs3_intensity of this t m a
	 */
	public void setCytoplasmic_socs3_intensity(long cytoplasmic_socs3_intensity);

	/**
	 * Returns the cytoplasmic_socs3_density of this t m a.
	 *
	 * @return the cytoplasmic_socs3_density of this t m a
	 */
	public long getCytoplasmic_socs3_density();

	/**
	 * Sets the cytoplasmic_socs3_density of this t m a.
	 *
	 * @param cytoplasmic_socs3_density the cytoplasmic_socs3_density of this t m a
	 */
	public void setCytoplasmic_socs3_density(long cytoplasmic_socs3_density);

	/**
	 * Returns the nuclear_socs3_intensity of this t m a.
	 *
	 * @return the nuclear_socs3_intensity of this t m a
	 */
	public long getNuclear_socs3_intensity();

	/**
	 * Sets the nuclear_socs3_intensity of this t m a.
	 *
	 * @param nuclear_socs3_intensity the nuclear_socs3_intensity of this t m a
	 */
	public void setNuclear_socs3_intensity(long nuclear_socs3_intensity);

	/**
	 * Returns the nuclear_socs3_density of this t m a.
	 *
	 * @return the nuclear_socs3_density of this t m a
	 */
	public long getNuclear_socs3_density();

	/**
	 * Sets the nuclear_socs3_density of this t m a.
	 *
	 * @param nuclear_socs3_density the nuclear_socs3_density of this t m a
	 */
	public void setNuclear_socs3_density(long nuclear_socs3_density);

	/**
	 * Returns the cytoplasmic_junb_intensity of this t m a.
	 *
	 * @return the cytoplasmic_junb_intensity of this t m a
	 */
	public long getCytoplasmic_junb_intensity();

	/**
	 * Sets the cytoplasmic_junb_intensity of this t m a.
	 *
	 * @param cytoplasmic_junb_intensity the cytoplasmic_junb_intensity of this t m a
	 */
	public void setCytoplasmic_junb_intensity(long cytoplasmic_junb_intensity);

	/**
	 * Returns the cytoplasmic_junb_density of this t m a.
	 *
	 * @return the cytoplasmic_junb_density of this t m a
	 */
	public long getCytoplasmic_junb_density();

	/**
	 * Sets the cytoplasmic_junb_density of this t m a.
	 *
	 * @param cytoplasmic_junb_density the cytoplasmic_junb_density of this t m a
	 */
	public void setCytoplasmic_junb_density(long cytoplasmic_junb_density);

	/**
	 * Returns the nuclear_junb_intensity of this t m a.
	 *
	 * @return the nuclear_junb_intensity of this t m a
	 */
	public long getNuclear_junb_intensity();

	/**
	 * Sets the nuclear_junb_intensity of this t m a.
	 *
	 * @param nuclear_junb_intensity the nuclear_junb_intensity of this t m a
	 */
	public void setNuclear_junb_intensity(long nuclear_junb_intensity);

	/**
	 * Returns the nuclear_junb_density of this t m a.
	 *
	 * @return the nuclear_junb_density of this t m a
	 */
	public long getNuclear_junb_density();

	/**
	 * Sets the nuclear_junb_density of this t m a.
	 *
	 * @param nuclear_junb_density the nuclear_junb_density of this t m a
	 */
	public void setNuclear_junb_density(long nuclear_junb_density);

	/**
	 * Returns the cytoplasmic_stat_3_intensity of this t m a.
	 *
	 * @return the cytoplasmic_stat_3_intensity of this t m a
	 */
	public long getCytoplasmic_stat_3_intensity();

	/**
	 * Sets the cytoplasmic_stat_3_intensity of this t m a.
	 *
	 * @param cytoplasmic_stat_3_intensity the cytoplasmic_stat_3_intensity of this t m a
	 */
	public void setCytoplasmic_stat_3_intensity(
		long cytoplasmic_stat_3_intensity);

	/**
	 * Returns the cytoplasmic_stat_3_density of this t m a.
	 *
	 * @return the cytoplasmic_stat_3_density of this t m a
	 */
	public long getCytoplasmic_stat_3_density();

	/**
	 * Sets the cytoplasmic_stat_3_density of this t m a.
	 *
	 * @param cytoplasmic_stat_3_density the cytoplasmic_stat_3_density of this t m a
	 */
	public void setCytoplasmic_stat_3_density(long cytoplasmic_stat_3_density);

	/**
	 * Returns the nuclear_stat_3_intensity of this t m a.
	 *
	 * @return the nuclear_stat_3_intensity of this t m a
	 */
	public long getNuclear_stat_3_intensity();

	/**
	 * Sets the nuclear_stat_3_intensity of this t m a.
	 *
	 * @param nuclear_stat_3_intensity the nuclear_stat_3_intensity of this t m a
	 */
	public void setNuclear_stat_3_intensity(long nuclear_stat_3_intensity);

	/**
	 * Returns the nuclear_stat_3_density of this t m a.
	 *
	 * @return the nuclear_stat_3_density of this t m a
	 */
	public long getNuclear_stat_3_density();

	/**
	 * Sets the nuclear_stat_3_density of this t m a.
	 *
	 * @param nuclear_stat_3_density the nuclear_stat_3_density of this t m a
	 */
	public void setNuclear_stat_3_density(long nuclear_stat_3_density);

	/**
	 * Returns the cytoplasmic_stat_5a_intensity of this t m a.
	 *
	 * @return the cytoplasmic_stat_5a_intensity of this t m a
	 */
	public long getCytoplasmic_stat_5a_intensity();

	/**
	 * Sets the cytoplasmic_stat_5a_intensity of this t m a.
	 *
	 * @param cytoplasmic_stat_5a_intensity the cytoplasmic_stat_5a_intensity of this t m a
	 */
	public void setCytoplasmic_stat_5a_intensity(
		long cytoplasmic_stat_5a_intensity);

	/**
	 * Returns the cytoplasmic_stat_5a_density of this t m a.
	 *
	 * @return the cytoplasmic_stat_5a_density of this t m a
	 */
	public long getCytoplasmic_stat_5a_density();

	/**
	 * Sets the cytoplasmic_stat_5a_density of this t m a.
	 *
	 * @param cytoplasmic_stat_5a_density the cytoplasmic_stat_5a_density of this t m a
	 */
	public void setCytoplasmic_stat_5a_density(long cytoplasmic_stat_5a_density);

	/**
	 * Returns the nuclear_stat_5a_intensity of this t m a.
	 *
	 * @return the nuclear_stat_5a_intensity of this t m a
	 */
	public long getNuclear_stat_5a_intensity();

	/**
	 * Sets the nuclear_stat_5a_intensity of this t m a.
	 *
	 * @param nuclear_stat_5a_intensity the nuclear_stat_5a_intensity of this t m a
	 */
	public void setNuclear_stat_5a_intensity(long nuclear_stat_5a_intensity);

	/**
	 * Returns the nuclear_stat_5a_density of this t m a.
	 *
	 * @return the nuclear_stat_5a_density of this t m a
	 */
	public long getNuclear_stat_5a_density();

	/**
	 * Sets the nuclear_stat_5a_density of this t m a.
	 *
	 * @param nuclear_stat_5a_density the nuclear_stat_5a_density of this t m a
	 */
	public void setNuclear_stat_5a_density(long nuclear_stat_5a_density);

	/**
	 * Returns the cytoplasmic_stat_5b_intensity of this t m a.
	 *
	 * @return the cytoplasmic_stat_5b_intensity of this t m a
	 */
	public long getCytoplasmic_stat_5b_intensity();

	/**
	 * Sets the cytoplasmic_stat_5b_intensity of this t m a.
	 *
	 * @param cytoplasmic_stat_5b_intensity the cytoplasmic_stat_5b_intensity of this t m a
	 */
	public void setCytoplasmic_stat_5b_intensity(
		long cytoplasmic_stat_5b_intensity);

	/**
	 * Returns the cytoplasmic_stat_5b_density of this t m a.
	 *
	 * @return the cytoplasmic_stat_5b_density of this t m a
	 */
	public long getCytoplasmic_stat_5b_density();

	/**
	 * Sets the cytoplasmic_stat_5b_density of this t m a.
	 *
	 * @param cytoplasmic_stat_5b_density the cytoplasmic_stat_5b_density of this t m a
	 */
	public void setCytoplasmic_stat_5b_density(long cytoplasmic_stat_5b_density);

	/**
	 * Returns the nuclear_stat_5b_intensity of this t m a.
	 *
	 * @return the nuclear_stat_5b_intensity of this t m a
	 */
	public long getNuclear_stat_5b_intensity();

	/**
	 * Sets the nuclear_stat_5b_intensity of this t m a.
	 *
	 * @param nuclear_stat_5b_intensity the nuclear_stat_5b_intensity of this t m a
	 */
	public void setNuclear_stat_5b_intensity(long nuclear_stat_5b_intensity);

	/**
	 * Returns the nuclear_stat_5b_density of this t m a.
	 *
	 * @return the nuclear_stat_5b_density of this t m a
	 */
	public long getNuclear_stat_5b_density();

	/**
	 * Sets the nuclear_stat_5b_density of this t m a.
	 *
	 * @param nuclear_stat_5b_density the nuclear_stat_5b_density of this t m a
	 */
	public void setNuclear_stat_5b_density(long nuclear_stat_5b_density);

	/**
	 * Returns the cytoplasmic_eif3a_intensity of this t m a.
	 *
	 * @return the cytoplasmic_eif3a_intensity of this t m a
	 */
	public long getCytoplasmic_eif3a_intensity();

	/**
	 * Sets the cytoplasmic_eif3a_intensity of this t m a.
	 *
	 * @param cytoplasmic_eif3a_intensity the cytoplasmic_eif3a_intensity of this t m a
	 */
	public void setCytoplasmic_eif3a_intensity(long cytoplasmic_eif3a_intensity);

	/**
	 * Returns the cytoplasmic_eif3a_density of this t m a.
	 *
	 * @return the cytoplasmic_eif3a_density of this t m a
	 */
	public long getCytoplasmic_eif3a_density();

	/**
	 * Sets the cytoplasmic_eif3a_density of this t m a.
	 *
	 * @param cytoplasmic_eif3a_density the cytoplasmic_eif3a_density of this t m a
	 */
	public void setCytoplasmic_eif3a_density(long cytoplasmic_eif3a_density);

	/**
	 * Returns the cytoplasmic_eif3a_peter_intensity of this t m a.
	 *
	 * @return the cytoplasmic_eif3a_peter_intensity of this t m a
	 */
	public long getCytoplasmic_eif3a_peter_intensity();

	/**
	 * Sets the cytoplasmic_eif3a_peter_intensity of this t m a.
	 *
	 * @param cytoplasmic_eif3a_peter_intensity the cytoplasmic_eif3a_peter_intensity of this t m a
	 */
	public void setCytoplasmic_eif3a_peter_intensity(
		long cytoplasmic_eif3a_peter_intensity);

	/**
	 * Returns the cytoplasmic_eif3a_peter_density of this t m a.
	 *
	 * @return the cytoplasmic_eif3a_peter_density of this t m a
	 */
	public long getCytoplasmic_eif3a_peter_density();

	/**
	 * Sets the cytoplasmic_eif3a_peter_density of this t m a.
	 *
	 * @param cytoplasmic_eif3a_peter_density the cytoplasmic_eif3a_peter_density of this t m a
	 */
	public void setCytoplasmic_eif3a_peter_density(
		long cytoplasmic_eif3a_peter_density);

	/**
	 * Returns the cytoplasmic_itih_5_o1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_itih_5_o1_intensity of this t m a
	 */
	public long getCytoplasmic_itih_5_o1_intensity();

	/**
	 * Sets the cytoplasmic_itih_5_o1_intensity of this t m a.
	 *
	 * @param cytoplasmic_itih_5_o1_intensity the cytoplasmic_itih_5_o1_intensity of this t m a
	 */
	public void setCytoplasmic_itih_5_o1_intensity(
		long cytoplasmic_itih_5_o1_intensity);

	/**
	 * Returns the cytoplasmic_itih_5_o1_density of this t m a.
	 *
	 * @return the cytoplasmic_itih_5_o1_density of this t m a
	 */
	public long getCytoplasmic_itih_5_o1_density();

	/**
	 * Sets the cytoplasmic_itih_5_o1_density of this t m a.
	 *
	 * @param cytoplasmic_itih_5_o1_density the cytoplasmic_itih_5_o1_density of this t m a
	 */
	public void setCytoplasmic_itih_5_o1_density(
		long cytoplasmic_itih_5_o1_density);

	/**
	 * Returns the nuclear_itih_5_o1_intensity of this t m a.
	 *
	 * @return the nuclear_itih_5_o1_intensity of this t m a
	 */
	public long getNuclear_itih_5_o1_intensity();

	/**
	 * Sets the nuclear_itih_5_o1_intensity of this t m a.
	 *
	 * @param nuclear_itih_5_o1_intensity the nuclear_itih_5_o1_intensity of this t m a
	 */
	public void setNuclear_itih_5_o1_intensity(long nuclear_itih_5_o1_intensity);

	/**
	 * Returns the nuclear_itih_5_o1_density of this t m a.
	 *
	 * @return the nuclear_itih_5_o1_density of this t m a
	 */
	public long getNuclear_itih_5_o1_density();

	/**
	 * Sets the nuclear_itih_5_o1_density of this t m a.
	 *
	 * @param nuclear_itih_5_o1_density the nuclear_itih_5_o1_density of this t m a
	 */
	public void setNuclear_itih_5_o1_density(long nuclear_itih_5_o1_density);

	/**
	 * Returns the cytoplasmic_itih_5_o2_intensity of this t m a.
	 *
	 * @return the cytoplasmic_itih_5_o2_intensity of this t m a
	 */
	public long getCytoplasmic_itih_5_o2_intensity();

	/**
	 * Sets the cytoplasmic_itih_5_o2_intensity of this t m a.
	 *
	 * @param cytoplasmic_itih_5_o2_intensity the cytoplasmic_itih_5_o2_intensity of this t m a
	 */
	public void setCytoplasmic_itih_5_o2_intensity(
		long cytoplasmic_itih_5_o2_intensity);

	/**
	 * Returns the cytoplasmic_itih_5_o2_density of this t m a.
	 *
	 * @return the cytoplasmic_itih_5_o2_density of this t m a
	 */
	public long getCytoplasmic_itih_5_o2_density();

	/**
	 * Sets the cytoplasmic_itih_5_o2_density of this t m a.
	 *
	 * @param cytoplasmic_itih_5_o2_density the cytoplasmic_itih_5_o2_density of this t m a
	 */
	public void setCytoplasmic_itih_5_o2_density(
		long cytoplasmic_itih_5_o2_density);

	/**
	 * Returns the nuclear_itih_5_o2_intensity of this t m a.
	 *
	 * @return the nuclear_itih_5_o2_intensity of this t m a
	 */
	public long getNuclear_itih_5_o2_intensity();

	/**
	 * Sets the nuclear_itih_5_o2_intensity of this t m a.
	 *
	 * @param nuclear_itih_5_o2_intensity the nuclear_itih_5_o2_intensity of this t m a
	 */
	public void setNuclear_itih_5_o2_intensity(long nuclear_itih_5_o2_intensity);

	/**
	 * Returns the nuclear_itih_5_o2_density of this t m a.
	 *
	 * @return the nuclear_itih_5_o2_density of this t m a
	 */
	public long getNuclear_itih_5_o2_density();

	/**
	 * Sets the nuclear_itih_5_o2_density of this t m a.
	 *
	 * @param nuclear_itih_5_o2_density the nuclear_itih_5_o2_density of this t m a
	 */
	public void setNuclear_itih_5_o2_density(long nuclear_itih_5_o2_density);

	/**
	 * Returns the cytoplasmic_imp2_2_intensity of this t m a.
	 *
	 * @return the cytoplasmic_imp2_2_intensity of this t m a
	 */
	public long getCytoplasmic_imp2_2_intensity();

	/**
	 * Sets the cytoplasmic_imp2_2_intensity of this t m a.
	 *
	 * @param cytoplasmic_imp2_2_intensity the cytoplasmic_imp2_2_intensity of this t m a
	 */
	public void setCytoplasmic_imp2_2_intensity(
		long cytoplasmic_imp2_2_intensity);

	/**
	 * Returns the cytoplasmic_imp2_2_density of this t m a.
	 *
	 * @return the cytoplasmic_imp2_2_density of this t m a
	 */
	public long getCytoplasmic_imp2_2_density();

	/**
	 * Sets the cytoplasmic_imp2_2_density of this t m a.
	 *
	 * @param cytoplasmic_imp2_2_density the cytoplasmic_imp2_2_density of this t m a
	 */
	public void setCytoplasmic_imp2_2_density(long cytoplasmic_imp2_2_density);

	/**
	 * Returns the cytoplasmic_stat_1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_stat_1_intensity of this t m a
	 */
	public long getCytoplasmic_stat_1_intensity();

	/**
	 * Sets the cytoplasmic_stat_1_intensity of this t m a.
	 *
	 * @param cytoplasmic_stat_1_intensity the cytoplasmic_stat_1_intensity of this t m a
	 */
	public void setCytoplasmic_stat_1_intensity(
		long cytoplasmic_stat_1_intensity);

	/**
	 * Returns the cytoplasmic_stat_1_density of this t m a.
	 *
	 * @return the cytoplasmic_stat_1_density of this t m a
	 */
	public long getCytoplasmic_stat_1_density();

	/**
	 * Sets the cytoplasmic_stat_1_density of this t m a.
	 *
	 * @param cytoplasmic_stat_1_density the cytoplasmic_stat_1_density of this t m a
	 */
	public void setCytoplasmic_stat_1_density(long cytoplasmic_stat_1_density);

	/**
	 * Returns the nuclear_stat_1_intensity of this t m a.
	 *
	 * @return the nuclear_stat_1_intensity of this t m a
	 */
	public long getNuclear_stat_1_intensity();

	/**
	 * Sets the nuclear_stat_1_intensity of this t m a.
	 *
	 * @param nuclear_stat_1_intensity the nuclear_stat_1_intensity of this t m a
	 */
	public void setNuclear_stat_1_intensity(long nuclear_stat_1_intensity);

	/**
	 * Returns the nuclear_stat_1_density of this t m a.
	 *
	 * @return the nuclear_stat_1_density of this t m a
	 */
	public long getNuclear_stat_1_density();

	/**
	 * Sets the nuclear_stat_1_density of this t m a.
	 *
	 * @param nuclear_stat_1_density the nuclear_stat_1_density of this t m a
	 */
	public void setNuclear_stat_1_density(long nuclear_stat_1_density);

	/**
	 * Returns the cytoplasmic_nfkb1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_nfkb1_intensity of this t m a
	 */
	public long getCytoplasmic_nfkb1_intensity();

	/**
	 * Sets the cytoplasmic_nfkb1_intensity of this t m a.
	 *
	 * @param cytoplasmic_nfkb1_intensity the cytoplasmic_nfkb1_intensity of this t m a
	 */
	public void setCytoplasmic_nfkb1_intensity(long cytoplasmic_nfkb1_intensity);

	/**
	 * Returns the cytoplasmic_nfkb1_density of this t m a.
	 *
	 * @return the cytoplasmic_nfkb1_density of this t m a
	 */
	public long getCytoplasmic_nfkb1_density();

	/**
	 * Sets the cytoplasmic_nfkb1_density of this t m a.
	 *
	 * @param cytoplasmic_nfkb1_density the cytoplasmic_nfkb1_density of this t m a
	 */
	public void setCytoplasmic_nfkb1_density(long cytoplasmic_nfkb1_density);

	/**
	 * Returns the nuclear_nfkb1_intensity of this t m a.
	 *
	 * @return the nuclear_nfkb1_intensity of this t m a
	 */
	public long getNuclear_nfkb1_intensity();

	/**
	 * Sets the nuclear_nfkb1_intensity of this t m a.
	 *
	 * @param nuclear_nfkb1_intensity the nuclear_nfkb1_intensity of this t m a
	 */
	public void setNuclear_nfkb1_intensity(long nuclear_nfkb1_intensity);

	/**
	 * Returns the nuclear_nfkb1_density of this t m a.
	 *
	 * @return the nuclear_nfkb1_density of this t m a
	 */
	public long getNuclear_nfkb1_density();

	/**
	 * Sets the nuclear_nfkb1_density of this t m a.
	 *
	 * @param nuclear_nfkb1_density the nuclear_nfkb1_density of this t m a
	 */
	public void setNuclear_nfkb1_density(long nuclear_nfkb1_density);

	/**
	 * Returns the cytoplasmic_nfkb2_intensity of this t m a.
	 *
	 * @return the cytoplasmic_nfkb2_intensity of this t m a
	 */
	public long getCytoplasmic_nfkb2_intensity();

	/**
	 * Sets the cytoplasmic_nfkb2_intensity of this t m a.
	 *
	 * @param cytoplasmic_nfkb2_intensity the cytoplasmic_nfkb2_intensity of this t m a
	 */
	public void setCytoplasmic_nfkb2_intensity(long cytoplasmic_nfkb2_intensity);

	/**
	 * Returns the cytoplasmic_nfkb2_density of this t m a.
	 *
	 * @return the cytoplasmic_nfkb2_density of this t m a
	 */
	public long getCytoplasmic_nfkb2_density();

	/**
	 * Sets the cytoplasmic_nfkb2_density of this t m a.
	 *
	 * @param cytoplasmic_nfkb2_density the cytoplasmic_nfkb2_density of this t m a
	 */
	public void setCytoplasmic_nfkb2_density(long cytoplasmic_nfkb2_density);

	/**
	 * Returns the nuclear_nfkb2_intensity of this t m a.
	 *
	 * @return the nuclear_nfkb2_intensity of this t m a
	 */
	public long getNuclear_nfkb2_intensity();

	/**
	 * Sets the nuclear_nfkb2_intensity of this t m a.
	 *
	 * @param nuclear_nfkb2_intensity the nuclear_nfkb2_intensity of this t m a
	 */
	public void setNuclear_nfkb2_intensity(long nuclear_nfkb2_intensity);

	/**
	 * Returns the nuclear_nfkb2_density of this t m a.
	 *
	 * @return the nuclear_nfkb2_density of this t m a
	 */
	public long getNuclear_nfkb2_density();

	/**
	 * Sets the nuclear_nfkb2_density of this t m a.
	 *
	 * @param nuclear_nfkb2_density the nuclear_nfkb2_density of this t m a
	 */
	public void setNuclear_nfkb2_density(long nuclear_nfkb2_density);

	/**
	 * Returns the cytoplasmic_pikb_intensity of this t m a.
	 *
	 * @return the cytoplasmic_pikb_intensity of this t m a
	 */
	public long getCytoplasmic_pikb_intensity();

	/**
	 * Sets the cytoplasmic_pikb_intensity of this t m a.
	 *
	 * @param cytoplasmic_pikb_intensity the cytoplasmic_pikb_intensity of this t m a
	 */
	public void setCytoplasmic_pikb_intensity(long cytoplasmic_pikb_intensity);

	/**
	 * Returns the cytoplasmic_pikb_density of this t m a.
	 *
	 * @return the cytoplasmic_pikb_density of this t m a
	 */
	public long getCytoplasmic_pikb_density();

	/**
	 * Sets the cytoplasmic_pikb_density of this t m a.
	 *
	 * @param cytoplasmic_pikb_density the cytoplasmic_pikb_density of this t m a
	 */
	public void setCytoplasmic_pikb_density(long cytoplasmic_pikb_density);

	/**
	 * Returns the cytoplasmic_phoshpo_pakt_o1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pakt_o1_intensity of this t m a
	 */
	public long getCytoplasmic_phoshpo_pakt_o1_intensity();

	/**
	 * Sets the cytoplasmic_phoshpo_pakt_o1_intensity of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pakt_o1_intensity the cytoplasmic_phoshpo_pakt_o1_intensity of this t m a
	 */
	public void setCytoplasmic_phoshpo_pakt_o1_intensity(
		long cytoplasmic_phoshpo_pakt_o1_intensity);

	/**
	 * Returns the cytoplasmic_phoshpo_pakt_o1_density of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pakt_o1_density of this t m a
	 */
	public long getCytoplasmic_phoshpo_pakt_o1_density();

	/**
	 * Sets the cytoplasmic_phoshpo_pakt_o1_density of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pakt_o1_density the cytoplasmic_phoshpo_pakt_o1_density of this t m a
	 */
	public void setCytoplasmic_phoshpo_pakt_o1_density(
		long cytoplasmic_phoshpo_pakt_o1_density);

	/**
	 * Returns the nuclear_phoshpo_pakt_o1_intensity of this t m a.
	 *
	 * @return the nuclear_phoshpo_pakt_o1_intensity of this t m a
	 */
	public long getNuclear_phoshpo_pakt_o1_intensity();

	/**
	 * Sets the nuclear_phoshpo_pakt_o1_intensity of this t m a.
	 *
	 * @param nuclear_phoshpo_pakt_o1_intensity the nuclear_phoshpo_pakt_o1_intensity of this t m a
	 */
	public void setNuclear_phoshpo_pakt_o1_intensity(
		long nuclear_phoshpo_pakt_o1_intensity);

	/**
	 * Returns the nuclear_phoshpo_pakt_o1_density of this t m a.
	 *
	 * @return the nuclear_phoshpo_pakt_o1_density of this t m a
	 */
	public long getNuclear_phoshpo_pakt_o1_density();

	/**
	 * Sets the nuclear_phoshpo_pakt_o1_density of this t m a.
	 *
	 * @param nuclear_phoshpo_pakt_o1_density the nuclear_phoshpo_pakt_o1_density of this t m a
	 */
	public void setNuclear_phoshpo_pakt_o1_density(
		long nuclear_phoshpo_pakt_o1_density);

	/**
	 * Returns the cytoplasmic_phoshpo_pakt_o2_intensity of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pakt_o2_intensity of this t m a
	 */
	public long getCytoplasmic_phoshpo_pakt_o2_intensity();

	/**
	 * Sets the cytoplasmic_phoshpo_pakt_o2_intensity of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pakt_o2_intensity the cytoplasmic_phoshpo_pakt_o2_intensity of this t m a
	 */
	public void setCytoplasmic_phoshpo_pakt_o2_intensity(
		long cytoplasmic_phoshpo_pakt_o2_intensity);

	/**
	 * Returns the cytoplasmic_phoshpo_pakt_o2_density of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pakt_o2_density of this t m a
	 */
	public long getCytoplasmic_phoshpo_pakt_o2_density();

	/**
	 * Sets the cytoplasmic_phoshpo_pakt_o2_density of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pakt_o2_density the cytoplasmic_phoshpo_pakt_o2_density of this t m a
	 */
	public void setCytoplasmic_phoshpo_pakt_o2_density(
		long cytoplasmic_phoshpo_pakt_o2_density);

	/**
	 * Returns the nuclear_phoshpo_pakt_o2_intensity of this t m a.
	 *
	 * @return the nuclear_phoshpo_pakt_o2_intensity of this t m a
	 */
	public long getNuclear_phoshpo_pakt_o2_intensity();

	/**
	 * Sets the nuclear_phoshpo_pakt_o2_intensity of this t m a.
	 *
	 * @param nuclear_phoshpo_pakt_o2_intensity the nuclear_phoshpo_pakt_o2_intensity of this t m a
	 */
	public void setNuclear_phoshpo_pakt_o2_intensity(
		long nuclear_phoshpo_pakt_o2_intensity);

	/**
	 * Returns the nuclear_phoshpo_pakt_o2_density of this t m a.
	 *
	 * @return the nuclear_phoshpo_pakt_o2_density of this t m a
	 */
	public long getNuclear_phoshpo_pakt_o2_density();

	/**
	 * Sets the nuclear_phoshpo_pakt_o2_density of this t m a.
	 *
	 * @param nuclear_phoshpo_pakt_o2_density the nuclear_phoshpo_pakt_o2_density of this t m a
	 */
	public void setNuclear_phoshpo_pakt_o2_density(
		long nuclear_phoshpo_pakt_o2_density);

	/**
	 * Returns the cytoplasmic_phoshpo_pmtor_o1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pmtor_o1_intensity of this t m a
	 */
	public long getCytoplasmic_phoshpo_pmtor_o1_intensity();

	/**
	 * Sets the cytoplasmic_phoshpo_pmtor_o1_intensity of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pmtor_o1_intensity the cytoplasmic_phoshpo_pmtor_o1_intensity of this t m a
	 */
	public void setCytoplasmic_phoshpo_pmtor_o1_intensity(
		long cytoplasmic_phoshpo_pmtor_o1_intensity);

	/**
	 * Returns the cytoplasmic_phoshpo_pmtor_o1_density of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pmtor_o1_density of this t m a
	 */
	public long getCytoplasmic_phoshpo_pmtor_o1_density();

	/**
	 * Sets the cytoplasmic_phoshpo_pmtor_o1_density of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pmtor_o1_density the cytoplasmic_phoshpo_pmtor_o1_density of this t m a
	 */
	public void setCytoplasmic_phoshpo_pmtor_o1_density(
		long cytoplasmic_phoshpo_pmtor_o1_density);

	/**
	 * Returns the nuclear_phoshpo_pmtor_o1_intensity of this t m a.
	 *
	 * @return the nuclear_phoshpo_pmtor_o1_intensity of this t m a
	 */
	public long getNuclear_phoshpo_pmtor_o1_intensity();

	/**
	 * Sets the nuclear_phoshpo_pmtor_o1_intensity of this t m a.
	 *
	 * @param nuclear_phoshpo_pmtor_o1_intensity the nuclear_phoshpo_pmtor_o1_intensity of this t m a
	 */
	public void setNuclear_phoshpo_pmtor_o1_intensity(
		long nuclear_phoshpo_pmtor_o1_intensity);

	/**
	 * Returns the nuclear_phoshpo_pmtor_o1_density of this t m a.
	 *
	 * @return the nuclear_phoshpo_pmtor_o1_density of this t m a
	 */
	public long getNuclear_phoshpo_pmtor_o1_density();

	/**
	 * Sets the nuclear_phoshpo_pmtor_o1_density of this t m a.
	 *
	 * @param nuclear_phoshpo_pmtor_o1_density the nuclear_phoshpo_pmtor_o1_density of this t m a
	 */
	public void setNuclear_phoshpo_pmtor_o1_density(
		long nuclear_phoshpo_pmtor_o1_density);

	/**
	 * Returns the cytoplasmic_phoshpo_pmtor_o2_intensity of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pmtor_o2_intensity of this t m a
	 */
	public long getCytoplasmic_phoshpo_pmtor_o2_intensity();

	/**
	 * Sets the cytoplasmic_phoshpo_pmtor_o2_intensity of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pmtor_o2_intensity the cytoplasmic_phoshpo_pmtor_o2_intensity of this t m a
	 */
	public void setCytoplasmic_phoshpo_pmtor_o2_intensity(
		long cytoplasmic_phoshpo_pmtor_o2_intensity);

	/**
	 * Returns the cytoplasmic_phoshpo_pmtor_o2_density of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pmtor_o2_density of this t m a
	 */
	public long getCytoplasmic_phoshpo_pmtor_o2_density();

	/**
	 * Sets the cytoplasmic_phoshpo_pmtor_o2_density of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pmtor_o2_density the cytoplasmic_phoshpo_pmtor_o2_density of this t m a
	 */
	public void setCytoplasmic_phoshpo_pmtor_o2_density(
		long cytoplasmic_phoshpo_pmtor_o2_density);

	/**
	 * Returns the nuclear_phoshpo_pmtor_o2_intensity of this t m a.
	 *
	 * @return the nuclear_phoshpo_pmtor_o2_intensity of this t m a
	 */
	public long getNuclear_phoshpo_pmtor_o2_intensity();

	/**
	 * Sets the nuclear_phoshpo_pmtor_o2_intensity of this t m a.
	 *
	 * @param nuclear_phoshpo_pmtor_o2_intensity the nuclear_phoshpo_pmtor_o2_intensity of this t m a
	 */
	public void setNuclear_phoshpo_pmtor_o2_intensity(
		long nuclear_phoshpo_pmtor_o2_intensity);

	/**
	 * Returns the nuclear_phoshpo_pmtor_o2_density of this t m a.
	 *
	 * @return the nuclear_phoshpo_pmtor_o2_density of this t m a
	 */
	public long getNuclear_phoshpo_pmtor_o2_density();

	/**
	 * Sets the nuclear_phoshpo_pmtor_o2_density of this t m a.
	 *
	 * @param nuclear_phoshpo_pmtor_o2_density the nuclear_phoshpo_pmtor_o2_density of this t m a
	 */
	public void setNuclear_phoshpo_pmtor_o2_density(
		long nuclear_phoshpo_pmtor_o2_density);

	/**
	 * Returns the cytoplasmic_phoshpo_pp70s6k_o1_density of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pp70s6k_o1_density of this t m a
	 */
	public long getCytoplasmic_phoshpo_pp70s6k_o1_density();

	/**
	 * Sets the cytoplasmic_phoshpo_pp70s6k_o1_density of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pp70s6k_o1_density the cytoplasmic_phoshpo_pp70s6k_o1_density of this t m a
	 */
	public void setCytoplasmic_phoshpo_pp70s6k_o1_density(
		long cytoplasmic_phoshpo_pp70s6k_o1_density);

	/**
	 * Returns the nuclear_phoshpo_pp70s6k_o1_intensity of this t m a.
	 *
	 * @return the nuclear_phoshpo_pp70s6k_o1_intensity of this t m a
	 */
	public long getNuclear_phoshpo_pp70s6k_o1_intensity();

	/**
	 * Sets the nuclear_phoshpo_pp70s6k_o1_intensity of this t m a.
	 *
	 * @param nuclear_phoshpo_pp70s6k_o1_intensity the nuclear_phoshpo_pp70s6k_o1_intensity of this t m a
	 */
	public void setNuclear_phoshpo_pp70s6k_o1_intensity(
		long nuclear_phoshpo_pp70s6k_o1_intensity);

	/**
	 * Returns the nuclear_phoshpo_pp70s6k_o1_density of this t m a.
	 *
	 * @return the nuclear_phoshpo_pp70s6k_o1_density of this t m a
	 */
	public long getNuclear_phoshpo_pp70s6k_o1_density();

	/**
	 * Sets the nuclear_phoshpo_pp70s6k_o1_density of this t m a.
	 *
	 * @param nuclear_phoshpo_pp70s6k_o1_density the nuclear_phoshpo_pp70s6k_o1_density of this t m a
	 */
	public void setNuclear_phoshpo_pp70s6k_o1_density(
		long nuclear_phoshpo_pp70s6k_o1_density);

	/**
	 * Returns the cytoplasmic_phoshpo_pp70s6k_o2_intensity of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pp70s6k_o2_intensity of this t m a
	 */
	public long getCytoplasmic_phoshpo_pp70s6k_o2_intensity();

	/**
	 * Sets the cytoplasmic_phoshpo_pp70s6k_o2_intensity of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pp70s6k_o2_intensity the cytoplasmic_phoshpo_pp70s6k_o2_intensity of this t m a
	 */
	public void setCytoplasmic_phoshpo_pp70s6k_o2_intensity(
		long cytoplasmic_phoshpo_pp70s6k_o2_intensity);

	/**
	 * Returns the cytoplasmic_phoshpo_pp70s6k_o2_density of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pp70s6k_o2_density of this t m a
	 */
	public long getCytoplasmic_phoshpo_pp70s6k_o2_density();

	/**
	 * Sets the cytoplasmic_phoshpo_pp70s6k_o2_density of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pp70s6k_o2_density the cytoplasmic_phoshpo_pp70s6k_o2_density of this t m a
	 */
	public void setCytoplasmic_phoshpo_pp70s6k_o2_density(
		long cytoplasmic_phoshpo_pp70s6k_o2_density);

	/**
	 * Returns the nuclear_phoshpo_pp70s6k_o2_intensity of this t m a.
	 *
	 * @return the nuclear_phoshpo_pp70s6k_o2_intensity of this t m a
	 */
	public long getNuclear_phoshpo_pp70s6k_o2_intensity();

	/**
	 * Sets the nuclear_phoshpo_pp70s6k_o2_intensity of this t m a.
	 *
	 * @param nuclear_phoshpo_pp70s6k_o2_intensity the nuclear_phoshpo_pp70s6k_o2_intensity of this t m a
	 */
	public void setNuclear_phoshpo_pp70s6k_o2_intensity(
		long nuclear_phoshpo_pp70s6k_o2_intensity);

	/**
	 * Returns the nuclear_phoshpo_pp70s6k_o2_density of this t m a.
	 *
	 * @return the nuclear_phoshpo_pp70s6k_o2_density of this t m a
	 */
	public long getNuclear_phoshpo_pp70s6k_o2_density();

	/**
	 * Sets the nuclear_phoshpo_pp70s6k_o2_density of this t m a.
	 *
	 * @param nuclear_phoshpo_pp70s6k_o2_density the nuclear_phoshpo_pp70s6k_o2_density of this t m a
	 */
	public void setNuclear_phoshpo_pp70s6k_o2_density(
		long nuclear_phoshpo_pp70s6k_o2_density);

	/**
	 * Returns the cytoplasmic_phoshpo_pp70s6k_o1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pp70s6k_o1_intensity of this t m a
	 */
	public long getCytoplasmic_phoshpo_pp70s6k_o1_intensity();

	/**
	 * Sets the cytoplasmic_phoshpo_pp70s6k_o1_intensity of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pp70s6k_o1_intensity the cytoplasmic_phoshpo_pp70s6k_o1_intensity of this t m a
	 */
	public void setCytoplasmic_phoshpo_pp70s6k_o1_intensity(
		long cytoplasmic_phoshpo_pp70s6k_o1_intensity);

	/**
	 * Returns the cytoplasmic_phoshpo_pten_o1_intensity of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pten_o1_intensity of this t m a
	 */
	public long getCytoplasmic_phoshpo_pten_o1_intensity();

	/**
	 * Sets the cytoplasmic_phoshpo_pten_o1_intensity of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pten_o1_intensity the cytoplasmic_phoshpo_pten_o1_intensity of this t m a
	 */
	public void setCytoplasmic_phoshpo_pten_o1_intensity(
		long cytoplasmic_phoshpo_pten_o1_intensity);

	/**
	 * Returns the cytoplasmic_phoshpo_pten_o1_density of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pten_o1_density of this t m a
	 */
	public long getCytoplasmic_phoshpo_pten_o1_density();

	/**
	 * Sets the cytoplasmic_phoshpo_pten_o1_density of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pten_o1_density the cytoplasmic_phoshpo_pten_o1_density of this t m a
	 */
	public void setCytoplasmic_phoshpo_pten_o1_density(
		long cytoplasmic_phoshpo_pten_o1_density);

	/**
	 * Returns the nuclear_phoshpo_pten_o1_intensity of this t m a.
	 *
	 * @return the nuclear_phoshpo_pten_o1_intensity of this t m a
	 */
	public long getNuclear_phoshpo_pten_o1_intensity();

	/**
	 * Sets the nuclear_phoshpo_pten_o1_intensity of this t m a.
	 *
	 * @param nuclear_phoshpo_pten_o1_intensity the nuclear_phoshpo_pten_o1_intensity of this t m a
	 */
	public void setNuclear_phoshpo_pten_o1_intensity(
		long nuclear_phoshpo_pten_o1_intensity);

	/**
	 * Returns the nuclear_phoshpo_pten_o1_density of this t m a.
	 *
	 * @return the nuclear_phoshpo_pten_o1_density of this t m a
	 */
	public long getNuclear_phoshpo_pten_o1_density();

	/**
	 * Sets the nuclear_phoshpo_pten_o1_density of this t m a.
	 *
	 * @param nuclear_phoshpo_pten_o1_density the nuclear_phoshpo_pten_o1_density of this t m a
	 */
	public void setNuclear_phoshpo_pten_o1_density(
		long nuclear_phoshpo_pten_o1_density);

	/**
	 * Returns the cytoplasmic_phoshpo_pten_o2_intensity of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pten_o2_intensity of this t m a
	 */
	public long getCytoplasmic_phoshpo_pten_o2_intensity();

	/**
	 * Sets the cytoplasmic_phoshpo_pten_o2_intensity of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pten_o2_intensity the cytoplasmic_phoshpo_pten_o2_intensity of this t m a
	 */
	public void setCytoplasmic_phoshpo_pten_o2_intensity(
		long cytoplasmic_phoshpo_pten_o2_intensity);

	/**
	 * Returns the cytoplasmic_phoshpo_pten_o2_density of this t m a.
	 *
	 * @return the cytoplasmic_phoshpo_pten_o2_density of this t m a
	 */
	public long getCytoplasmic_phoshpo_pten_o2_density();

	/**
	 * Sets the cytoplasmic_phoshpo_pten_o2_density of this t m a.
	 *
	 * @param cytoplasmic_phoshpo_pten_o2_density the cytoplasmic_phoshpo_pten_o2_density of this t m a
	 */
	public void setCytoplasmic_phoshpo_pten_o2_density(
		long cytoplasmic_phoshpo_pten_o2_density);

	/**
	 * Returns the nuclear_phoshpo_pten_o2_intensity of this t m a.
	 *
	 * @return the nuclear_phoshpo_pten_o2_intensity of this t m a
	 */
	public long getNuclear_phoshpo_pten_o2_intensity();

	/**
	 * Sets the nuclear_phoshpo_pten_o2_intensity of this t m a.
	 *
	 * @param nuclear_phoshpo_pten_o2_intensity the nuclear_phoshpo_pten_o2_intensity of this t m a
	 */
	public void setNuclear_phoshpo_pten_o2_intensity(
		long nuclear_phoshpo_pten_o2_intensity);

	/**
	 * Returns the nuclear_phoshpo_pten_o2_density of this t m a.
	 *
	 * @return the nuclear_phoshpo_pten_o2_density of this t m a
	 */
	public long getNuclear_phoshpo_pten_o2_density();

	/**
	 * Sets the nuclear_phoshpo_pten_o2_density of this t m a.
	 *
	 * @param nuclear_phoshpo_pten_o2_density the nuclear_phoshpo_pten_o2_density of this t m a
	 */
	public void setNuclear_phoshpo_pten_o2_density(
		long nuclear_phoshpo_pten_o2_density);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TMA tma);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TMA> toCacheModel();

	@Override
	public TMA toEscapedModel();

	@Override
	public TMA toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}