/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.bbmrieric.services.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LDAPlog service. Represents a row in the &quot;LDAP_LDAPlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.liferay.portlet.bbmrieric.services.model.impl.LDAPlogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.liferay.portlet.bbmrieric.services.model.impl.LDAPlogImpl}.
 * </p>
 *
 * @author reihsr
 * @see LDAPlog
 * @see at.meduni.liferay.portlet.bbmrieric.services.model.impl.LDAPlogImpl
 * @see at.meduni.liferay.portlet.bbmrieric.services.model.impl.LDAPlogModelImpl
 * @generated
 */
public interface LDAPlogModel extends BaseModel<LDAPlog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l d a plog model instance should use the {@link LDAPlog} interface instead.
	 */

	/**
	 * Returns the primary key of this l d a plog.
	 *
	 * @return the primary key of this l d a plog
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l d a plog.
	 *
	 * @param primaryKey the primary key of this l d a plog
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ldaplog ID of this l d a plog.
	 *
	 * @return the ldaplog ID of this l d a plog
	 */
	public long getLdaplogId();

	/**
	 * Sets the ldaplog ID of this l d a plog.
	 *
	 * @param ldaplogId the ldaplog ID of this l d a plog
	 */
	public void setLdaplogId(long ldaplogId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LDAPlog ldaPlog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LDAPlog> toCacheModel();

	@Override
	public LDAPlog toEscapedModel();

	@Override
	public LDAPlog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}