/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.hmmc.liferay.portlet.puch.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ObjectImage service. Represents a row in the &quot;puchmuseum.objectimage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.hmmc.liferay.portlet.puch.model.impl.ObjectImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.hmmc.liferay.portlet.puch.model.impl.ObjectImageImpl}.
 * </p>
 *
 * @author reihsr
 * @see ObjectImage
 * @see at.graz.hmmc.liferay.portlet.puch.model.impl.ObjectImageImpl
 * @see at.graz.hmmc.liferay.portlet.puch.model.impl.ObjectImageModelImpl
 * @generated
 */
public interface ObjectImageModel extends BaseModel<ObjectImage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a object image model instance should use the {@link ObjectImage} interface instead.
	 */

	/**
	 * Returns the primary key of this object image.
	 *
	 * @return the primary key of this object image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this object image.
	 *
	 * @param primaryKey the primary key of this object image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the objectimage ID of this object image.
	 *
	 * @return the objectimage ID of this object image
	 */
	public long getObjectimageId();

	/**
	 * Sets the objectimage ID of this object image.
	 *
	 * @param objectimageId the objectimage ID of this object image
	 */
	public void setObjectimageId(long objectimageId);

	/**
	 * Returns the puchmuseumsobject ID of this object image.
	 *
	 * @return the puchmuseumsobject ID of this object image
	 */
	public long getPuchmuseumsobjectId();

	/**
	 * Sets the puchmuseumsobject ID of this object image.
	 *
	 * @param puchmuseumsobjectId the puchmuseumsobject ID of this object image
	 */
	public void setPuchmuseumsobjectId(long puchmuseumsobjectId);

	/**
	 * Returns the creater user ID of this object image.
	 *
	 * @return the creater user ID of this object image
	 */
	public long getCreaterUserId();

	/**
	 * Sets the creater user ID of this object image.
	 *
	 * @param createrUserId the creater user ID of this object image
	 */
	public void setCreaterUserId(long createrUserId);

	/**
	 * Returns the creater user uuid of this object image.
	 *
	 * @return the creater user uuid of this object image
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreaterUserUuid() throws SystemException;

	/**
	 * Sets the creater user uuid of this object image.
	 *
	 * @param createrUserUuid the creater user uuid of this object image
	 */
	public void setCreaterUserUuid(String createrUserUuid);

	/**
	 * Returns the create date of this object image.
	 *
	 * @return the create date of this object image
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this object image.
	 *
	 * @param createDate the create date of this object image
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this object image.
	 *
	 * @return the modified user ID of this object image
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this object image.
	 *
	 * @param modifiedUserId the modified user ID of this object image
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this object image.
	 *
	 * @return the modified user uuid of this object image
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this object image.
	 *
	 * @param modifiedUserUuid the modified user uuid of this object image
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified date of this object image.
	 *
	 * @return the modified date of this object image
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this object image.
	 *
	 * @param modifiedDate the modified date of this object image
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dlappimageraw ID of this object image.
	 *
	 * @return the dlappimageraw ID of this object image
	 */
	public long getDlappimagerawId();

	/**
	 * Sets the dlappimageraw ID of this object image.
	 *
	 * @param dlappimagerawId the dlappimageraw ID of this object image
	 */
	public void setDlappimagerawId(long dlappimagerawId);

	/**
	 * Returns the dlappimageprocessed ID of this object image.
	 *
	 * @return the dlappimageprocessed ID of this object image
	 */
	public long getDlappimageprocessedId();

	/**
	 * Sets the dlappimageprocessed ID of this object image.
	 *
	 * @param dlappimageprocessedId the dlappimageprocessed ID of this object image
	 */
	public void setDlappimageprocessedId(long dlappimageprocessedId);

	/**
	 * Returns the dlappimageweb ID of this object image.
	 *
	 * @return the dlappimageweb ID of this object image
	 */
	public long getDlappimagewebId();

	/**
	 * Sets the dlappimageweb ID of this object image.
	 *
	 * @param dlappimagewebId the dlappimageweb ID of this object image
	 */
	public void setDlappimagewebId(long dlappimagewebId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ObjectImage objectImage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ObjectImage> toCacheModel();

	@Override
	public ObjectImage toEscapedModel();

	@Override
	public ObjectImage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}