/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.hmmc.liferay.portlet.puch.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PuchMuseumsObjekt service. Represents a row in the &quot;puchmuseum_puchmuseumsobjekt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.hmmc.liferay.portlet.puch.model.impl.PuchMuseumsObjektModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.hmmc.liferay.portlet.puch.model.impl.PuchMuseumsObjektImpl}.
 * </p>
 *
 * @author reihsr
 * @see PuchMuseumsObjekt
 * @see at.graz.hmmc.liferay.portlet.puch.model.impl.PuchMuseumsObjektImpl
 * @see at.graz.hmmc.liferay.portlet.puch.model.impl.PuchMuseumsObjektModelImpl
 * @generated
 */
public interface PuchMuseumsObjektModel extends BaseModel<PuchMuseumsObjekt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a puch museums objekt model instance should use the {@link PuchMuseumsObjekt} interface instead.
	 */

	/**
	 * Returns the primary key of this puch museums objekt.
	 *
	 * @return the primary key of this puch museums objekt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this puch museums objekt.
	 *
	 * @param primaryKey the primary key of this puch museums objekt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the puchmuseumsobject ID of this puch museums objekt.
	 *
	 * @return the puchmuseumsobject ID of this puch museums objekt
	 */
	public long getPuchmuseumsobjectId();

	/**
	 * Sets the puchmuseumsobject ID of this puch museums objekt.
	 *
	 * @param puchmuseumsobjectId the puchmuseumsobject ID of this puch museums objekt
	 */
	public void setPuchmuseumsobjectId(long puchmuseumsobjectId);

	/**
	 * Returns the creater user ID of this puch museums objekt.
	 *
	 * @return the creater user ID of this puch museums objekt
	 */
	public long getCreaterUserId();

	/**
	 * Sets the creater user ID of this puch museums objekt.
	 *
	 * @param createrUserId the creater user ID of this puch museums objekt
	 */
	public void setCreaterUserId(long createrUserId);

	/**
	 * Returns the creater user uuid of this puch museums objekt.
	 *
	 * @return the creater user uuid of this puch museums objekt
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreaterUserUuid() throws SystemException;

	/**
	 * Sets the creater user uuid of this puch museums objekt.
	 *
	 * @param createrUserUuid the creater user uuid of this puch museums objekt
	 */
	public void setCreaterUserUuid(String createrUserUuid);

	/**
	 * Returns the create date of this puch museums objekt.
	 *
	 * @return the create date of this puch museums objekt
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this puch museums objekt.
	 *
	 * @param createDate the create date of this puch museums objekt
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this puch museums objekt.
	 *
	 * @return the modified user ID of this puch museums objekt
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this puch museums objekt.
	 *
	 * @param modifiedUserId the modified user ID of this puch museums objekt
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this puch museums objekt.
	 *
	 * @return the modified user uuid of this puch museums objekt
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this puch museums objekt.
	 *
	 * @param modifiedUserUuid the modified user uuid of this puch museums objekt
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified date of this puch museums objekt.
	 *
	 * @return the modified date of this puch museums objekt
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this puch museums objekt.
	 *
	 * @param modifiedDate the modified date of this puch museums objekt
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the objekttyp of this puch museums objekt.
	 *
	 * @return the objekttyp of this puch museums objekt
	 */
	@AutoEscape
	public String getObjekttyp();

	/**
	 * Sets the objekttyp of this puch museums objekt.
	 *
	 * @param objekttyp the objekttyp of this puch museums objekt
	 */
	public void setObjekttyp(String objekttyp);

	/**
	 * Returns the objektid of this puch museums objekt.
	 *
	 * @return the objektid of this puch museums objekt
	 */
	public long getObjektid();

	/**
	 * Sets the objektid of this puch museums objekt.
	 *
	 * @param objektid the objektid of this puch museums objekt
	 */
	public void setObjektid(long objektid);

	/**
	 * Returns the folder of this puch museums objekt.
	 *
	 * @return the folder of this puch museums objekt
	 */
	@AutoEscape
	public String getFolder();

	/**
	 * Sets the folder of this puch museums objekt.
	 *
	 * @param folder the folder of this puch museums objekt
	 */
	public void setFolder(String folder);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PuchMuseumsObjekt puchMuseumsObjekt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PuchMuseumsObjekt> toCacheModel();

	@Override
	public PuchMuseumsObjekt toEscapedModel();

	@Override
	public PuchMuseumsObjekt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}