/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bcnet.portlet.biobank.model;

import com.bcnet.portlet.biobank.service.persistence.BiobankContactPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BiobankContact service. Represents a row in the &quot;biobankcontact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bcnet.portlet.biobank.model.impl.BiobankContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bcnet.portlet.biobank.model.impl.BiobankContactImpl}.
 * </p>
 *
 * @author suyama
 * @see BiobankContact
 * @see com.bcnet.portlet.biobank.model.impl.BiobankContactImpl
 * @see com.bcnet.portlet.biobank.model.impl.BiobankContactModelImpl
 * @generated
 */
public interface BiobankContactModel extends BaseModel<BiobankContact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a biobank contact model instance should use the {@link BiobankContact} interface instead.
	 */

	/**
	 * Returns the primary key of this biobank contact.
	 *
	 * @return the primary key of this biobank contact
	 */
	public BiobankContactPK getPrimaryKey();

	/**
	 * Sets the primary key of this biobank contact.
	 *
	 * @param primaryKey the primary key of this biobank contact
	 */
	public void setPrimaryKey(BiobankContactPK primaryKey);

	/**
	 * Returns the biobank db ID of this biobank contact.
	 *
	 * @return the biobank db ID of this biobank contact
	 */
	public long getBiobankDbId();

	/**
	 * Sets the biobank db ID of this biobank contact.
	 *
	 * @param biobankDbId the biobank db ID of this biobank contact
	 */
	public void setBiobankDbId(long biobankDbId);

	/**
	 * Returns the contact ID of this biobank contact.
	 *
	 * @return the contact ID of this biobank contact
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this biobank contact.
	 *
	 * @param contactId the contact ID of this biobank contact
	 */
	public void setContactId(long contactId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BiobankContact biobankContact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BiobankContact> toCacheModel();

	@Override
	public BiobankContact toEscapedModel();

	@Override
	public BiobankContact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}