/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bcnet.portlet.biobank.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BiobankGeneralInformation service. Represents a row in the &quot;biobank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bcnet.portlet.biobank.model.impl.BiobankGeneralInformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bcnet.portlet.biobank.model.impl.BiobankGeneralInformationImpl}.
 * </p>
 *
 * @author suyama
 * @see BiobankGeneralInformation
 * @see com.bcnet.portlet.biobank.model.impl.BiobankGeneralInformationImpl
 * @see com.bcnet.portlet.biobank.model.impl.BiobankGeneralInformationModelImpl
 * @generated
 */
public interface BiobankGeneralInformationModel extends BaseModel<BiobankGeneralInformation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a biobank general information model instance should use the {@link BiobankGeneralInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this biobank general information.
	 *
	 * @return the primary key of this biobank general information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this biobank general information.
	 *
	 * @param primaryKey the primary key of this biobank general information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the biobank db ID of this biobank general information.
	 *
	 * @return the biobank db ID of this biobank general information
	 */
	public long getBiobankDbId();

	/**
	 * Sets the biobank db ID of this biobank general information.
	 *
	 * @param biobankDbId the biobank db ID of this biobank general information
	 */
	public void setBiobankDbId(long biobankDbId);

	/**
	 * Returns the biobank ID of this biobank general information.
	 *
	 * @return the biobank ID of this biobank general information
	 */
	@AutoEscape
	public String getBiobankId();

	/**
	 * Sets the biobank ID of this biobank general information.
	 *
	 * @param biobankId the biobank ID of this biobank general information
	 */
	public void setBiobankId(String biobankId);

	/**
	 * Returns the acronym of this biobank general information.
	 *
	 * @return the acronym of this biobank general information
	 */
	@AutoEscape
	public String getAcronym();

	/**
	 * Sets the acronym of this biobank general information.
	 *
	 * @param acronym the acronym of this biobank general information
	 */
	public void setAcronym(String acronym);

	/**
	 * Returns the url of this biobank general information.
	 *
	 * @return the url of this biobank general information
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this biobank general information.
	 *
	 * @param url the url of this biobank general information
	 */
	public void setUrl(String url);

	/**
	 * Returns the juristic person ID of this biobank general information.
	 *
	 * @return the juristic person ID of this biobank general information
	 */
	public long getJuristicPersonId();

	/**
	 * Sets the juristic person ID of this biobank general information.
	 *
	 * @param juristicPersonId the juristic person ID of this biobank general information
	 */
	public void setJuristicPersonId(long juristicPersonId);

	/**
	 * Returns the country code of this biobank general information.
	 *
	 * @return the country code of this biobank general information
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this biobank general information.
	 *
	 * @param countryCode the country code of this biobank general information
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the description of this biobank general information.
	 *
	 * @return the description of this biobank general information
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this biobank general information.
	 *
	 * @param description the description of this biobank general information
	 */
	public void setDescription(String description);

	/**
	 * Returns the backup of this biobank general information.
	 *
	 * @return the backup of this biobank general information
	 */
	public boolean getBackup();

	/**
	 * Returns <code>true</code> if this biobank general information is backup.
	 *
	 * @return <code>true</code> if this biobank general information is backup; <code>false</code> otherwise
	 */
	public boolean isBackup();

	/**
	 * Sets whether this biobank general information is backup.
	 *
	 * @param backup the backup of this biobank general information
	 */
	public void setBackup(boolean backup);

	/**
	 * Returns the training courses of this biobank general information.
	 *
	 * @return the training courses of this biobank general information
	 */
	public boolean getTrainingCourses();

	/**
	 * Returns <code>true</code> if this biobank general information is training courses.
	 *
	 * @return <code>true</code> if this biobank general information is training courses; <code>false</code> otherwise
	 */
	public boolean isTrainingCourses();

	/**
	 * Sets whether this biobank general information is training courses.
	 *
	 * @param trainingCourses the training courses of this biobank general information
	 */
	public void setTrainingCourses(boolean trainingCourses);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BiobankGeneralInformation biobankGeneralInformation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BiobankGeneralInformation> toCacheModel();

	@Override
	public BiobankGeneralInformation toEscapedModel();

	@Override
	public BiobankGeneralInformation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}