/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.rdconnect.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MasterCandidateLinkCandidate service. Represents a row in the &quot;rdconnect.master_candidate_link_candidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.liferay.portlet.rdconnect.model.impl.MasterCandidateLinkCandidateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.liferay.portlet.rdconnect.model.impl.MasterCandidateLinkCandidateImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see MasterCandidateLinkCandidate
 * @see at.meduni.liferay.portlet.rdconnect.model.impl.MasterCandidateLinkCandidateImpl
 * @see at.meduni.liferay.portlet.rdconnect.model.impl.MasterCandidateLinkCandidateModelImpl
 * @generated
 */
public interface MasterCandidateLinkCandidateModel extends BaseModel<MasterCandidateLinkCandidate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a master candidate link candidate model instance should use the {@link MasterCandidateLinkCandidate} interface instead.
	 */

	/**
	 * Returns the primary key of this master candidate link candidate.
	 *
	 * @return the primary key of this master candidate link candidate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this master candidate link candidate.
	 *
	 * @param primaryKey the primary key of this master candidate link candidate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the link ID of this master candidate link candidate.
	 *
	 * @return the link ID of this master candidate link candidate
	 */
	public long getLinkId();

	/**
	 * Sets the link ID of this master candidate link candidate.
	 *
	 * @param linkId the link ID of this master candidate link candidate
	 */
	public void setLinkId(long linkId);

	/**
	 * Returns the candidate ID of this master candidate link candidate.
	 *
	 * @return the candidate ID of this master candidate link candidate
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this master candidate link candidate.
	 *
	 * @param candidateId the candidate ID of this master candidate link candidate
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the master candidate ID of this master candidate link candidate.
	 *
	 * @return the master candidate ID of this master candidate link candidate
	 */
	public long getMasterCandidateId();

	/**
	 * Sets the master candidate ID of this master candidate link candidate.
	 *
	 * @param masterCandidateId the master candidate ID of this master candidate link candidate
	 */
	public void setMasterCandidateId(long masterCandidateId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.meduni.liferay.portlet.rdconnect.model.MasterCandidateLinkCandidate masterCandidateLinkCandidate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.meduni.liferay.portlet.rdconnect.model.MasterCandidateLinkCandidate> toCacheModel();

	@Override
	public at.meduni.liferay.portlet.rdconnect.model.MasterCandidateLinkCandidate toEscapedModel();

	@Override
	public at.meduni.liferay.portlet.rdconnect.model.MasterCandidateLinkCandidate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}