/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.rdconnect.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the RDCRecommender service. Represents a row in the &quot;rdconnect.rdcrecommender&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.meduni.liferay.portlet.rdconnect.model.impl.RDCRecommenderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.meduni.liferay.portlet.rdconnect.model.impl.RDCRecommenderImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see RDCRecommender
 * @see at.meduni.liferay.portlet.rdconnect.model.impl.RDCRecommenderImpl
 * @see at.meduni.liferay.portlet.rdconnect.model.impl.RDCRecommenderModelImpl
 * @generated
 */
public interface RDCRecommenderModel extends BaseModel<RDCRecommender> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a r d c recommender model instance should use the {@link RDCRecommender} interface instead.
	 */

	/**
	 * Returns the primary key of this r d c recommender.
	 *
	 * @return the primary key of this r d c recommender
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this r d c recommender.
	 *
	 * @param primaryKey the primary key of this r d c recommender
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rdcrecommenderid of this r d c recommender.
	 *
	 * @return the rdcrecommenderid of this r d c recommender
	 */
	public long getRdcrecommenderid();

	/**
	 * Sets the rdcrecommenderid of this r d c recommender.
	 *
	 * @param rdcrecommenderid the rdcrecommenderid of this r d c recommender
	 */
	public void setRdcrecommenderid(long rdcrecommenderid);

	/**
	 * Returns the organisation ID of this r d c recommender.
	 *
	 * @return the organisation ID of this r d c recommender
	 */
	public long getOrganisationId();

	/**
	 * Sets the organisation ID of this r d c recommender.
	 *
	 * @param organisationId the organisation ID of this r d c recommender
	 */
	public void setOrganisationId(long organisationId);

	/**
	 * Returns the recommendedorganisation ID of this r d c recommender.
	 *
	 * @return the recommendedorganisation ID of this r d c recommender
	 */
	public long getRecommendedorganisationId();

	/**
	 * Sets the recommendedorganisation ID of this r d c recommender.
	 *
	 * @param recommendedorganisationId the recommendedorganisation ID of this r d c recommender
	 */
	public void setRecommendedorganisationId(long recommendedorganisationId);

	/**
	 * Returns the recommendervalue of this r d c recommender.
	 *
	 * @return the recommendervalue of this r d c recommender
	 */
	public long getRecommendervalue();

	/**
	 * Sets the recommendervalue of this r d c recommender.
	 *
	 * @param recommendervalue the recommendervalue of this r d c recommender
	 */
	public void setRecommendervalue(long recommendervalue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RDCRecommender rdcRecommender);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RDCRecommender> toCacheModel();

	@Override
	public RDCRecommender toEscapedModel();

	@Override
	public RDCRecommender toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}