/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package test.portlet.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MolgenisAPIRequest service. Represents a row in the &quot;test_MolgenisAPIRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link test.portlet.model.impl.MolgenisAPIRequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link test.portlet.model.impl.MolgenisAPIRequestImpl}.
 * </p>
 *
 * @author reihsr
 * @see MolgenisAPIRequest
 * @see test.portlet.model.impl.MolgenisAPIRequestImpl
 * @see test.portlet.model.impl.MolgenisAPIRequestModelImpl
 * @generated
 */
public interface MolgenisAPIRequestModel extends BaseModel<MolgenisAPIRequest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a molgenis a p i request model instance should use the {@link MolgenisAPIRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this molgenis a p i request.
	 *
	 * @return the primary key of this molgenis a p i request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this molgenis a p i request.
	 *
	 * @param primaryKey the primary key of this molgenis a p i request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the molgenisapirequest ID of this molgenis a p i request.
	 *
	 * @return the molgenisapirequest ID of this molgenis a p i request
	 */
	public long getMolgenisapirequestId();

	/**
	 * Sets the molgenisapirequest ID of this molgenis a p i request.
	 *
	 * @param molgenisapirequestId the molgenisapirequest ID of this molgenis a p i request
	 */
	public void setMolgenisapirequestId(long molgenisapirequestId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MolgenisAPIRequest molgenisAPIRequest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MolgenisAPIRequest> toCacheModel();

	@Override
	public MolgenisAPIRequest toEscapedModel();

	@Override
	public MolgenisAPIRequest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}