/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the idcard service. Represents a row in the &quot;rdconnect.idcardapiupdate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.liferay.portlet.bibbox.service.model.impl.idcardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.liferay.portlet.bibbox.service.model.impl.idcardImpl}.
 * </p>
 *
 * @author reihsr
 * @see idcard
 * @see at.graz.meduni.liferay.portlet.bibbox.service.model.impl.idcardImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.service.model.impl.idcardModelImpl
 * @generated
 */
public interface idcardModel extends BaseModel<idcard> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a idcard model instance should use the {@link idcard} interface instead.
	 */

	/**
	 * Returns the primary key of this idcard.
	 *
	 * @return the primary key of this idcard
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this idcard.
	 *
	 * @param primaryKey the primary key of this idcard
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the idcard ID of this idcard.
	 *
	 * @return the idcard ID of this idcard
	 */
	public long getIdcardId();

	/**
	 * Sets the idcard ID of this idcard.
	 *
	 * @param idcardId the idcard ID of this idcard
	 */
	public void setIdcardId(long idcardId);

	/**
	 * Returns the user ID of this idcard.
	 *
	 * @return the user ID of this idcard
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this idcard.
	 *
	 * @param userId the user ID of this idcard
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this idcard.
	 *
	 * @return the user uuid of this idcard
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this idcard.
	 *
	 * @param userUuid the user uuid of this idcard
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the userip of this idcard.
	 *
	 * @return the userip of this idcard
	 */
	@AutoEscape
	public String getUserip();

	/**
	 * Sets the userip of this idcard.
	 *
	 * @param userip the userip of this idcard
	 */
	public void setUserip(String userip);

	/**
	 * Returns the logmsg of this idcard.
	 *
	 * @return the logmsg of this idcard
	 */
	@AutoEscape
	public String getLogmsg();

	/**
	 * Sets the logmsg of this idcard.
	 *
	 * @param logmsg the logmsg of this idcard
	 */
	public void setLogmsg(String logmsg);

	/**
	 * Returns the date of this idcard.
	 *
	 * @return the date of this idcard
	 */
	public Date getDate();

	/**
	 * Sets the date of this idcard.
	 *
	 * @param date the date of this idcard
	 */
	public void setDate(Date date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(idcard idcard);

	@Override
	public int hashCode();

	@Override
	public CacheModel<idcard> toCacheModel();

	@Override
	public idcard toEscapedModel();

	@Override
	public idcard toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}