/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.liferay.portlet.bibbox.service.model.impl;

import at.graz.meduni.liferay.portlet.bibbox.service.model.Logapi;
import at.graz.meduni.liferay.portlet.bibbox.service.model.LogapiModel;
import at.graz.meduni.liferay.portlet.bibbox.service.model.LogapiSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Logapi service. Represents a row in the &quot;rdconnect.logapi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link at.graz.meduni.liferay.portlet.bibbox.service.model.LogapiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LogapiImpl}.
 * </p>
 *
 * @author reihsr
 * @see LogapiImpl
 * @see at.graz.meduni.liferay.portlet.bibbox.service.model.Logapi
 * @see at.graz.meduni.liferay.portlet.bibbox.service.model.LogapiModel
 * @generated
 */
@JSON(strict = true)
public class LogapiModelImpl extends BaseModelImpl<Logapi>
	implements LogapiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a logapi model instance should use the {@link at.graz.meduni.liferay.portlet.bibbox.service.model.Logapi} interface instead.
	 */
	public static final String TABLE_NAME = "rdconnect.logapi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "logapiId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userip", Types.VARCHAR },
			{ "logmsg", Types.VARCHAR },
			{ "date_", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table rdconnect.logapi (logapiId LONG not null primary key,userId LONG,userip VARCHAR(75) null,logmsg TEXT null,date_ DATE null)";
	public static final String TABLE_SQL_DROP = "drop table rdconnect.logapi";
	public static final String ORDER_BY_JPQL = " ORDER BY logapi.logapiId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY rdconnect.logapi.logapiId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.meduni.liferay.portlet.bibbox.service.model.Logapi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.meduni.liferay.portlet.bibbox.service.model.Logapi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Logapi toModel(LogapiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Logapi model = new LogapiImpl();

		model.setLogapiId(soapModel.getLogapiId());
		model.setUserId(soapModel.getUserId());
		model.setUserip(soapModel.getUserip());
		model.setLogmsg(soapModel.getLogmsg());
		model.setDate(soapModel.getDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Logapi> toModels(LogapiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Logapi> models = new ArrayList<Logapi>(soapModels.length);

		for (LogapiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.at.graz.meduni.liferay.portlet.bibbox.service.model.Logapi"));

	public LogapiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _logapiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLogapiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _logapiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Logapi.class;
	}

	@Override
	public String getModelClassName() {
		return Logapi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("logapiId", getLogapiId());
		attributes.put("userId", getUserId());
		attributes.put("userip", getUserip());
		attributes.put("logmsg", getLogmsg());
		attributes.put("date", getDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long logapiId = (Long)attributes.get("logapiId");

		if (logapiId != null) {
			setLogapiId(logapiId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userip = (String)attributes.get("userip");

		if (userip != null) {
			setUserip(userip);
		}

		String logmsg = (String)attributes.get("logmsg");

		if (logmsg != null) {
			setLogmsg(logmsg);
		}

		Date date = (Date)attributes.get("date");

		if (date != null) {
			setDate(date);
		}
	}

	@JSON
	@Override
	public long getLogapiId() {
		return _logapiId;
	}

	@Override
	public void setLogapiId(long logapiId) {
		_logapiId = logapiId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserip() {
		if (_userip == null) {
			return StringPool.BLANK;
		}
		else {
			return _userip;
		}
	}

	@Override
	public void setUserip(String userip) {
		_userip = userip;
	}

	@JSON
	@Override
	public String getLogmsg() {
		if (_logmsg == null) {
			return StringPool.BLANK;
		}
		else {
			return _logmsg;
		}
	}

	@Override
	public void setLogmsg(String logmsg) {
		_logmsg = logmsg;
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		_date = date;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Logapi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Logapi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Logapi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LogapiImpl logapiImpl = new LogapiImpl();

		logapiImpl.setLogapiId(getLogapiId());
		logapiImpl.setUserId(getUserId());
		logapiImpl.setUserip(getUserip());
		logapiImpl.setLogmsg(getLogmsg());
		logapiImpl.setDate(getDate());

		logapiImpl.resetOriginalValues();

		return logapiImpl;
	}

	@Override
	public int compareTo(Logapi logapi) {
		long primaryKey = logapi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Logapi)) {
			return false;
		}

		Logapi logapi = (Logapi)obj;

		long primaryKey = logapi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Logapi> toCacheModel() {
		LogapiCacheModel logapiCacheModel = new LogapiCacheModel();

		logapiCacheModel.logapiId = getLogapiId();

		logapiCacheModel.userId = getUserId();

		logapiCacheModel.userip = getUserip();

		String userip = logapiCacheModel.userip;

		if ((userip != null) && (userip.length() == 0)) {
			logapiCacheModel.userip = null;
		}

		logapiCacheModel.logmsg = getLogmsg();

		String logmsg = logapiCacheModel.logmsg;

		if ((logmsg != null) && (logmsg.length() == 0)) {
			logapiCacheModel.logmsg = null;
		}

		Date date = getDate();

		if (date != null) {
			logapiCacheModel.date = date.getTime();
		}
		else {
			logapiCacheModel.date = Long.MIN_VALUE;
		}

		return logapiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{logapiId=");
		sb.append(getLogapiId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userip=");
		sb.append(getUserip());
		sb.append(", logmsg=");
		sb.append(getLogmsg());
		sb.append(", date=");
		sb.append(getDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("at.graz.meduni.liferay.portlet.bibbox.service.model.Logapi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>logapiId</column-name><column-value><![CDATA[");
		sb.append(getLogapiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userip</column-name><column-value><![CDATA[");
		sb.append(getUserip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>logmsg</column-name><column-value><![CDATA[");
		sb.append(getLogmsg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date</column-name><column-value><![CDATA[");
		sb.append(getDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Logapi.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Logapi.class };
	private long _logapiId;
	private long _userId;
	private String _userUuid;
	private String _userip;
	private String _logmsg;
	private Date _date;
	private Logapi _escapedModel;
}