/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.meduni.liferay.portlet.bbmrieric.model.impl;

import at.meduni.liferay.portlet.bbmrieric.model.DiseaseDiscription;
import at.meduni.liferay.portlet.bbmrieric.service.DiseaseDiscriptionLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the DiseaseDiscription service. Represents a row in the &quot;bbmrieric.diseasediscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiseaseDiscriptionImpl}.
 * </p>
 *
 * @author reihsr
 * @see DiseaseDiscriptionImpl
 * @see at.meduni.liferay.portlet.bbmrieric.model.DiseaseDiscription
 * @generated
 */
public abstract class DiseaseDiscriptionBaseImpl
	extends DiseaseDiscriptionModelImpl implements DiseaseDiscription {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a disease discription model instance should use the {@link DiseaseDiscription} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			DiseaseDiscriptionLocalServiceUtil.addDiseaseDiscription(this);
		}
		else {
			DiseaseDiscriptionLocalServiceUtil.updateDiseaseDiscription(this);
		}
	}
}